### ISSUE TITLE
Support alternative docroot

### ISSUE THREAD

**Issue by lslinnet** [wodby/docker4drupal#103]
In version 1.0.0 it was possible to use ```PHP_DOCROOT``` and ```NGINX_DOCROOT``` to define a subdirectory in the project folder where the drupal site was actually located.
This structure allowed for having a config folder located outside the actual docroot of the drupal site.

Is it possible to do this with 2.0.0?

**Comment by csandanov** [comment]
Yes, just use NGINX_SERVER_ROOT env var for nginx, e.g. /var/www/html/web for composer template project instead of default /var/www/html/
