### ISSUE TITLE
Mailhog not working with Traefik

### ISSUE THREAD

**Issue by lucasan** [wodby/docker4drupal#105]
Hi, I have some Drupal sites (local sites) working with the previous version of Docker4Drupal, but I started using Traefik and all the containers work just fine, but not Mailhog.

Browser says ERR_CONNECTION_REFUSED

Has anyone experienced something like this?

Thanks!

**Comment by csandanov** [comment]
There was a bug in initial 2.0.0 version with incorrect port specified for mailhog service. Make sure you have `traefik.port=8025` under mailhog labels.

**Comment by lucasan** [comment]
I have it like that, but it's not running (at least I cannot access it via Browser)

<img width="516" alt="screen shot 2017-03-14 at 12 37 54 am" src="https://cloud.githubusercontent.com/assets/1307861/23887255/9932a414-084e-11e7-9696-44287ca5a852.png">

**Comment by csandanov** [comment]
How are you trying to access it? As `mailhog.drupal.docker.localhost`? 

Few suggestions:
1. Make sure traefik container is up and running
2. Go to traefik admin UI (port 8080) and look up mailhog status
3. Add public port to mailhog (8025:8025) and check if it works when you access it directly (localhost:8025) without traefik

**Comment by lucasan** [comment]
Hi @csandanov, thanks for your help.

1. Yes, Traefik is up and running (all the other services work as expected)
2. Mailhog status is fine in the Traefik admin UI (just like the others)
3. I added the port and yes, I can access it directly without Traefik.

I'm using Docker CE Version 17.03.0-ce-mac2 (for MAC)

Best,

**Comment by csandanov** [comment]
I have the same version and I can't reproduce it. Paste here your compose file and output of `curl -I mailhog.domain`

**Comment by lucasan** [comment]
This is working, I wasn't using it the right way (maybe a better documentation would be fine).

The Mailhog should be accessed using the port 8000

http://mailhog.drupal.docker.localhost:8000

Thanks

**Comment by aluidens** [comment]
I am still having this problem. I do not understand why. I am have docker version 18.09.7 build CE for Linux and followed the checks mentioned above, except for the port=8000. I did not understand that part.

Your assistance is greatly appreciated. Thank you.
