### ISSUE TITLE
Creating Solr core fails

### ISSUE THREAD

**Issue by meramo** [wodby/docker4drupal#106]
Hello guys,

I'm using the latest (as of 15 March) build of D4D. Two problems with Solr.
1. When executing `docker-compose exec solr solr-create-core my-core drupal8` from the folder with docker-compose.yml file I get this error
`rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "exec: \"create-core\": executable file not found in $PATH"`

2. After logging in to the container and executing `/opt/docker-solr/scripts/solr-create my-core drupal8` get this:
```
Port 8983 is already being used by another process (pid: 1)
Please choose a different port using the -p option.
```

Any advice? Thanks!

**Comment by csandanov** [comment]
See actions usages from README https://github.com/wodby/solr, drupal-solr image inherits from it. The core will be created with search_api_solr module configs.

**Comment by meramo** [comment]
Thanks Chingis, I will try and post the results here. Just curious why it didn't work for the first time..

**Comment by meramo** [comment]
Alright, this command worked me like a charm 
`docker exec -ti [id] make core=mycore -f /usr/local/bin/actions.mk`
Closing
