### ISSUE TITLE
Redis doesn't work with the provided settings in the doc

### ISSUE THREAD

**Issue by khaldoonmasud** [wodby/docker4drupal#107]
I followed the redis documentation http://docs.docker4drupal.org/en/latest/containers/redis/
but the configurations are different in drupal redis module's Readme.md file:
```
$settings['redis.connection']['interface'] = 'PhpRedis'; // Can be "Predis".
$settings['redis.connection']['host']      = '1.2.3.4';  // Your Redis instance hostname.
$settings['cache']['default'] = 'cache.backend.redis';
```

Redis doesn't work with http://docs.docker4drupal.org/en/latest/containers/redis/

**Comment by csandanov** [comment]
Are you using D8 version? Check out [these settings](https://github.com/wodby/docker4drupal/blob/master/test/8/7.1/test.settings.php) we use for tests. I will update the docs.

**Comment by csandanov** [comment]
Instructions updated http://docs.docker4drupal.org/en/latest/containers/redis/
