### ISSUE TITLE
Sending emails

### ISSUE THREAD

**Issue by walkero-gr** [Wodby/docker4drupal#11]
Great work guys. 
I would like to ask about sendmail. I connected to the php container and tried to use /usr/bin/sendmail for a test email. I wanted to be sure that it works and mailhog grabs the emails.

Unfortunately I get the message 
> sendmail: can't connect to remote host (127.0.0.1): Connection refused

Can you help me on this issue? Did I do something wrong with it?

Thank you for your help.

**Comment by PavelPrischepa** [comment]
Hi, @walkero-gr 

You should use sendmail with the following keys `/usr/sbin/sendmail -t -i -S mailhog:1025`.
Also, pay attention to the environment variable `PHP_SENDMAIL_PATH` in the [compose file](https://github.com/Wodby/docker4drupal/blob/master/docker-compose.yml).

**Comment by walkero-gr** [comment]
Hello @PavelPrischepa,
Thank you very much for your reply. And the hard work you do with the package.
