### ISSUE TITLE
Xdebug not working

### ISSUE THREAD

**Issue by arrubiu** [wodby/docker4drupal#114]
I've updated my docker-compose-yml with new version but I'm not able to use xdebug.
Here is my conf:

> php:
>     image: wodby/drupal-php:7.0-2.0.0
>     environment:
>       PHP_SITE_NAME: local
>       PHP_HOST_NAME: localhost
>       PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
>       PHP_XEDBUG: 1
>       PHP_XDEBUG_ENABLED: 1
>       PHP_XDEBUG_REMOTE_AUTOSTART: 1
>     volumes:
>       - ./:/var/www/html

I'm using PhpStorm and these are configurations (nginx is exposed on port 7000):

![schermata del 2017-03-23 09-04-25](https://cloud.githubusercontent.com/assets/1532246/24237815/241639fa-0fa8-11e7-9fd8-eb69808efbfa.png)

![schermata del 2017-03-23 09-04-40](https://cloud.githubusercontent.com/assets/1532246/24237820/291ce1ba-0fa8-11e7-854b-28f53872a264.png)

These confs work on other projects with previous versions of php images (1.0.0).

What's wrong?

**Comment by PavelPrischepa** [comment]
Try to replace `PHP_XDEBUG_ENABLED: 1` by `PHP_XDEBUG_DEFAULT_ENABLE=1`.

**Comment by csandanov** [comment]
More about Xdebug http://docs.docker4drupal.org/en/latest/containers/php/#xdebug

**Comment by arrubiu** [comment]
Ok ok, I'm a stupid, there was a type:

`PHP_XEDBUG: 1`

And obviously should be:

`PHP_XDEBUG: 1`
