### ISSUE TITLE
Add support for XDEBUG or any other debugging tool

### ISSUE THREAD

**Issue by diacu** [wodby/docker4drupal#122]
It would be great to add support for XDEBUG in a php image. Maybe an additional version for each php version?

I am currently handling this by generating my own image in a Dockerfile with 
```shell
if [ $USE_XDEBUG = "yes" ]; then \
          pecl install xdebug && docker-php-ext-enable xdebug; \
          echo "xdebug.remote_enable=on" >> /usr/local/etc/php/conf.d/xdebug.ini; \
          echo "xdebug.remote_autostart=1" >> /usr/local/etc/php/conf.d/xdebug.ini; \
          echo "xdebug.idekey=PHPSTORM" >> /usr/local/etc/php/conf.d/xdebug.ini; \
          echo "xdebug.remote_connect_back=On" >> /usr/local/etc/php/conf.d/xdebug.ini; \
          echo "xdebug.remote_host=127.0.0.1" >> /usr/local/etc/php/conf.d/xdebug.ini; \
  fi
```

Then, in compose I use same image, but with a different environment variable set:
```shell
web: &web
        build: etc/docker/dev/web
        ports:
            - "8000:80"
        [...]
    web_debug:
        <<: *web
        build:
            context: etc/docker/dev/web
            args:
              USE_XDEBUG: "yes"
        ports:
            - "8001:80"
            - "9001:9000"
```

Maybe XDEBUG can be installed on all php images but the content of `/usr/local/etc/php/conf.d/xdebug.ini` can change depending on some environment variables? This way there's no need for another image. 
What do you think?

**Comment by csandanov** [comment]
Please see http://docs.docker4drupal.org/en/latest/containers/php/#xdebug
