### ISSUE TITLE
Vanilla install does not seem to work

### ISSUE THREAD

**Issue by parijke** [wodby/docker4drupal#123]
I tried a plain vanilla spin of the latest docker compose, but I can seem to get it running

**reproduce**
I downloaded the latest docker-compose.yml and keprt it default
I entered the commands for linux at http://docs.docker4drupal.org/en/latest/permissions/
did a docker-compose up -d 
after the download and install was ready, I tried to connect to http://drupal.docker.localhost:8000 and it gives me "server not found"
I try to connect to localhost:8000 and het 404 page not found
I try to connect to localhost:8080 and I get the traefik dashboad

Any help would be highly appreciated.

**Comment by pifagor87** [comment]
similar problem here https://github.com/wodby/docker4drupal/issues/117

**Comment by parijke** [comment]
correct @pifagor87 I close this one

**Comment by f1rf1n** [comment]
That thread is quite long and noisy (lot of other problems and complaints there), but the only solution I could find there is adding the hostnames to /etc/hosts in my ubuntu 16 host. If this needs to be done (and is the best solution) should it not be in the getting started guide?
This is quite tricky when you're starting out with Docker, it is so basic you can't even find it easily cause it is hardly mentioned anywhere...
Can you re-open parijke? So we can discuss getting this mentioned in the readme? or the online docs at least?

**Comment by f1rf1n** [comment]
It is actually already a known issue and in the documentation already also,  https://docker4drupal.readthedocs.io/en/latest/domains/ states at the bottom:
IMPORTANT: you might need to add *.docker.localhost domains manually to your /etc/hosts file 

Unfortunately, this did not work for me, I had to put all the full hostnames into /etc/hosts (ubuntu 16.04)

Furthermore, I read (but did not confirm) in another issue that the *.docker.localhost works for some browsers but not others (don't quite get how, but that might be at least part of the problems.

**Comment by PavelPrischepa** [comment]
@f1rf1n what's in your files:
- /etc/nsswitch.conf
- /etc/resolv.conf
- /etc/hosts
