### ISSUE TITLE
Xdebug not working on docker4drupal 2.0 version with phpstorm zero configuration 

### ISSUE THREAD

**Issue by daliborstojakovic** [wodby/docker4drupal#125]
reverted to 1.3 version and it works fine there

**Comment by csandanov** [comment]
Did you follow http://docs.docker4drupal.org/en/latest/containers/php/#xdebug? Env vars changed a bit.

**Comment by daliborstojakovic** [comment]
Yes. I followed documentation. Set 
PHP_XDEBUG: 1                 # Enable Xdebug extension
PHP_XDEBUG_DEFAULT_ENABLE: 1  # Comment out to disable (default).
PHP_XDEBUG_REMOTE_AUTOSTART: 1 
This is on linux environment so this should be all it takes for linux right? Am I missing something?

**Comment by PavelPrischepa** [comment]
@daliborstojakovic Try to click "Break at first line in PHP script" in "Run" menu.
![image](https://cloud.githubusercontent.com/assets/1525104/24940111/599e5792-1f6b-11e7-9325-935b798bd566.png)

**Comment by daliborstojakovic** [comment]
I had a problem with my environment you can close this.
