### ISSUE TITLE
Include a more up-to-date DrupalConsole

### ISSUE THREAD

**Issue by jurgenhaas** [wodby/docker4drupal#128]
With the latest Drupal core versions the currently included DC version (0.11) doesn't really work well any more. It would be great if you could include 1.0.0-rc16 or later instead.

**Comment by csandanov** [comment]
Use 2.1.0 tagged image, it comes with rc16 version of the drupal console launcher. Please note that with the new console ~1.0 you have to install it separately per each website, the launcher just lets you run console without specifying the full path.

**Comment by jurgenhaas** [comment]
You guys are amazing. Such a turnaround is unusual. I can confirm that the new image is exactly what I was looking for.

Just wondering: what's the best place to watch the progress of all your work. Do you maintain some sort of central changelog somewhere? Simply because there are so many repositories around that I don't know if I can keep an eye on each of them.

**Comment by alesrebec** [comment]
There's a CHANGELOG.md in the root of the project https://github.com/wodby/docker4drupal/blob/master/CHANGELOG.md

**Comment by jurgenhaas** [comment]
Thanks, that the changelog for the docker4drupal project but if one wanted to know what's new in the used images, you have to look into them individually, right?

**Comment by csandanov** [comment]
@jurgenhaas yes, you'll have to go through changes manually. Currently, we do not keep track of changes for images repos because there're too many changes (mostly related to Wodby orchestration). Once it stabilizes a bit we might add CHANGELOG.

**Comment by jurgenhaas** [comment]
That's OK, thanks. I was just asking because it would have saved time and this isuue were redundant.
