### ISSUE TITLE
Drush Alias needed when configured an NGINX_DOCROOT

### ISSUE THREAD

**Issue by lhridley** [Wodby/docker4drupal#13]
if you configure a doc root for nginx using the NGINX_DOCROOT environment variable, executing drush commands per the instructions in the docs and the readme will no longer work properly, since the drush commands are executed from /var/www/html and not from within the drupal root directory.

This can be solved by setting up a drush alias inside the PHP container for user 82.

For example (file named wodby.aliases.drushrc.php):

`<?php
$aliases['dev'] = array(
  'root' => '/var/www/html/www', #adds the NGINX_DOCROOT to the mounted volume path
  'uri'  => 'localhost',
  'path-aliases' => array(
    '%site' => 'sites/default/'
  ),
);`

where "www" is the NGINX_DOCROOT configured.

Then you execute your drush commands as follows:

`docker-compose exec --user 82 php drush @dev <drush-command>`

**Comment by PavelPrischepa** [comment]
I've integrated environment variables into the php container:

- PHP_SITE_NAME: mysite1
- PHP_HOST_NAME: localhost:8000
- PHP_DOCROOT: public

Drush aliase file will be generated automatically:
```
<?php
$aliases['mysite1'] = array(
  'root' => '/var/www/html/public'),
  'uri' => 'localhost:8000',
);
```

So you can execute drush command like: `docker-compose exec --user 82 php drush @mysite1 pml`.

Also, see the [compose file](https://github.com/Wodby/docker4drupal/blob/master/docker-compose.yml#L15).

**Comment by lhridley** [comment]
I just build this project using PHP version 5.6 and I don't see a drush alias file anywhere inside the container, nor do any drush command using a drush alias work.

Please advise.
