### ISSUE TITLE
Change file permissions without root

### ISSUE THREAD

**Issue by yonas** [wodby/docker4drupal#135]
```
total 28
drwxrwxr-x  6 goat             goat 4096 Apr 27 19:08 .
drwxrwxr-x  5 goat             goat 4096 Apr 27 17:36 ..
drwxrwxr-x  5 systemd-timesync goat 4096 Apr 27 18:31 db-data
-rw-rw-r--  1 goat             goat 3508 Apr 27 19:08 docker-compose.yml
drwxrwxr-x  2 goat             goat 4096 Apr 27 18:31 mariadb-init
drwxr-xr-x 10               82   82 4096 Apr 27 16:23 www
```

I'd like to remove the `db-data` and `www` directories, but Docker4Drupal is setting those directories to be owned by another user.

Is it possible to use Docker to completely delete these directories?

**Comment by PavelPrischepa** [comment]
You have to use `sudo rm -f ./db-data ./www`

**Comment by yonas** [comment]
@PavelPrischepa Thanks, I was hoping there was a way without `sudo` either.
