### ISSUE TITLE
Using multiple domains for single installation

### ISSUE THREAD

**Issue by ericmulder1980** [wodby/docker4drupal#137]
Hi there,

I have a use case where i have a single Drupal installation that responds to multiple domain names. In this specific case it is used to switch between a local development database and a remote production database copy on a central database. I guess the same use case would be valid when using the Domain Access module.

I have searched a bit and found the Traefik configuration below to work. I'm curious as if perhaps you have a better solution for this.

```docker.frontend.rule="HostRegexp:dev.domain1.com,dev.domain2.com,dev.domain3.com"```

Kind regards,
Eric Mulder

**Comment by alesrebec** [comment]
You don't need Regexp with the domains in your example.
Just use Host and list the domains or subdomains separated with a comma.

Example: 
`traefik.frontend.rule=Host:www.domain.com,domain.com`

**Comment by ericmulder1980** [comment]
Right, found some more information here : https://docs.traefik.io/basics/

Thanks for your answer.
