### ISSUE TITLE
Installing additional php extensions

### ISSUE THREAD

**Issue by ericmulder1980** [wodby/docker4drupal#138]
Hi there,

For some projects i need to install additional PHP extensions such as TCPDF. I can understand that you are unable to add each and every PHP extension to the PHP image. What would be the best option to do this without creating an own dockerfile for each project that needs an extra php extension?

Kind regards,
Eric Mulder

**Comment by csandanov** [comment]
Are you talking about this one https://github.com/tecnickcom/tc-lib-pdf? We could add it to the generic php image but it says under development. There's no other way to add extensions other than via Dockerfile.

**Comment by ericmulder1980** [comment]
Hi Chingis,

I got a few library names mixed up. TCPdf is actually a PHP Class and the extension i was looking for is not even an extension but a command line tool (WKHTMLTOPDF).

Sorry about that, i will close this issue.

**Comment by Mykola-Veriga** [comment]
Hello

Do we have a way to use wkhtmltopdf in docker4drupal?

**Comment by csandanov** [comment]
we have athenapdf for that https://wodby.com/docs/stacks/athenapdf/

**Comment by superromeo** [comment]
Hello

Do we have a way to use [geos library](https://geophp.net/geos.html) in docker4drupal?
When I use VM I used [this code](https://www.drupal.org/project/geophp/issues/1754138#comment-12552522) .
