### ISSUE TITLE
Access databases from host when running multiple projects

### ISSUE THREAD

**Issue by tanc** [wodby/docker4drupal#139]
I have multiple projects set up with traefik running standalone. I can't figure out how to get sequel pro to connect to one of the mariadb containers. Do I need further traefik config?

**Comment by csandanov** [comment]
By default, MariaDB doesn't expose any public ports and available only inside of containers virtual network, you can just expose unique public port per project. AFAIK, traefik supports only http and https at the moment.

**Comment by tanc** [comment]
If I expose a unique port per project, how do I access that mariadb machine from the host?

**Comment by csandanov** [comment]
The same way as always – `localhost:[PORT]`
