### ISSUE TITLE
Feature Request:  Add a Varnish container

### ISSUE THREAD

**Issue by lhridley** [Wodby/docker4drupal#14]
Please add a Varnish container configured to work with this application stack.

**Comment by csandanov** [comment]
I'm not sure this is a must have for the local environment but since we already have a varnish container we use at Wodby we can add it.

**Comment by PavelPrischepa** [comment]
I've implemented the Varnish-4.1.2 container. See the [compose file](https://github.com/Wodby/docker4drupal/blob/master/docker-compose.yml#L67) for details.
