### ISSUE TITLE
Latest PHP 7 version

### ISSUE THREAD

**Issue by alesrebec** [wodby/docker4drupal#140]
Currently PHP 7.1.3 is used in wodby/drupal-php image.
Where can we change it to 7.1.4 which is out now for about 3 weeks?
It would be good to have that control @csandanov

**Comment by csandanov** [comment]
Use non-tagged image `wodby/drupal-php:7.1`, it's already with 7.1.4.

**Comment by alesrebec** [comment]
I did already tried that but id doesn't rebuild the container with a new image.
I tried: 
* docker-compose up --force-recreate
* docker-compose rm php
* docker compose build php

None of those actually replaced existing image with php 7.1.3 in it.

**Comment by csandanov** [comment]
Run `docker pull wodby/drupal-php:7.1`

**Comment by alesrebec** [comment]
Thanks.
