### ISSUE TITLE
Issue Running drush in drupal installed via composer

### ISSUE THREAD

**Issue by pulasthibandara** [wodby/docker4drupal#141]
Hi,

I just started using this in one of my existing Drupal projects (installed via composer). when running, 

`docker-compose exec --user 82 php drush @dev status` 

I'm getting the following error:

`Could not find the alias @dev`

I tried running drush without the profile, but the work context is `/var/www/html` but my application is in `/var/www/html/www`

I checked for the file `/etc/drush/site-aliases/default.aliases.drushrc.php` via bash in container but it was not found.

Some help is much appreciated :)

**Comment by pulasthibandara** [comment]
btw, Im running `drupal-php:5.6`

**Comment by csandanov** [comment]
Try to specify `-r /var/www/html/web` option

**Comment by alesrebec** [comment]
`docker-compose exec php drush -r ./web status`

**Comment by pulasthibandara** [comment]
@csandanov, @alesrebec 
This worked, Thanks a lot.!

**Comment by duartegarin** [comment]
Hi,
I am having the same issue described above but the fix doesn't work for me.
Any clues?
Cheers,

**Comment by pulasthibandara** [comment]
Did you try with an absolute path `-r /var/www/html/web`? And what's the error that you're getting?
