### ISSUE TITLE
docker-sync does no longer need fswatch/unison/unox

### ISSUE THREAD

**Issue by EugenMayer** [wodby/docker4drupal#142]
with 0.4.0 https://docker-sync.io does no longer need any further installation other then

```
gem install docker-sync
```

Beside that, its faster and does utilise far less CPU 0- http://docs.docker4drupal.org/en/latest/macos/ would need an updatea

**Comment by csandanov** [comment]
Thank you, instructions were updated.

**Comment by EugenMayer** [comment]
Thank you :)
