### ISSUE TITLE
Permissions trouble 

### ISSUE THREAD

**Issue by MatthieuScarset** [wodby/docker4drupal#146]
Hello and thank you for the `docker4drupal` project :)

I am having difficulties working with it because of permissions issues.

Briefly, here's the issue:
- Composer-based Drupal project (https://github.com/MatthieuScarset/drupal-project)
- Clone the repo locally (everything belongs to my local user `matthieu:matthieu`)
- Run `docker-composer -p myproject up -d`
- Enter the PHP container to run composer install and other installation scripts
- **Impossible to create new files** inside the container under `web/sites/default`

Here's an example of the issue with my files and folder. They all belongs to my local user therefore can not be edit/copy/delete from within the container *myproject_php_1*:
```
bash-4.3$ ls -la web/sites/
drwxr-xr-x    3 1000     1000          4096 May 14 05:17 .
drwxr-xr-x    6 1000     1000          4096 May 14 05:17 ..
drwxr-xr-x    2 1000     1000          4096 May 14 05:30 default
-rw-r--r--    1 1000     1000           382 May 14 05:17 development.services.yml
-rw-r--r--    1 1000     1000          4056 May 14 05:17 example.settings.local.php
-rw-r--r--    1 1000     1000          2337 May 14 05:17 example.sites.php
```

For instance, I have a custom composer script which copy the default `settings.php` files for me but it is not working within the container:
```
Failed to copy "/var/www/html/web/sites/default/default.settings.php" to "/var/www/html/web/sites/default/settings.php" because target file could not be opened for writing.
```

Anyone have an idea how I can solve this?

Of course, there is NO way I `chown -R 82:alpine-www-data` my whole project otherwise I wont be able to edit files locally...

**Comment by MatthieuScarset** [comment]
I have tried to `chown -R 82:alpine-www-data my-project/` 

This solve my issue within the Docker container *myproject_php_1* as everything belongs to the right use now... but **I can't edit and save a file locally anymore**.

I already tried [to fix permissions](http://docs.docker4drupal.org/en/latest/permissions/) by adding my to the usergroup but this is obviously not working because folders are `chmod 755` and `chmod 644` by default.

**Comment by csandanov** [comment]
Keep codebase ownership as it is (belong to host user). The permissions fix described in docs just helps you to access files created inside of a container. If you want to create new files inside of sites/default as a user different from www-data, you can do it as root and fix permissions afterward. In general, I don't think it's a big deal to create settings.php manually from the host machine for your local environment, you do it once anyway.

**Comment by MatthieuScarset** [comment]
In my case, I need to be able to create, edit and delete settings.php more than once so it is not really convinient to do that from within the PHP container.

I will try to find where and when this file's permission are set. 

Thank you for your answer @csandanov anyway.
