### ISSUE TITLE
Host url only works if it ends with .locahost

### ISSUE THREAD

**Issue by arled** [wodby/docker4drupal#149]
I want to change this: `- 'traefik.frontend.rule=Host:drupal.docker.localhost'`
To: `- 'traefik.frontend.rule=Host:something.dev'`
The latter does not work as it does not end with .locahost
Have tried adding the following:
```
labels:
  - 'traefik.frontend.rule=HostRegexp:{subdomain:[A-Za-z0-9-]+}.local.cruk.org'
```
How can I get docker/traefik to work with any host url that I define?

**Comment by csandanov** [comment]
Add your domain to /etc/hosts

**Comment by csandanov** [comment]
Use [`-dev` version](https://github.com/wodby/php#-dev-images) of the image, it has `sudo` for all commands.
