### ISSUE TITLE
Need sudo to run Docker app on Mac

### ISSUE THREAD

**Issue by macmladen** [Wodby/docker4drupal#15]
I left this issue on Docker for Mac issue queue: [Docker runs under root, 'docker info' cannot connect to the Docker demon #132](https://github.com/docker/for-mac/issues/132).

I followed instructions on http://Docker4Drupal.org and everything went as expected (Mac 2011 i7, OS X 10.11, 8GB) except

```
$ docker info
```

did not produce anything but error that is can't connect to docker demon.

I was wondering why as I have clearly seen that docker processes are running under my user but still it was unable to connect.

I tried `sudo docker info` and it worked, also `sudo docker-compose up -d` also worked.

Any clue why is that happening?

```
$ docker -v
Docker version 1.12.0, build 8eab29e
```

**Comment by macmladen** [comment]
I found it: [Connecting via unix-socket to the docker-daemon ](https://forums.docker.com/t/connecting-via-unix-socket-to-the-docker-daemon/17396)

While this `bash` variable was defined, docker tried to use **TCP port** instead of **socket**:

```
DOCKER_HOST=tcp://localhost:2375
```

The solution is to **unset** the variable, after that **docker** commands work without `sudo`.

```
unset DOCKER_HOST
```

Before using **Docker for Mac** my machine did not have installed anything docker related so this probably came as a part of installation (will look where it gets defined in restarting sequence).

**Comment by csandanov** [comment]
@macmladen I have exactly the same version of docker on my mac but don't have this environment variable, maybe you installed something like kitematic before

**Comment by csandanov** [comment]
I'm going to close this issue since it's not related to this project and there's nothing we can do here. For details, people can refer to the [issue you've reported](https://github.com/docker/for-mac/issues/132) in the docker for mac repository
