### ISSUE TITLE
How do I access Drupal Code when using built-in vanilla Drupal?

### ISSUE THREAD

**Issue by chuongle** [wodby/docker4drupal#150]
This is a dump question but how do I access my Drupal codebase without sh to the site? I used the default docker-compose.yml provided and got the site running. However I don't see the Drupal project anywhere unless I sh to the container. Will the Drupal code only available if you use the mounted codebase options?  Thanks!

**Comment by csandanov** [comment]
You can add a volume from your host to `/var/www/html` of php container, vanilla Drupal code will be copied there automatically when the container starts. Although you'll probably have a [permission issue](docs.docker4drupal.org/en/latest/permissions/) so you might want to consider using the 2nd option – mounting your own codebase.
