### ISSUE TITLE
drupal 7 404 error

### ISSUE THREAD

**Issue by pferlito** [wodby/docker4drupal#158]
So I basically followed the doc, uncommenting the Drupal 7 options for php and nginx and got a 404 error along with the PHP error below in the logs. Also included is my docker-compose.yml file.

**Stack**:

- **Codebase: built-in vanilla Drupal or mounted codebase?**: Vanilla
- **Drupal version**: 7
- **PHP service image with tag**: wodby/drupal:7-5.6-2.1.2
- **Host OS**: OSX 10.11.16
- **Docker version**: Docker version 1.12.3, build 6b644ec
- **Logs output**: NOTICE: PHP message: PHP Fatal error:  Call to a member function get() on null in /var/www/html/web/core/lib/Drupal/Core/Session/SessionHandler.php on line 76  

version: "2"

services:
  mariadb:
    image: wodby/mariadb:10.1-2.1.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal

  php:
    image: wodby/drupal:7-5.6-2.1.2
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: mariadb
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: drupal
      DB_DRIVER: mysql
    volumes:
      - codebase:/var/www/html

  nginx:
    image: wodby/drupal-nginx:7-1.10-2.1.0
    depends_on:
      - php
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
    volumes:
      - codebase:/var/www/html
    labels:
      - 'traefik.backend=nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:drupal.docker.localhost'

  mailhog:
    image: mailhog/mailhog
    labels:
      - 'traefik.backend=mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.drupal.docker.localhost'

  traefik:
    image: traefik
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '8000:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  codebase:

**Comment by Haehnchen** [comment]
@pferlito see https://github.com/wodby/docker4drupal/pull/159

**Comment by pferlito** [comment]
Thanks @Haehnchen. I used '/var/www/html' as the NGINX_SERVER_ROOT but it still didn't work. I then changed 'codebase' to './codebase' in the volumes and that did work. Thanks for your help.

**Comment by csandanov** [comment]
The value of `NGINX_SERVER_ROOT` is correct. Did you get 404 right after the starting docker-compose or after you installed Drupal?

**Comment by pferlito** [comment]
I get the 404 error after starting docker-compose. No Drupal files are even downloaded. It's not until I change the volumes to '- ./codebase/web:/var/www/html' that I can install Drupal.
So it looks like the 404 is because it's looking for the Drupal files in codebase instead of codebase/web.

**Comment by csandanov** [comment]
Try to stop all container, run `docker system prune` to clean up volumes and run compose file again. Works OK for me, you can access the drupal container and see that there's files in `/var/www/html/web`.

**Comment by pferlito** [comment]
I tried `docker system prune` but it still isn't working for me. Oh well, I'm sure it's something to do with my environment. Here is my docker-compose.yml one last time. Thanks for trying.
```
version: "2"

services:
  mariadb:
    image: wodby/mariadb:10.1-2.1.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal

  php:
    image: wodby/drupal:7-5.6-2.1.2
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: mariadb
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: drupal
      DB_DRIVER: mysql
    volumes:
      - codebase:/var/www/html

  nginx:
    image: wodby/drupal-nginx:7-1.10-2.1.0
    depends_on:
      - php
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html
    volumes:
      - codebase:/var/www/html
    labels:
      - 'traefik.backend=nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:drupal.docker.localhost'

  traefik:
    image: traefik
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '8000:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  codebase:

**Comment by csandanov** [comment]
Just change `NGINX_SERVER_ROOT` to `/var/www/html/web`. I've just tried it with your compose file and it worked, just wait a little for docker to sync files because [it's slow on macos by default](http://docs.docker4drupal.org/en/latest/macos/).

**Comment by pferlito** [comment]
Yes that it working now. Thank you!
