### ISSUE TITLE
Drupal status complaint on HTTP request

### ISSUE THREAD

**Issue by macmladen** [Wodby/docker4drupal#16]
On Drupal report status page, this error is reported

```
Error
	HTTP request status	Fails
Your system or network configuration does not allow Drupal to access web pages, resulting in reduced functionality.
```

Also

```
Database 4 byte UTF-8 support Not enabled
```

```
Upload progress Not enabled
```

**Comment by PavelPrischepa** [comment]
> HTTP request status Fails

It doesn't matter in docker containers, so just disable it in the settings.php:
```
$conf['drupal_http_request_fails'] = FALSE;
```

> Database 4 byte UTF-8 support Not enabled

4 byte UTF-8 already supported in MariaDB container. So all you need to do is convert your DB and add some options to the DB connection config in the settings.php:
```
...
  'charset' => 'utf8mb4',
  'collation' => 'utf8mb4_general_ci',
...
```
Also, see the official [instruction](https://www.drupal.org/node/2754539).

> Upload progress Not enabled

Actually, the upload progress extension is enabled. So it's not an error, just a notice.
Try to use the [FileField Nginx Progress](https://www.drupal.org/project/filefield_nginx_progress) module to solve the warning.
