### ISSUE TITLE
Document new way to solve Mac OS performance issues

### ISSUE THREAD

**Issue by idiazroncero** [wodby/docker4drupal#160]
**Stack**:

- **Codebase:**: Mounted codebase 
- **Drupal version**: 8.3.3
- **PHP service image with tag**:  Not relevant.
- **Host OS**: Mac OS Sierra
- **Docker version**: 17.06.0-rc2-ce-mac14 (¡Important! this is Edge, not Stable channel)

Hi there!

Just a small hint: I was struggling with Mac OS performance problems trying to set up docker-sync when I came across this post:

https://www.drud.com/real-world-performance-gains-docker-for-mac-user-guided-cache

**TL, DR:** Basically, latest Docker versions (edge channel) for Mac have shipped with an alternate way to solve performance issues. You simply have to append `:cached` directly after the volume mounts.

In my case, I was using a mounted codebase so I changed my `docker-compose.yml` to reflect the changes:

````
nginx:
      volumes:
        - ./:/var/www/html:cached
````

````
php:
      volumes:
        - ./:/var/www/html:cached
````

(I am noob to docker so I don't know if it makes sense to add it on both containers or just one of them)

I have noticed a _huge_ improvement on performance. I have had no time to run any tests, but it is noteworthy even at a glance. 

I guess it would be interesting to add this on the [official docs](http://docs.docker4drupal.org/en/latest/macos/) (and even as a commented line on the docker-compose file) since it is by far the simplest and best solution I've tried to this old problem.

**Comment by chuongle** [comment]
I can confirm this is working pretty well. I got docker-sync working but it sometimes does not sync correctly.

**Comment by csandanov** [comment]
http://docs.docker4drupal.org/en/latest/macos/#2-user-guided-caching
