### ISSUE TITLE
Troubles with permissions on windows 10

### ISSUE THREAD

**Issue by alexd73** [wodby/docker4drupal#167]
- **Codebase: built-in vanilla Drupal or mounted codebase?**: mounted codebase
- **Drupal version**: 8
- **PHP service image with tag**: wodby/drupal-php:7.1-2.4.2
- **Host OS**: windows 10
- **Docker version**: 17.06.0-ce-win18 (12627)
- **Logs output**:   

H! I have troubles with permissions on windows 10.
If I first time to load a file to image field, then Drupal create folder for it in default/files
But all other times I have the error: **The file could not be upload** (like this https://github.com/geerlingguy/drupal-vm/issues/99 ![](https://cloud.githubusercontent.com/assets/1831637/7672054/2a917834-fcaa-11e4-9614-c08b1c46ae93.png))

I trying change permissions for files but cannot do it on NTFS system from docker. ![](http://savepic.ru/14690072.png)
The same situation for other commands (chmod -R 777 ./ and chown)
Can you help me?

**Comment by csandanov** [comment]
Have you tried to set 777 permissions on files directory from the host machine? AFAIK Windows 10 has ubuntu shell or something.

**Comment by LoicLEMEUT** [comment]
Hi,

I have the same problem, I dont't know why I can't set 777 permission in default/ folder

I use:
`chmod -R 777 ./`
`chown www-data:ww-data-R ./`

Need help :)

Loïc

**Comment by alexd73** [comment]
I think, Linux permissions impossible if you use Windows and NTFS. I went back to Linux again )

**Comment by LoicLEMEUT** [comment]
In Windows 10, when I create a volume in my docker-composer, permissions are always root:root. Impossible to change with chmod ou chown...

But, if I create a DockerFile, I copy source to /var/www/html, and I put chown www-data permission, it works, but it's not acceptable...

I want back to Linux, but I cant't for the moment. It would be possible to create a volume without root permission in Windows !

Thks :)

**Comment by lcube45** [comment]
I've been adding my workaround for the same problem : https://github.com/wodby/docker4drupal/issues/29

**Comment by LoicLEMEUT** [comment]
Oh, I think a find a trouble here.

It's the method is_writable of PHP. is_writable return false, but if i try to write in the same directory, it's done !

Many method of Drupal use is_writable function, and if I comment in file.inc:309
```
  // The directory exists, so check to see if it is writable.
  $writable = is_writable($directory);
  if (!$writable && ($options & FILE_MODIFY_PERMISSIONS)) {
    return drupal_chmod($directory);
  }

  return $writable;
```
and I return true instead of $writable, all Done, my upload files are uploaded.

**Comment by LoicLEMEUT** [comment]
Read this: https://github.com/wodby/docker4drupal/issues/29#issuecomment-316055081

**Comment by csandanov** [comment]
Documented https://wodby.com/stacks/drupal/docs/local/permissions/#windows
