### ISSUE TITLE
Build is fine locally, but PHP container fails to connect to MySQL container on Travis

### ISSUE THREAD

**Issue by lhridley** [Wodby/docker4drupal#17]
Messages when trying to connect to mysql container from php container on Travis:

`
docker-compose exec --user 82 php /bin/sh -c "mysql -udrupal -pdrupal -h mariadb drupal -e 'SHOW TABLES;'"
`

`
ERROR 2003 (HY000): Can't connect to MySQL server on 'mariadb' (111 "Connection refused")
`

Builds for a local development environment are working fine, using the same docker-compose.yml file for both environments.

**Comment by PavelPrischepa** [comment]
@lhridley Is there any errors in the MariaDB log ` docker-compose logs mariadb`?

**Comment by lhridley** [comment]
I'm going to close this issue -- a new project with a fresh docker4drupal build setup is working properly.
