### ISSUE TITLE
Mount my Drupal Codebase issue

### ISSUE THREAD

**Issue by shaksi** [wodby/docker4drupal#172]
the instruction is missing a step between steps 10 and 11.
It should include: "uncomment volumes section to use docker-sync"
so its as follows:

`volumes:
    codebase:
    docker-sync:
      external: true`

**Comment by csandanov** [comment]
Using docker-sync is optional for macOS users https://docker4drupal.readthedocs.io/en/latest/macos/

**Comment by shaksi** [comment]
understood, took me a little while to figure out.
