### ISSUE TITLE
File not found on a working drupal installation

### ISSUE THREAD

**Issue by walkero-gr** [wodby/docker4drupal#176]
I need your help on something. I have a drupal installation working just fine under docker4drupal. The issue that I have is that when I add a custom php/html file I cannot access it straight, because I get a file not found error. The files are not part of drupal, just testing files.

I guess that this is a nginx configuration. I tried to edit the /etc/nginx/conf.d/drupal file, where I commented the "return 404" command. Unfortunately, after a restart it returns to the default. 

Is there a way to make this work?

**Comment by csandanov** [comment]
You should fork `drupa.conf` and use env var to include your own config. See https://cloud.wodby.com/stackhub/ada51e9b-2204-45ee-8e49-a4151912a168/overview#extra-php-endpoint how to add an extra php endpoint. For html endpoins add a location similar to [this](https://github.com/wodby/drupal-nginx/blob/master/8/1.13/drupal.conf.tpl#L83)
