### ISSUE TITLE
Additional mysql config

### ISSUE THREAD

**Issue by fortis** [Wodby/docker4drupal#18]
Need ability to change/extend default mysql settings, it could be placed as my.cnf near drupal-compose.yml and used as option in yml to extend default settings.
I just need to increase innodb_buffer_pool =)

**Comment by PavelPrischepa** [comment]
Here is the the [simple way](https://github.com/Wodby/docker4drupal/blob/master/docker-compose.yml#L11) to override the MariaDB config:
```
command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
```
It's possible through the use of official mysql init script. See more info in the official [docker image](https://hub.docker.com/_/mysql/).

**Comment by fortis** [comment]
Great! Maybe it makes sense to add this way to README ?

**Comment by PavelPrischepa** [comment]
Yes, it makes sense.
