### ISSUE TITLE
The file could not be uploaded in Windows 10

### ISSUE THREAD

**Issue by jayjaydluffy** [wodby/docker4drupal#185]
### Codebase
Drupal 7 - Open Atrium and other mounted codebase
### Host OS 
Windows 10 Pro
### Services
- wodby/mariadb:10.1-2.3.3
- wodby/drupal-php:5.6-2.4.3
- wodby/drupal-nginx:7-1.13-2.4.2
- phpmyadmin/phpmyadmin
- mailhog/mailhog
- portainer/portainer
### Multiple projects hosted in Traefik
Followed instructions here: http://docker4drupal.readthedocs.io/en/latest/multiple-projects/

### Image field
When trying to upload an image using Image field, this what happens:
![image](https://user-images.githubusercontent.com/13216855/30512900-f057d21c-9b2b-11e7-8325-5d333127e317.png)

In the console:
![image](https://user-images.githubusercontent.com/13216855/30512906-0818d7c0-9b2c-11e7-9e03-3c45103b49b3.png)

### Media Browser
When trying to upload an image using Media Browser:
![image](https://user-images.githubusercontent.com/13216855/30512922-6850c0b2-9b2c-11e7-9e58-a4868ea26bb5.png)

In the console:
![image](https://user-images.githubusercontent.com/13216855/30512925-774759dc-9b2c-11e7-8f30-b06da9f4288d.png)

But getting sources/image from web seems to download the file successfully. What's going on?

### Linux file permission
When changing permissions in Linux, nothing happens
![image](https://user-images.githubusercontent.com/13216855/30512963-4ac19f0c-9b2d-11e7-8191-b10eeafe257c.png)

### Windows: remove read-only
Removing Read-only from /sites/default/files as well as doc root doesn't do anything. Read-only is checked the next time you see directory properties:
![image](https://user-images.githubusercontent.com/13216855/30512975-af845ff6-9b2d-11e7-952c-be7c554b5348.png)

I've spent several days already trying to remove this impediment in my local project. I really need your help.

**Comment by jayjaydluffy** [comment]
When setting up new Drupal site using wodby/drupal, user and group www-data owns the files, but with wodby/drupal-php it is always root:root. Can anyone pls help me with this? Thanks

**Comment by LoicLEMEUT** [comment]
Hi,

Do you see this post ? I have a similar problem.

See this: https://github.com/wodby/docker4drupal/issues/167

And i solved my probleme here: https://github.com/wodby/docker4drupal/issues/29#issuecomment-316055081

Loïc

**Comment by jayjaydluffy** [comment]
not sure i understand why the problem lies in the core file.inc file when Vanilla Drupal images wodby/drupal should be using the same Drupal core files as the Windows-problematic wodby/drupal-php images. if Linux users don't get this problem unlike Windows users then certainly the core Drupal file isn't the culprit, right?

**Comment by cbeier** [comment]
Under Windows there are in general problems with write permissions. Because under Windows all files/directories inside the container belongs to root. And all chown/chmod have no effect, since the changes for this can not be set in Windows (Host for the volumes).

And because the php process in docker4drupal does not run as root, Drupal has no write permissions to the files directory. If the php run as root, files should be writeable (I use this with Drupal 7).

**Comment by jayjaydluffy** [comment]
this works for me: https://github.com/wodby/docker4drupal/issues/29#issuecomment-358756715
