### ISSUE TITLE
Drush Alias is not appearing

### ISSUE THREAD

**Issue by lhridley** [Wodby/docker4drupal#19]
See: #13 

I just built this project using PHP 5.6, after adding the following to my docker-compose.yml file:

 php:
    image: wodby/drupal-php:5.6 # Allowed: 7.0, 5.6.
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_XDEBUG_ENABLED: 1 # Set 1 to enable.
      PHP_SITE_NAME: mydrupalsite.dev
      PHP_HOST_NAME: localhost:8000
      PHP_DOCROOT: www #set this the same as NGINX_DOCROOT

Using the drush alias commands result in:

`
 [error]  Could not find the alias @mydrupalsite.dev 
`

Shelling into the PHP container, I could not locate a drush alias file anywhere in the home directory for the PHP user.

Please advise.

**Comment by PavelPrischepa** [comment]
You can find drush alias in the _/etc/drush/site-aliases/default.aliases.drushrc.php_.
Also, be sure, you pulled the latest wodby/drupal-php image (i.e docker-compose up).
