### ISSUE TITLE
xdebug configuration on Windows 10

### ISSUE THREAD

**Issue by Vacilando** [wodby/docker4drupal#192]
From instructions at https://docker4drupal.readthedocs.io/en/latest/containers/php/ for Windows I gather we need to run "sudo ifconfig lo0 alias 10.0.75.1"
However, that is a Linux command.
Can anyone please clarify how to set an alias for lo0 on Windows 10, and can the docs be updated in that regard?

**Comment by Vacilando** [comment]
Got it to work on Windows 10.

Config in .yml:
PHP_XDEBUG: 1
PHP_XDEBUG_DEFAULT_ENABLE: 1
PHP_XDEBUG_REMOTE_CONNECT_BACK: 0 
PHP_XDEBUG_REMOTE_HOST: "10.0.75.1"

One more step to get it to work with PhpStorm:
Windows Firewall -> Allow an app ... -> enable for PhpStorm

I did have to do any additional IP config.

Please adjust the docs accordingly.

**Comment by csandanov** [comment]
Xdebug documentation has been reworked https://wodby.com/stacks/drupal/docs/local/xdebug/

> I did have to do any additional IP config.

I guess you meant **I did not**

**Comment by ChristopheCaron** [comment]
The "Windows Firewall -> Allow an app ... -> enable for PhpStorm" fix my issue too , thanks for your report !
