### ISSUE TITLE
404 on https://github.com/wodby/drupal-apache

### ISSUE THREAD

**Issue by dakkusingh** [wodby/docker4drupal#196]
Hi guys,
The documentation seems to point to this repo: https://github.com/wodby/drupal-apache but this a 404, however the dockerhub image for wodby/drupal-apache is available. 

Has the git repo been deleted?

**Comment by csandanov** [comment]
The image has been replaced with https://github.com/wodby/php-apache, TBA with the next d4d release

**Comment by csandanov** [comment]
Links updated with 2.4.0 release
