### ISSUE TITLE
Docker bundle for non-drupal applications

### ISSUE THREAD

**Issue by fortis** [wodby/docker4drupal#20]
It would be great to have something like docker4drupal but with non-drupal applications support (silex, symfony, etc) - docker4php.
Seems that drupal-mariadb and drupal-php could be named as wodby-mariadb, wodby-php to be used as common containers.

**Comment by csandanov** [comment]
I believe there are plenty of implementations already, we have to figure out what new/better we can bring

**Comment by csandanov** [comment]
We will likely to add docker4symfony since we now have new 2.0.0 images architecture

**Comment by ghalusa** [comment]
This. +1

**Comment by csandanov** [comment]
We have https://github.com/wodby/docker4php now

**Comment by ghalusa** [comment]
Oh, nice!!! Thanks @csandanov!
