### ISSUE TITLE
Where can I find the drupal directory? 

### ISSUE THREAD

**Issue by TeclisFtw** [wodby/docker4drupal#208]
Hello, 

I'm pretty new to docker. After some researching I was able to install drupal 7 with docker4drupal and got it running, now I'm adding modules and functionality but my question is, where am I storaging this? 

Let's say I want to swap some images from a theme, where is my theme directory so I can do that?

**Comment by TeclisFtw** [comment]
as a side note, I have the docker-compose.yml like

`volumes:
      - codebase:/var/www/html`

`volumes:
      - codebase:/var/www/html`

For both PHP+ Vanilla Drupal and NGINX . 

I just need to find where is the drupal www folder, I've been doing some research about volumes but it doesn't seem to be what I'm looking for, as I am running my containers with the compose. 

Any help that can point me into the right direction is welcome! :)

**Comment by f1rf1n** [comment]
The basic way it is set up does not really allow access to the fiels inside the containers. You DO want to use volumes directive in your yml file. But there are different ways of using it, default is as a volume, but you want it as a bindmount. See https://docs.docker.com/engine/admin/volumes/ for more background info. 
The documentation explains how to set this up a bit.  Check out https://docker4drupal.readthedocs.io/en/latest/ , which states on of the most important steps you have to take : _5. Update nginx and php volumes to - ./:/var/www/html to mount your codebase_

**Comment by csandanov** [comment]
Closing due to no response from OP. And the question is more about how Docker works rather about d4d
