### ISSUE TITLE
RROR: Unable to lock database: Permission denied ERROR: Failed to open apk database: Permission denied

### ISSUE THREAD

**Issue by tingan** [wodby/docker4drupal#212]
How to install package in the docker4drupal container e.g. the nginx container. I tried the apk add ru y, it fails with permission denied. What's the user name and password or what's the default password for root user? thanks.

**Comment by igorbiki** [comment]
Hi,
you should try this
```
ocker-compose exec --user=root --privileged nginx sh
```
nginx is name of the container, you may have to change that.
