### ISSUE TITLE
Feature Request - Add Blackfire.io

### ISSUE THREAD

**Issue by BrizzleRocker** [wodby/docker4drupal#217]
Could we add the Blackfire.io server and agent as an option in the setup? I appreciate that this can be added manually after the fact but would be a really useful addition! https://blackfire.io/

**Comment by csandanov** [comment]
It's already here https://docker4drupal.readthedocs.io/en/latest/containers/blackfire/

**Comment by BrizzleRocker** [comment]
Awesome - thanks!
