### ISSUE TITLE
D8 composer error

### ISSUE THREAD

**Issue by grocc** [wodby/docker4drupal#218]
Hello, refeal to this [issue](https://github.com/wodby/docker4drupal/issues/108),
I have problem on installing modules with composer. Here what I've done...
`docker container ls` give me my container id, _r-D8Devel-php-1-96ee6b14_
`docker exec --user 82 -it r-D8Devel-php-1-96ee6b14 bash` log me in on the right container

now, if i run `composer require drupal/adminimal_admin_toolbar` i have the follow result

`bash-4.3$ composer require drupal/adminimal_admin_toolbar
    1/2:	https://packages.drupal.org/8/drupal/provider-2017-4$68b37340bb1544e20e43327a9b3c7af12963d02dc34fee273f0b0f38668a78cd.json
    2/2:	https://packages.drupal.org/8/drupal/provider-2017-3$718bbbeee5427870a3149fd9ca15a9f6a0877c4cb0432e6372fd175d757f8550.json
    Finished: success: 2, skipped: 0, failure: 0, total: 2
    1/3:	http://packagist.org/p/provider-latest$a9c00cbcbdad6fc9703777aee2f85d9c0beb6a2ccb95115a323f0f1732c0ad55.json
    2/3:	http://packagist.org/p/provider-2017-07$3360a75c99ee26e0ac28d48503e3fe672f664689e9fd5df647921de207585eff.json
    3/3:	http://packagist.org/p/provider-2017-10$f1a9412881055c197e1eaa2eea993e457bf8a3ddea431170d10d0cfb2834a47b.json
    Finished: success: 3, skipped: 0, failure: 0, total: 3
Using version ^1.5 for drupal/adminimal_admin_toolbar
./composer.json has been updated
> DrupalProject\composer\ScriptHandler::checkComposerVersion
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals

Installation failed, reverting ./composer.json to its original content.

                                                                              
  [RuntimeException]                                                          
  web/modules/contrib/admin_toolbar does not exist and could not be created.                                                             
`

checking the permission of the folder i have
drwxr-xr-x    7 www-data www-data      4096 Oct 10 08:40 web
drwxr-xr-x    2 root     1001          4096 Oct 10 08:40 web/modules

so i think that the problem is because i'm logged in as www-data and i want to install something in a folder that i can't manage...
Any idea to solve it?
Thanks!

**Comment by grocc** [comment]
I can fix it, but the solution that I found is not so nice...
before login in docker container, i can become root, cd to the volumes as root and change permission to 777.
In this way composer require work, but is not nice to set permission to 777....
Any idea?

**Comment by igorbiki** [comment]
Having umask 0002 instead of 0022 would be nice. 
I'm adding `sudo chmod -R g+w html/` from host for mapped volumes on every project.

**Comment by csandanov** [comment]
It's an old issue, since 5.0 most of the permissions issues have been fixed due to matching uid/gid, see more at https://wodby.com/stacks/drupal/docs/local/permissions/
