### ISSUE TITLE
PMA container is set to restart always

### ISSUE THREAD

**Issue by macmladen** [Wodby/docker4drupal#22]
That means that as soon as **Docker for Mac** is started (e.g. after the restart) that docker is also restarted although that docker machine is not started.

If that docker machine was stopped with `docker-compose down` it will not restart by itself.

Also `_pma` container can be stopped with `docker-compose down`.

After quitting **Docker for Mac** app and starting again, `_pma` was started but with the name of parent directory and I was unable to stop it with `docker-compose down` but had to use `docker kill 451f3b341d4a` (id of the container).

Why does `_pma` has that **restart** property?

**Comment by PavelPrischepa** [comment]
Yes, you are right, it's useless. We already [removed](https://github.com/Wodby/docker4drupal/commit/f88a86c77f95c986d2d9870e0f0e1662e8c77d4d#diff-4e5e90c6228fd48698d074241c2ba760L36) this property.

**Comment by PavelPrischepa** [comment]
I'm going to close the issue because it was solved.
