### ISSUE TITLE
Docker-compose Permission Denied

### ISSUE THREAD

**Issue by TeclisFtw** [wodby/docker4drupal#220]
Hello all,

I am using windows 10 pro 64 bits, I want to set up a drupal enviroment for a personal project. 

I want to be able to modify my files on drupal so I've mounted my codebase and to do that I've changed the volumes for php and nginx to 

`./:/var/www`

I have placed the docker-compose.yml into the drupal directory. 

I am getting this error ( I'm running everything as admin and I have permissons in all directories ) 

ERROR: for d0f009197cf8_drupal754_php_1  Cannot start service php: oci runtime error: container_linux.go:265: starting c
ontainer process caused "process_linux.go:368: container init caused \"rootfs_linux.go:57: mounting \\\"/C/Users/H├®ctor
/Documents/Docker/drupal-7.54\\\" to rootfs \\\"/var/lib/docker/overlay2/734783110bc98f15eee438256c38029812454151c989316
47352c764aed7f399/merged\\\" at \\\"/var/www\\\" caused \\\"stat /C/Users/H├®ctor/Documents/Docker/drupal-7.54: permissi
on denied\\\"\""

Any idea of why I'm getting this? 

Thanks!

**Comment by csandanov** [comment]
See step 5 in [Mount my Drupal codebase](https://docker4drupal.readthedocs.io/en/latest/#2-mount-my-drupal-codebase)

**Comment by TeclisFtw** [comment]
Hello,

I have corrected that, also checked step 6 is correct, both are now in `./:/var/www/html` .
Still displays the same error.

**Comment by csandanov** [comment]
I guess the problem is that `chown` doesn't work on volumes under Windows, so you should change the default user from `www-data` to `root`, in your compose file:
* add `user: root` directive for php container
* add environment variables `PHP_FPM_USER: www-data`, `PHP_FPM_GROUP: www-data` for php container

ref https://github.com/wodby/php/issues/12

**Comment by TeclisFtw** [comment]
Hello, 

This question might be simple, yet determinant, I have now placed those lines as follow:

`php:
# 1. Images with vanilla Drupal – wodby/drupal:[DRUPAL_VERSION]-[PHP_VERSION]-[STABILITY_TAG].
#    image: wodby/drupal:8-7.1-3.0.0
#    image: wodby/drupal:8-7.0-3.0.0
#    image: wodby/drupal:7-7.1-3.0.0
#   image: wodby/drupal:7-7.0-3.0.0 ------------------
#    image: wodby/drupal:7-5.6-3.0.0
#    image: wodby/drupal:6-5.6-3.0.0
#    image: wodby/drupal:6-5.3-3.0.0
# 2. Images without Drupal – wodby/drupal-php:[PHP_VERSION]-[STABILITY_TAG].
    image: wodby/drupal-php:7.1-3.0.0
#    image: wodby/drupal-php:7.0-3.0.0
#    image: wodby/drupal-php:5.6-3.0.0
#    image: wodby/drupal-php:5.3-3.0.0
    user: root

    environment:
      
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_FPM_CLEAR_ENV: "no"
      DB_HOST: mariadb
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: drupal
      DB_DRIVER: mysql
      PHP_FPM_USER: root
      PHP_FPM_GROUP: root`

This is where they belong I assume. In affirmative case, I still get the same issue. So maybe I am not placing them correctly, thanks for your time replying!

**Comment by TeclisFtw** [comment]
I'm gonna bump the thread. 

I am still having issues with the permissions in Windows. 

Did I put the  
PHP_FPM_USER: www-data
PHP_FPM_GROUP: www-data

to where they belong in my compose file? 

Thanks in advance!

**Comment by csandanov** [comment]
I'm trying to resolve this permission problem on windows once and for all but [I can't launch](https://github.com/docker/for-win/issues/904#issuecomment-351642219) docker for win in my parallels VM. So, let's do it the hard way, paste here your full docker-compose.yml (without commented lines) and I'll try to understand what's going on.

**Comment by csandanov** [comment]
Your compose file starts fine for me on macOS. What docker for win version do you use? Paste here all logs after you run `docker-compose up`.

**Comment by TeclisFtw** [comment]
Sorry I could not answer before, I wasn't home. In fact I'm accesing my computer from remote to be able to answer.

I open Docker and whent to where I'm allocating my docker-compose file, did a `docker-compose up -d `and EVERYTHING WORKED. It went up just fine, I tried accesing my drupal project and I got an Access Denied. 

I did a docker-compose stop. And then again a `docker-compose up -d`, and then the same problem ocurred, here I leave all the messages I get after running `docker-compose up -d`

Thank you for your time! 


PS C:\Users\Héctor\Documents\Docker\drupal-7.54> docker-compose up -d
Starting drupal754_mariadb_1 ...
Recreating drupal754_php_1 ...
Starting drupal754_mailhog_1 ...
Starting drupal754_traefik_1 ...
Starting drupal754_portainer_1 ...
Starting drupal754_mariadb_1
Recreating drupal754_php_1
Starting drupal754_mailhog_1
Starting drupal754_traefik_1
Recreating drupal754_php_1 ... error

ERROR: for drupal754_php_1  Cannot start service php: oci runtime error: container_linux.go:265: starting container proc
ess caused "process_linux.go:368: container init caused \"rootfs_linux.go:57: mounting \\\"/C/Users/H├®ctor/Documents/Do
cker/drupal-7.54\\\" to rootfs \\\"/var/lib/docker/overlay2/8137df052cfa6762ee1a47cfa72a9119dff76ee2bf0ffdcb61c64935b497
31c7/merged\\\" at \\\"/var/www/html\\\" caused \\\"stat /C/Users/H├®ctor/Documents/Docker/drupal-7.54: permission denie
d\\\"\""


ERROR: for php  Cannot start service php: oci runtime error: container_linux.go:265: starting container process caused "
process_linux.go:368: container init caused \"rootfs_linux.go:57: mounting \\\"/C/Users/H├®ctor/Documents/Docker/drupal-
7.54\\\" to rootfs \\\"/var/lib/docker/overlay2/8137df052cfa6762ee1a47cfa72a9119dff76ee2bf0ffdcb61c64935b49731c7/merged\
\\" at \\\"/var/www/html\\\" caused \\\"stat /C/Users/H├®ctor/Documents/Docker/drupal-7.54: permission denied\\\"\""

ERROR: Encountered errors while bringing up the project.

**Comment by TeclisFtw** [comment]
So I tried restarting docker seeing that apparently when just started it ran fine, and I got this issue restarting docker, I'll paste it here, it might help 

Docker hv-sock proxy (vsudd) is not reachable
   en Docker.Backend.ContainerEngine.Linux.ConnectToVsud(TaskCompletionSource`1 vmId) en C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:línea 282
   en Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) en C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:línea 249
   en Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) en C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:línea 122
   en Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) en C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:línea 47
   en Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) en C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:línea 145
