### ISSUE TITLE
Allow config for config_split module?

### ISSUE THREAD

**Issue by dakkusingh** [wodby/docker4drupal#221]
Can we include a generic template for enabling config_split module?

https://github.com/wodby/drupal-php/blob/master/7/templates/drupal8.settings.php.tpl

This could allow for configuring config split options without too much pain.
```
$wodby['config_split_env'] = '{{ getenv "ENV" "" }}';
...
...

if (!empty($wodby['config_split_env'])) {
  $config['config_split.config_split.' . $wodby['config_split_env']]['status'] = TRUE;
}

**Comment by csandanov** [comment]
I don't see this module as very popular or de-facto standard to include it in the template (I can be mistaken). This settings file designed to be included in the original `settings.php` where you can add anything you want after the include.

**Comment by dakkusingh** [comment]
HI @csandanov 
Thanks for your thoughts, I ended up implementing my own init step in a custom bash file like so:

```
#!/usr/bin/env bash

set -e
settings_php="/var/www/html/web/sites/default/settings.php"
disclaimer="\n// MY Specific Settings."
environment='$config["drupal_env"] = "'${ENVIRONMENT}'"; \n'

if [[ $( grep -ic "my.settings.php" "${settings_php}" ) -eq 0 ]]; then
    chmod 644 "${settings_php}"
    echo -e "${disclaimer}" >> "${settings_php}"
    echo -e "${environment}" >> "${settings_php}"

    echo -e 'if (file_exists($app_root . "/" . $site_path . "/my.settings.php")) {
      include $app_root . "/" . $site_path . "/my.settings.php";
    }' >> "${settings_php}"

fi

```

and then in my `my.settings.php`, I can do:

```
if ($config['drupal_env']) {
  $config['config_split.config_split.' . $config['drupal_env']]['status'] = TRUE;
}
else {
  $config['config_split.config_split.local']['status'] = TRUE;
}
```
