### ISSUE TITLE
Unable to send emails via Sendgrid from Drupal deployed with Docker container.

### ISSUE THREAD

**Issue by al-ralovecs** [wodby/docker4drupal#224]
I used Docker4Drupal PHP 7.1 container for my Drupal installation.
Sendgrid is configured via SMTP Authentication Support on my Drupal website.
When sending emails, no errors are determined.
However, emails do not reach recipients.
Do you have any clue on what might be wrong?

**Comment by csandanov** [comment]
If you're using a Drupal module for connecting to sendgrid, it's unlikely the issue of docker images. You might want to look up sendgrid logs to ensure any incoming requests received at all.

**Comment by al-ralovecs** [comment]
I've used 'sendgrid_integration' module instead of 'smtp'. And it worked perfectly. Thank you for your docker images!
