### ISSUE TITLE
Document critical details in docs/index.md, bullet 2.6 

### ISSUE THREAD

**Issue by McFateM** [wodby/docker4drupal#226]
I've been experimenting with docker4drupal for the past few weeks and finally got over a huge hurdle when employing the "existing codebase" and the ./mariadb-init database import options.  The problems I ran into seem to stem from the what's documented (actually what's NOT documented) in section 2.6 of the docs/index.md document which says... 

> Ensure your settings.php uses the same credentials as mariadb service

In my experience, I found it necessary to make the following critical changes to my existing settings.php file:

```
/* In addition to matching credentials with the _mariadb_ service, find the active database section (bottom of the file) and change… */
  'host' => ‘localhost’,
  'port' => '',
to
  'host' => 'mariadb',
  'port' => '3306',
 
```
Failing to make these simple changes produced all kinds of obscure errors (usually a "File not found" or "The website encountered an unexpected error" responses in my browser) that I found difficult to work through.

**Perhaps it would be helpful, particularly for Docker newbies like me, to link the subject line of documentation to an example of a settings.php file?**  My abridged settings.php, I've removed nearly all of the original comments, is included here for reference...

```
<?php

/**
 * @file
 * Drupal site-specific configuration file.
 */

$databases = array();
$config_directories = array();
$settings['hash_salt'] = 'lda1oTfXElOr_evN-Nj4jAJemYxm5-obfuscated-saEOKC3NdlwvE0ZoKShFdlJDIoLwRsQ';
$settings['update_free_access'] = FALSE;

if ($settings['hash_salt']) {
  $prefix = 'drupal.' . hash('sha256', 'drupal.' . $settings['hash_salt']);
  $apc_loader = new \Symfony\Component\ClassLoader\ApcClassLoader($prefix, $class_loader);
  unset($prefix);
  $class_loader->unregister();
  $apc_loader->register();
  $class_loader = $apc_loader;
}

$settings['file_private_path'] = '/var/www/private';
$settings['container_yamls'][] = $app_root . '/' . $site_path . '/services.yml';

$settings['trusted_host_patterns'] = array(
  '^localhost$',
  '^drupal.docker.localhost',					/* added for docker4drupal use */
);

$settings['file_scan_ignore_directories'] = [
  'node_modules',
  'bower_components',
];

$databases['default']['default'] = array (
  'database' => 'drupal',					/* made to match mariadb service */
  'username' => 'drupal', 					/* made to match mariadb service */
  'password' => 'drupal',					/* made to match mariadb service */
  'prefix' => '',
  'host' => 'mariadb',                  			/* was 'localhost' */
  'port' => '3306',						/* was '' */
  'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql',
  'driver' => 'mysql',
);

$settings['install_profile'] = 'standard';
$config_directories['sync'] = 'sites/default/files/config_kxJl1NQwJHofsfsm0nIO40-kxqg0-obfuscated-0VhbFVjR7vdZL5se5uhXNw/sync';
```

**Comment by csandanov** [comment]
Thank you, example added to https://wodby.com/stacks/drupal/docs/local/quick-start/
