### ISSUE TITLE
Root pass for PHP container

### ISSUE THREAD

**Issue by soupman99** [wodby/docker4drupal#228]
I'm getting this error when I try and upload a 21MB site backup.

`The input file exceeds the servers upload_max_filesize or post_max_size limit.`

I tried logging into the Vanilla drupal container and changing `/usr/local/etc/php/conf.d/docker-php.ini` and adding 
`upload_max_filesize = 10M
post_max_size = 10M`
but the `docker-php.ini` keeps getting reset when I restart the container.

How can I avoid the upload_max_filesize error?

**Comment by csandanov** [comment]
We provide env vars to configure php.ini settings, see the list of vars at https://github.com/wodby/php

**Comment by Mykola-Veriga** [comment]
I think we should be able to edit all configs in php.ini.
