### ISSUE TITLE
404 not found using vanilla Drupal 7 

### ISSUE THREAD

**Issue by bradbulger** [wodby/docker4drupal#234]
### Codebase
vanilla
    image: wodby/drupal:7-7.0-3.3.2
  
### Host OS 
os x 10.11.6

### Docker info output
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 8
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.36-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: moby
ID: GWP7:OIFA:M7NL:XPHB:EUTF:PL5M:DDP7:VULO:QT3D:J5XO:CN2G:VBMA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 18
 Goroutines: 30
 System Time: 2018-01-23T22:28:51.039318551Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

### Docker compose file
basically the unchanged 2.5.0 docker-compose.yml file though i did change "localhost" to "local" per some other tickets. i also uncommented the dashboard, which does work at drupal.docker.local:8080

### Logs output
> docker-compose logs mariadb
> Attaching to d7_mariadb_1
> mariadb_1    | Initializing database
> mariadb_1    |
> mariadb_1    | PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !
> mariadb_1    | To do so, start the server, then issue the following commands:
> mariadb_1    |
> mariadb_1    | '/usr/bin/mysqladmin' -u root password 'new-password'
> mariadb_1    | '/usr/bin/mysqladmin' -u root -h  password 'new-password'
> mariadb_1    |
> mariadb_1    | Alternatively you can run:
> mariadb_1    | '/usr/bin/mysql_secure_installation'
> mariadb_1    |
> mariadb_1    | which will also give you the option of removing the test
> mariadb_1    | databases and anonymous user created by default.  This is
> mariadb_1    | strongly recommended for production servers.
> mariadb_1    |
> mariadb_1    | See the MariaDB Knowledgebase at http://mariadb.com/kb or the
> mariadb_1    | MySQL manual for more instructions.
> mariadb_1    |
> mariadb_1    | Please report any problems at http://mariadb.org/jira
> mariadb_1    |
> mariadb_1    | The latest information about MariaDB is available at http://mariadb.org/.
> mariadb_1    | You can find additional information about the MySQL part at:
> mariadb_1    | http://dev.mysql.com
> mariadb_1    | Consider joining MariaDB's strong and vibrant community:
> mariadb_1    | https://mariadb.org/get-involved/
> mariadb_1    |
> mariadb_1    | Database initialized
> mariadb_1    | MySQL init process in progress...
> mariadb_1    | 2018-01-23 22:33:08 140243246574408 [Note] mysqld (mysqld 10.2.11-MariaDB) starting as process 99 ...
> mariadb_1    | 2018-01-23 22:33:08 140243246574408 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
> mariadb_1    | 2018-01-23 22:33:08 140243246574408 [Note] InnoDB: Uses event mutexes
> mariadb_1    | 2018-01-23 22:33:08 140243246574408 [Note] InnoDB: Compressed tables use zlib 1.2.11
> mariadb_1    | 2018-01-23 22:33:08 140243246574408 [Note] InnoDB: Using Linux native AIO
> mariadb_1    | 2018-01-23 22:33:08 140243246574408 [Note] InnoDB: Number of pools: 1
> mariadb_1    | 2018-01-23 22:33:08 140243246574408 [Note] InnoDB: Using SSE2 crc32 instructions
> mariadb_1    | 2018-01-23 22:33:08 140243246574408 [Note] InnoDB: Initializing buffer pool, total size = 1G, instances = 4, chunk size = 128M
> mariadb_1    | 2018-01-23 22:33:08 140243246574408 [Note] InnoDB: Completed initialization of buffer pool
> mariadb_1    | 2018-01-23 22:33:08 140241771719400 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
> mariadb_1    | 2018-01-23 22:33:08 140243246574408 [Note] InnoDB: Highest supported file format is Barracuda.
> mariadb_1    | 2018-01-23 22:33:08 140243246574408 [Note] InnoDB: 128 out of 128 rollback segments are active.
> mariadb_1    | 2018-01-23 22:33:08 140243246574408 [Note] InnoDB: Creating shared tablespace for temporary tables
> mariadb_1    | 2018-01-23 22:33:08 140243246574408 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
> mariadb_1    | 2018-01-23 22:33:08 140243246574408 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
> mariadb_1    | 2018-01-23 22:33:08 140243246574408 [Note] InnoDB: Waiting for purge to start
> mariadb_1    | 2018-01-23 22:33:08 140243246574408 [Note] InnoDB: 5.7.20 started; log sequence number 1619994
> mariadb_1    | 2018-01-23 22:33:08 140241800719080 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
> mariadb_1    | 2018-01-23 22:33:08 140241800719080 [Note] InnoDB: Buffer pool(s) load completed at 180123 22:33:08
> mariadb_1    | 2018-01-23 22:33:08 140243246574408 [Note] Plugin 'FEEDBACK' is disabled.
> mariadb_1    | 2018-01-23 22:33:08 140243246574408 [Warning] 'user' entry 'root@9e47198ec230' ignored in --skip-name-resolve mode.
> mariadb_1    | 2018-01-23 22:33:08 140243246574408 [Warning] 'user' entry '@9e47198ec230' ignored in --skip-name-resolve mode.
> mariadb_1    | 2018-01-23 22:33:08 140243246574408 [Warning] 'proxies_priv' entry '@% root@9e47198ec230' ignored in --skip-name-resolve mode.
> mariadb_1    | 2018-01-23 22:33:08 140243246574408 [Note] Reading of all Master_info entries succeded
> mariadb_1    | 2018-01-23 22:33:08 140243246574408 [Note] Added new Master_info '' to hash table
> mariadb_1    | 2018-01-23 22:33:08 140243246574408 [Note] mysqld: ready for connections.
> mariadb_1    | Version: '10.2.11-MariaDB'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MariaDB Server
> mariadb_1    | 2018-01-23 22:33:10 140241791498984 [Warning] 'proxies_priv' entry '@% root@9e47198ec230' ignored in --skip-name-resolve mode.
> mariadb_1    | 2018-01-23 22:33:10 140241791498984 [Warning] 'proxies_priv' entry '@% root@9e47198ec230' ignored in --skip-name-resolve mode.
> mariadb_1    |
> mariadb_1    | 2018-01-23 22:33:10 140241791179496 [Note] mysqld (unknown): Normal shutdown
> mariadb_1    |
> mariadb_1    | 2018-01-23 22:33:10 140241791179496 [Note] Event Scheduler: Purging the queue. 0 events
> mariadb_1    | 2018-01-23 22:33:10 140241801190120 [Note] InnoDB: FTS optimize thread exiting.
> mariadb_1    | 2018-01-23 22:33:10 140241791179496 [Note] InnoDB: Starting shutdown...
> mariadb_1    | 2018-01-23 22:33:10 140241800719080 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
> mariadb_1    | 2018-01-23 22:33:10 140241800719080 [Note] InnoDB: Buffer pool(s) dump completed at 180123 22:33:10
> mariadb_1    | 2018-01-23 22:33:11 140241791179496 [Note] InnoDB: Shutdown completed; log sequence number 1620013
> mariadb_1    | 2018-01-23 22:33:11 140241791179496 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
> mariadb_1    | 2018-01-23 22:33:11 140241791179496 [Note] mysqld: Shutdown complete
> mariadb_1    |
> mariadb_1    |
> mariadb_1    | MySQL init process done. Ready for start up.
> mariadb_1    |
> mariadb_1    | 2018-01-23 22:33:11 140019270351688 [Note] mysqld (mysqld 10.2.11-MariaDB) starting as process 1 ...
> mariadb_1    | 2018-01-23 22:33:11 140019270351688 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
> mariadb_1    | 2018-01-23 22:33:11 140019270351688 [Note] InnoDB: Uses event mutexes
> mariadb_1    | 2018-01-23 22:33:11 140019270351688 [Note] InnoDB: Compressed tables use zlib 1.2.11
> mariadb_1    | 2018-01-23 22:33:11 140019270351688 [Note] InnoDB: Using Linux native AIO
> mariadb_1    | 2018-01-23 22:33:11 140019270351688 [Note] InnoDB: Number of pools: 1
> mariadb_1    | 2018-01-23 22:33:11 140019270351688 [Note] InnoDB: Using SSE2 crc32 instructions
> mariadb_1    | 2018-01-23 22:33:11 140019270351688 [Note] InnoDB: Initializing buffer pool, total size = 1G, instances = 4, chunk size = 128M
> mariadb_1    | 2018-01-23 22:33:11 140019270351688 [Note] InnoDB: Completed initialization of buffer pool
> mariadb_1    | 2018-01-23 22:33:11 140017795496680 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
> mariadb_1    | 2018-01-23 22:33:11 140019270351688 [Note] InnoDB: Highest supported file format is Barracuda.
> mariadb_1    | 2018-01-23 22:33:11 140019270351688 [Note] InnoDB: 128 out of 128 rollback segments are active.
> mariadb_1    | 2018-01-23 22:33:11 140019270351688 [Note] InnoDB: Creating shared tablespace for temporary tables
> mariadb_1    | 2018-01-23 22:33:11 140019270351688 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
> mariadb_1    | 2018-01-23 22:33:11 140019270351688 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
> mariadb_1    | 2018-01-23 22:33:11 140019270351688 [Note] InnoDB: 5.7.20 started; log sequence number 1620013
> mariadb_1    | 2018-01-23 22:33:11 140017824496360 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
> mariadb_1    | 2018-01-23 22:33:11 140017824496360 [Note] InnoDB: Buffer pool(s) load completed at 180123 22:33:11
> mariadb_1    | 2018-01-23 22:33:11 140019270351688 [Note] Plugin 'FEEDBACK' is disabled.
> mariadb_1    | 2018-01-23 22:33:11 140019270351688 [Note] Server socket created on IP: '0.0.0.0'.
> mariadb_1    | 2018-01-23 22:33:11 140019270351688 [Warning] 'proxies_priv' entry '@% root@9e47198ec230' ignored in --skip-name-resolve mode.
> mariadb_1    | 2018-01-23 22:33:11 140019270351688 [Note] Reading of all Master_info entries succeded
> mariadb_1    | 2018-01-23 22:33:11 140019270351688 [Note] Added new Master_info '' to hash table
> mariadb_1    | 2018-01-23 22:33:11 140019270351688 [Note] mysqld: ready for connections.
> mariadb_1    | Version: '10.2.11-MariaDB'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MariaDB Server
> docker-compose logs php
> Attaching to d7_php_1
> php_1        | DRUPAL_ROOT=/var/www/html/web init.sh
> php_1        | [23-Jan-2018 22:33:05] NOTICE: fpm is running, pid 1
> php_1        | [23-Jan-2018 22:33:05] NOTICE: ready to handle connections
> php_1        | 172.18.0.7 -  23/Jan/2018:22:34:51 +0000 "GET /index.php" 302
> docker-compose logs nginx
> Attaching to d7_nginx_1
> nginx_1      | 2018/01/23 22:33:07 [notice] 1#1: using the "epoll" event method
> nginx_1      | 2018/01/23 22:33:07 [notice] 1#1: nginx/1.13.7
> nginx_1      | 2018/01/23 22:33:07 [notice] 1#1: built by gcc 6.3.0 (Alpine 6.3.0)
> nginx_1      | 2018/01/23 22:33:07 [notice] 1#1: OS: Linux 4.9.36-moby
> nginx_1      | 2018/01/23 22:33:07 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
> nginx_1      | 2018/01/23 22:33:07 [notice] 1#1: start worker processes
> nginx_1      | 2018/01/23 22:33:07 [notice] 1#1: start worker process 27
> nginx_1      | 2018/01/23 22:33:07 [notice] 1#1: start worker process 28
> nginx_1      | 172.18.0.4 - - [23/Jan/2018:22:34:48 +0000] "GET /info.php HTTP/1.1" 404 193 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36"
> nginx_1      | 172.18.0.4 - - [23/Jan/2018:22:34:51 +0000] "GET /index.php HTTP/1.1" 302 5 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36"
> nginx_1      | 172.18.0.4 - - [23/Jan/2018:22:34:51 +0000] "GET /install.php HTTP/1.1" 404 193 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36"
> docker-compose logs mailhog
> Attaching to d7_mailhog_1
> mailhog_1    | 2018/01/23 22:33:05 Using in-memory storage
> mailhog_1    | 2018/01/23 22:33:05 [SMTP] Binding to address: 0.0.0.0:1025
> mailhog_1    | [HTTP] Binding to address: 0.0.0.0:8025
> mailhog_1    | 2018/01/23 22:33:05 Serving under http://0.0.0.0:8025/
> mailhog_1    | Creating API v1 with WebPath:
> mailhog_1    | Creating API v2 with WebPath:
> mailhog_1    | [APIv1] KEEPALIVE /api/v1/events
> docker-compose logs portainer
> Attaching to d7_portainer_1
> portainer_1  | 2018/01/23 22:33:05 Starting Portainer 1.16.1 on :9000
> docker-compose logs traefik
> Attaching to d7_traefik_1
> traefik_1    | time="2018-01-23T22:33:06Z" level=info msg="Using TOML configuration file /dev/null"
> traefik_1    | time="2018-01-23T22:33:06Z" level=warning msg="web provider configuration is deprecated, you should use these options : api, rest provider, ping and metrics"
> traefik_1    | time="2018-01-23T22:33:06Z" level=info msg="Traefik version v1.5.0 built on 2018-01-23_04:42:32PM"
> traefik_1    | time="2018-01-23T22:33:06Z" level=info msg="
> traefik_1    | Stats collection is disabled.
> traefik_1    | Help us improve Traefik by turning this feature on :)
> traefik_1    | More details on: https://docs.traefik.io/basics/#collected-data
> traefik_1    | "
> traefik_1    | time="2018-01-23T22:33:06Z" level=info msg="Preparing server http &{Network: Address::80 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc4200b9560} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
> traefik_1    | time="2018-01-23T22:33:06Z" level=info msg="Preparing server traefik &{Network: Address::8080 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc4200b9580} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
> traefik_1    | time="2018-01-23T22:33:06Z" level=info msg="Starting provider *docker.Provider {"Watch":true,"Filename":"","Constraints":null,"Trace":false,"DebugLogGeneratedTemplate":false,"Endpoint":"unix:///var/run/docker.sock","Domain":"","TLS":null,"ExposedByDefault":true,"UseBindPortIP":false,"SwarmMode":false}"
> traefik_1    | time="2018-01-23T22:33:06Z" level=info msg="Starting server on :80"
> traefik_1    | time="2018-01-23T22:33:06Z" level=info msg="Starting server on :8080"
> traefik_1    | time="2018-01-23T22:33:06Z" level=info msg="Server configuration reloaded on :80"
> traefik_1    | time="2018-01-23T22:33:06Z" level=info msg="Server configuration reloaded on :8080"
> traefik_1    | time="2018-01-23T22:33:08Z" level=info msg="Server configuration reloaded on :80"
> traefik_1    | time="2018-01-23T22:33:08Z" level=info msg="Server configuration reloaded on :8080"
> traefik_1    | time="2018-01-23T22:34:48Z" level=info msg="vulcand/oxy/forward/http: Round trip: http://172.18.0.7:80, code: 404, Length: 182, duration: 975.605µs"
> traefik_1    | time="2018-01-23T22:34:51Z" level=info msg="vulcand/oxy/forward/http: Round trip: http://172.18.0.7:80, code: 302, Length: 0, duration: 22.467777ms"
> traefik_1    | time="2018-01-23T22:34:51Z" level=info msg="vulcand/oxy/forward/http: Round trip: http://172.18.0.7:80, code: 404, Length: 182, duration: 421.227µs"

**Comment by bradbulger** [comment]
I'm sorry I can't figure out how to paste the log file output in a readable format.

**Comment by bradbulger** [comment]
the /var/www/html/web directory doesn't seem to be the document root for the web server. i tried putting an info.php file in there just to check that and it came up as a 404 as well.

**Comment by igorbiki** [comment]
Stop containers, set web server root to `/var/www/html'. Then start containers. That should do it. Drupal 8 requires /web, while D7 does not.

**Comment by bradbulger** [comment]
that's where nginx thinks the root is, and that's where the code is, though - in the web directory. it's where *some* code is anyway. i tried putting the info.php file into /var/www/html just in case but it's still 404. presumably there is some directory somewhere that it's searching. or else the clever redirects are clevering themselves into oblivion.

i tried wget http://localhost and that also gets a 404. so i dunno.

when you say "set web server root" do you mean anything beyond changing all references in the docker-compose file to remove the "/web" part?

**Comment by igorbiki** [comment]
Yeap, if you are using nginx set
```
NGINX_SERVER_ROOT: /var/www/html
```
But make sure to stop containers and then apply change, then start containers again.

**Comment by bradbulger** [comment]
i deleted all the images on this machine and started over with a fresh copy of docker-compose.yml from master (no relevant differences to 2.5.0 that i can see though). now it at least brings up the install.php file. it still gives a 404 on any new file i create in /var/www/html/web (which is where the code is, not in /var/www/html) but maybe that's a nginx thing? i am unfamiliar with it.

i had to change the mysql hostname to be the mariadb container name in the install.php process, but after that, the installation proceeded successfully.

**Comment by igorbiki** [comment]
There are restrictions on which php files nginx will serve. Adding mytest.php will result in 404. But Drupal related php file are fine.

**Comment by bradbulger** [comment]
yes that's how it seemed to be working. thanks.
