### ISSUE TITLE
ERROR: manifest for wodby/drupal-php:5.3-dev-3.3.1 not found

### ISSUE THREAD

**Issue by readingdan** [wodby/docker4drupal#235]
### Codebase
mounted codebase
  
### Host OS 
macOS High Sierra

### Docker info output
Containers: 6
 Running: 1
 Paused: 0
 Stopped: 5
Images: 53
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.855GiB
Name: linuxkit-025000000001
ID: VCWZ:OBY3:MA3C:PEIG:WLPA:SVKG:MBAV:SLEC:62M7:Z6NR:VJ2B:DG2M
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 33
 Goroutines: 48
 System Time: 2018-01-25T14:51:24.640584582Z
 EventsListeners: 2
HTTP Proxy: 
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

### Docker compose file
version: "2"

services:
  mariadb:
    image: wodby/mariadb:10.1-2.1.0
    ports:
      - 45877:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - ./database:/var/lib/mysql # I want to manage volumes manually.
  php:
# image: wodby/drupal-php:5.3-2.1.0
  image: wodby/drupal-php:5.3-dev-3.3.1

    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_FPM_CLEAR_ENV: "no"
      DB_DRIVER: mysql# PHP_MEMORY_LIMIT: 512M

  volumes:
      - ./docroot:/var/www/html

  nginx:
    image: wodby/drupal-nginx:8-1.10-2.1.0
    depends_on:
      - php
    environment:
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html
    volumes:
      - ./public:/var/www/html

    labels:
      - 'traefik.backend=nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host: cuk.internal, www.cuk.internal'
      - 'traefik.docker.network=cuk_default'

  traefik:
    image: traefik
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '8000:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

**Comment by csandanov** [comment]
We do not provide dev image for 5.3 version, this legacy version no longer supported
