### ISSUE TITLE
AthenaPDF: Connection refused error

### ISSUE THREAD

**Issue by rafatwork** [wodby/docker4drupal#237]
Enabled the AthenaPDF container & followed the documentation at https://wodby.com/stacks/drupal/docs/containers/athenapdf/.

The curl command (within the PHP/ngin containers) returns a "curl: (7) Failed to connect to athenapdf port 80: Connection refused" error.

Any ideas?

**Comment by csandanov** [comment]
TL;DR use port `8080` for local environment

We had [this PR](https://github.com/wodby/drupal-docs/pull/1) a few weeks ago removing the port `8080` from the usage example. So, you have to use `8080` on local environment and `80` in Wodby environment because we expose athenapdf's port by default.
