### ISSUE TITLE
Is there any way to choose the drush version

### ISSUE THREAD

**Issue by albertski** [wodby/docker4drupal#241]
I changed my php image from `image: wodby/drupal-php:5.6-2.4.3` (version I had a while ago) to `image: wodby/drupal-php:5.6` which I think gets the latest version.  Problem is that Drush 9 gets installed but I am running a Drupal 7 site.  Only sites built on Drupal 8.4+ are supported with Drush 9.

Is the only way to change the Drush version with the `Images without Drupal`?

**Comment by michaelpporter** [comment]
New Pull Request created https://github.com/wodby/drupal-php/pull/51

**Comment by csandanov** [comment]
Guys, please don't use images without stability tags. Also, it's recommended to install a Drupal project via composer so that you have right dependencies, i.e. the correct version of drush that actually compatible with your Drupal version.

P.S. PR merged.

**Comment by michaelpporter** [comment]
Thank you, most of our D7 do not have composer set. We can add Drush when we ass Behat.
