### ISSUE TITLE
Drupal Settings File

### ISSUE THREAD

**Issue by skorski** [Wodby/docker4drupal#25]
Not sure where this should go but this took me a long time to figure out.  In the drupal settings file the db connection should be: 
```
$databases = array (
    'default' =>
        array (
            'default' =>
                array (
                    'database' => 'drupal',
                    'username' => 'drupal',
                    'password' => 'drupal',
                    'host' => 'mariadb',
                    'port' => '3306',
                    'driver' => 'mysql',
                    'prefix' => '',
                ),
        ),
);
```

In most cases the host is localhost or 127.0.0.1 but docker changes it a bit...

**Comment by csandanov** [comment]
It's described in a point 6 of the instructions or did we miss something?

**Comment by skorski** [comment]
I think I might have missed it there.  As you point it out I realized it was there but I just didn't see it as clearly.  Thanks for doing such a great job with this!
