### ISSUE TITLE
Solr is not set up

### ISSUE THREAD

**Issue by davidlukac** [wodby/docker4drupal#26]
When uncommenting `solr` service from the `docker-compose` file, Solr starts up, but it's not set up for Drupal - it doesn't have default collection and Drupal settings. I've tried replacing it with `wodby/solr-5-alpine` - `apachesolr` module was able to connect. Would that be more suitable solution as that incorporates Drupal configuration?

**Comment by PavelPrischepa** [comment]
Hi, @davidlukac.

We use the official Solr image, which doesn't include drupal-specific configs. The image `wodby/solr-5-alpine` isn't compatible with the **docker4drupal**. So, you can put Solr config manually.

- D7: https://ftp.drupal.org/files/projects/search_api_solr-7.x-1.10.tar.gz
- D8: https://ftp.drupal.org/files/projects/search_api_solr-8.x-1.0-alpha4.tar.gz

Also, we plan to create the **drupal-solr5** image with built-in configs.

**Comment by csandanov** [comment]
A new solr container has been added. See README file.
