### ISSUE TITLE
Symlink issue

### ISSUE THREAD

**Issue by rroblik** [wodby/docker4drupal#260]
### Codebase
Built-in vanilla Drupal
  
### Host OS 
Linux Debian 8 (in VMWare, Windows 8.1 host)

### Docker info output
```
Containers: 8
 Running: 1
 Paused: 0
 Stopped: 7
Images: 58
Server Version: 17.12.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 183
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local local-persist
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Kernel Version: 3.16.0-5-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.95GiB
Name: vm-localdomain
ID: xxx
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
HTTP Proxy: http://192.168.30.1:808/
HTTPS Proxy: http://192.168.30.1:808/
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support

```

### Docker compose file
```yml
#...
volumes:
  codebase:
    driver_opts:
      type: none
      device: ${PWD}/codebase
      o: bind
```

### Logs output
```
php_1        | rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(11                      78) [sender=3.1.2]
php_1        | make: *** [/usr/local/bin/actions.mk:6: init] Error 23
3d_php exited with code 2
```

As you can see there is a issue while using `rsync` during init phase (image `image: wodby/drupal:$DRUPAL_TAG`). This is a know issue as Windows doesn't know about Unix symlink BUT I already have composer project on my VM (outside of docker) that run without issue.

So my question is : why using symlink here ? Why no fallback ?

Best regards, and thanks for the hard work !

**Comment by csandanov** [comment]
> why using symlink here ?

Not sure I understand you, what symlink?

**Comment by rroblik** [comment]
... Symlink : http://stackabuse.com/symbolic-links-in-unix-linux/

**Comment by csandanov** [comment]
I mean you say we use symlinks, where? Do you refer to symlinks in `vendor/`?

**Comment by rroblik** [comment]
I think yes, maybe it's the default composer behavior ? Maybe we can alter that ?

Regards

**Comment by csandanov** [comment]
I think the problem might be caused by the `driver_opts` you add to the shared volume, why you need those?

**Comment by rroblik** [comment]
Because i’m trying to mount « persistant » local holder into container

**Comment by csandanov** [comment]
Is there a reason you don't follow [the instructions](https://wodby.com/stacks/drupal/docs/local/quick-start/#option-2-mount-my-drupal-codebase) on how to mount your own persistent codebase?

**Comment by rroblik** [comment]
Yes, because i'm using vanilla Drupal and using docker in Debian VMWare on windows 8.1 host 

BR

**Comment by csandanov** [comment]
You can clone [drupal-composer/drupal-project](https://github.com/drupal-composer/drupal-project) on your Debian host, mount it as described in the instructions and run `composer install` from php container. This would be the same as vanilla and you won't need `driver_opts`.

**Comment by rroblik** [comment]
Hi,
@csandanov : don't understand what you mean

Here is a corrected and working volumes rules : 

```yml
volumes:
  database:
    driver: local-persist
    driver_opts:
      mountpoint: /docker-data/3d/database
  codebase:
    driver: local-persist
    driver_opts:
      mountpoint: /docker-data/3d/html
```

The mountpoint is on the Debian VM sytem (not on a VMWare shared folder between host and VM, as those do not support symlink) and thanks to that, during the init rsync (after the `Drupal 8 not found in /var/www/html - copying now...`), no symlink error (as Debian support symlink)
The cons is : on my host (Windows 8.1) I access to the volumes files thanks to a Samba share with the VM; but that is pretty slow :(

The remaining question is : why using rsync to "deploy" Drupal base files during docker Build (here https://github.com/wodby/drupal/blob/67a7a9474a390a9421358f13bb0076f42eaa494c/8/bin/init#L13) ?

Regards

**Comment by csandanov** [comment]
We use rsync to copy vanilla Drupal codebase to `/var/www/html` volume exactly for the case when you want to make it persistent with a bind mount from the host. However, in docker4drupal we use named volume for vanilla case (option 1 from quick start guide) to share files between nginx and php. Named volumes can't be mounted from the host.

So if you want to use vanilla and have it persistent, just follow my advice in the previous post – clone composer-based vanilla project in your Debian VM and mount it as described in option 2 of the quick start guide.

For more details see https://docs.docker.com/storage/volumes/
