### ISSUE TITLE
/mnt/files/ access

### ISSUE THREAD

**Issue by rroblik** [wodby/docker4drupal#263]
### Codebase
Built-in vanilla 

Hello,  
As ask myself why the command `drush config:export` output files to `/mnt/files/config/` ; and moreover why the `/mnt/files` folder is not mounted in docker volume (to be accessed by codebase in php container)

Thanks for your light !

BR

**Comment by csandanov** [comment]
For vanilla Drupal we add a default [`settings.php`](https://github.com/wodby/drupal/blob/4.x/8/settings.php.tpl) that among other things sets sync directory to `/mnt/files/config/sync`, for local development it could be set to something simpler like  `sites/default/sync`, so feel free to change it. It's just we use `/mnt/files` for shared volume with static files between php and nginx when you deploy a stack via Wodby, besides it's recommended to have sync folder outside of the docroot for prod environments.
