### ISSUE TITLE
PHP_BLACKFIRE variable is missing

### ISSUE THREAD

**Issue by Niklan** [wodby/docker4drupal#274]
Previously in docker-compose.yml in php container section wass commented out variable `PHP_BLACKFIRE: 1`. Now it missing, but without it, blackfire won't work. Who don't know about this variable can't run blackfire container propertly.

I think it just missed in 5.x versions.

**Comment by csandanov** [comment]
We've removed it because it's optional, the variable documented at https://wodby.com/stacks/drupal/docs/containers/blackfire/

**Comment by Niklan** [comment]
Okay, thanks.

**Comment by BrizzleRocker** [comment]
`PHP_BLACKFIRE: 1` underneath the XDebug stuff
