### ISSUE TITLE
No access by using the Drupal domain on postman OR curl

### ISSUE THREAD

**Issue by mzachariadis** [wodby/docker4drupal#277]
Hello, 

I have an issue when I try to get a response though postman or curl. I get timeout with a message: 
**curl: (7) Failed to connect to drupal.docker.localhost port 8000: Operation timed out**

On the browser side, everything is fine. 

OS: macOS Siera

Thanks !

**Comment by csandanov** [comment]
Did you add `drupal.docker.localhost` to `/etc/hosts`? What in your logs? Did containers actually started?

**Comment by mzachariadis** [comment]
Yeap it's already added to the hosts file. Which logs would you like me to share? 
Everything looks fine with the containers. I can open http://drupal.docker.localhost:8000 on browser. The only problem is that I don't get any response on Postman or telnet or cURL. 

I can get a response when I request http://localhost:8000 -> 404 not found.  
The problem is when I use the domain http://drupal.docker.localhost:8000. Looks like a DNS issue. 

P.S. I edited the issue title, because the problem is on the domain.

**Comment by mzachariadis** [comment]
I used **dnsmasq** and everything looks fine now. I close this issue. Thanks!
