### ISSUE TITLE
Whats the difference between the 2.x and 5.x branch

### ISSUE THREAD

**Issue by readingdan** [wodby/docker4drupal#279]
Whats the difference between the 2.x and 5.x branch

I also notice the documentation link for 2.4 has disappeared/broken, but it does seem to have docs built into the repo, unlike the 5.x branch.

### Codebase
Built-in vanilla Drupal or mounted codebase
  
### Host OS 
e.g. macOS Sierra

### Docker info output
```
# Run "docker info" on the host machine and paste output here 
```

### Docker compose file
```yml
# Content of your docker-compose.yml file. Make sure you remove all sensible information you might have there.
```

### Logs output
```
# Run "docker-compose logs [service]". Let's say you get 500 error for some reason then it'll be helpful to provide logs for php and http server (nginx/apache) services.
```

**Comment by csandanov** [comment]
Those branches used for 2.x and 5.x tags accordingly, see full changelog at https://github.com/wodby/docker4drupal/releases/
