### ISSUE TITLE
Webgrind volume

### ISSUE THREAD

**Issue by adriadrop** [wodby/docker4drupal#280]
Great repo! Little question about "webgrind" I uncommented it in docker-compose.yml and then when i try to run docker-compose up I get this message below

`Named volume "files:/mnt/files:rw" is used in service "webgrind" but no declaration was found in the volumes section.
`

Wondering what to do, seems like volume is there in config?

`
  webgrind:
    image: wodby/webgrind:$WEBGRIND_TAG
    container_name: "${PROJECT_NAME}_webgrind"
    environment:
      WEBGRIND_PROFILER_DIR: /mnt/files/xdebug/profiler
    labels:
      - 'traefik.backend=webgrind'
      - 'traefik.port=8080'
      - 'traefik.frontend.rule=Host:webgrind.${PROJECT_BASE_URL}'
    volumes:
      - files:/mnt/files
`

**Comment by csandanov** [comment]
You need to uncomment the global files volume definition at the end of docker-compose.yml and also in php service volumes. It's used to share xdebug profiler files between webgrind and php containers.
