### ISSUE TITLE
Setting up docker stops at mailhog_1

### ISSUE THREAD

**Issue by deepcore** [wodby/docker4drupal#285]
On initial setup setup stops at mailhog_1    | [APIv1] KEEPALIVE /api/v1/events and keep trying but keeps displaying line above over and over again.

**Comment by csandanov** [comment]
It sounds like you just run `docker-compose up` without `-d` flag and just follows the containers' logs

**Comment by deepcore** [comment]
Thank you @csandanov 👍

**Comment by Bae-ji-yeol** [comment]
> 플래그 `docker-compose up`없이 실행 `-d`하고 컨테이너의 로그를 따르는 것처럼 들립니다.

how can I use docker-compose up??
