### ISSUE TITLE
Install FFmpeg

### ISSUE THREAD

**Issue by igorsok** [wodby/docker4drupal#288]
### Codebase
Built-in vanilla Drupal or mounted codebase
  
### Host OS 
e.g. macOS Sierra

### Docker info output
```
# Run "docker info" on the host machine and paste output here 
```

### Docker compose file
Make sure you remove all commented services.
```yml
# Content of your docker-compose.yml file. Make sure you remove all sensible information you might have there.
```

### .env file
```
# Content of .env file. Make sure you remove all sensible information you might have there.
```

### Logs output
```
# Run "docker-compose logs [service]". Let's say you get 500 error for some reason then it'll be helpful to provide logs for php and http server (nginx/apache) services.
```

**Comment by csandanov** [comment]
You can install it via composer in your dependencies https://github.com/PHP-FFMpeg/PHP-FFMpeg

P.S. Please use English (even if you're bad at it) and don't post empty issue templates (if the template does not apply to your issue, the remove it).

**Comment by csandanov** [comment]
The ffmped library is available [alpine edge repo](https://pkgs.alpinelinux.org/package/edge/community/x86_64/ffmpeg). You should build your own image based on ours, add `edge` repo and install the package
