### ISSUE TITLE
Custom Drupal 8 codebase location

### ISSUE THREAD

**Issue by deepcore** [wodby/docker4drupal#289]
Hi all,

I am using docker4drupal with a composer to set up a local dev environment.
As I want to separate docker file structure from drupal 8 code base (coming from my git repo).
My strucure looks like this:
|
- docker4drupal
- drupal

I'm updating volumes to:
    volumes:
      - ../drupal:/var/www/html

But all the time getting "Permission denied" in Browser.

What's the best way of doing that?

Thank you.

**Comment by deepcore** [comment]
Whoowee!!! Finally, fixed that!
Might be useful for someone, it should be like that:

version: "2"

services:
  php:
    image: wodby/drupal:$DRUPAL_TAG
    environment:
      PHP_FPM_CLEAR_ENV: "no"
    volumes:
      - ../myprojectDir:/var/www/html

  nginx:
    volumes:
      - ../myprojectDir:/var/www/html

volumes:
  codebase:

**Comment by lmeurs** [comment]
Awesome, worked for me! To be complete, alterations were made to the `docker-compose.override.yml` file.
