### ISSUE TITLE
Can someone please tell me how I can have Varnish cache on drupal.docker.localhost

### ISSUE THREAD

**Issue by MarioBaron** [wodby/docker4drupal#290]
I know I can have varnish cache at varnish.docker.localhost but how can I have it set up so varnish cache serves my primary domain at drupal.docker.localhost
I know the old fashioned way with ports but I am using multisite setup with traefik which is completely new to me. I can make it work by removing "varnish." from 'traefik.frontend.rule=Host:varnish.${PROJECT_BASE_URL}' but somehow that doesn't seem right since Nginx is also using - 'traefik.frontend.rule=Host:${PROJECT_BASE_URL}' 

Sorry, its a real noob question but I am hoping someone here can answer this for me.

**I did search Google far and wide before troubling anyone here :)** thanks in advance

**Comment by csandanov** [comment]
> but somehow that doesn't seem right since Nginx is also using - 'traefik.frontend.rule=Host:${PROJECT_BASE_URL}'

well, you can change hostname for nginx as well

also see https://wodby.com/stacks/drupal/docs/local/multiple-projects/

**Comment by MarioBaron** [comment]
thank you for your reply :) Wouldn't that make the site accessible at nginx.docker.localhost as well. I would want the site be accessible only through drupal.docker.localhost with varnish cache enabled.

**Comment by csandanov** [comment]
Why not remove traefik rules for nginx completely then?

**Comment by MarioBaron** [comment]
Funny outcome...I tried commenting out nginx `traefik.frontend.rule=Host:${PROJECT_BASE_URL}'`
and it worked. However, there is about 20% + speed gain when nginx traefik rule is active even though it is effectively pointing to the same hostname as Varnish...
No idea why this would happen, I'd sooner expect the opposite but I am super new to Traefik...
Either way I am liking this :) Will close the issue now. But if I figure out why the speed boost with both Traefik rules pointing to exact same hostname I'll let you know.

> Awesome work on this stack, I did try a few other Drupal stacks but docker4drupal is by far most complete and best performing. Only suggestion is to have Varnish set up to serve pages on drupal.docker.localhost by default (even if it remained disabled in default configuration as it is now)... Drupalers love Varnish :)
