### ISSUE TITLE
Composer install for private repo's from php container (SSH)

### ISSUE THREAD

**Issue by gertvdb** [wodby/docker4drupal#291]
Hi,

We have some private repo's which we get into our project via a composer.json file which references the repo in "repositories". Since it's a private repo we need to have ssh to access the repo.

We do this now by mounting the ssh-key of the user to the container via volumes and starting the ssh-client in the php container (`eval $(ssh-agent) + ssh-add`),but this has to be done manually every time the container starts up.

I was wondering if there’s a way to start up the ssh agent when bringing up the container or a better way to access private repo's from the php container via composer.

Thanks

**Comment by csandanov** [comment]
See [how we run sshd in our tests](https://github.com/wodby/php/blob/master/7/test/docker-compose.yml#L9)

**Comment by csandanov** [comment]
Sorry, the wrong line, you can add a private SSH key via env var [like this](https://github.com/wodby/php/blob/master/7/test/docker-compose.yml#L23)
