### ISSUE TITLE
A few questions that might be worth being added to a FAQ

### ISSUE THREAD

**Issue by chrarnold** [wodby/docker4drupal#300]
I have some questions, some of which might be useful for a FAQ or something. I am sorry if I oversaw something! I am thankful for your answer and help, I think this is a great project...

**Describe your issue**
(1) Can I set NGINX_SERVER_ROOT to any arbitrary path other than /var/www/html/web? I tried something like /datadisk/NGINX_ROOT to reflect my local directory structure, but this did not work. Maybe I made another mistake, so I am troubleshooting step by step. If yes, is there any other change I have to make? Let's say I want /datadisk/NGINX_ROOT to be my root directory of the webserver, and then within this folder multiple subfolders reflecting different Drupal projects, say project1 and project2, which should then be accessible via  http://drupal.docker.localhost/project1:8000 and http://drupal.docker.localhost/project2:8000, respectively. Should they both be within "web", or is "web" irrelevant now because I changed the NGINX_SERVER_ROOT default anyway?

(2) I did not find instructions clear enough how to integrate an own existing Drupal project. Is it generally  really as easy as (a) Putting the existing one in the right directory, as specified by NGINX_SERVER_ROOT, (b) adjusting username and PW etc, and (c) creating a mariadb-init folder + uncommenting the line in the docker-compose.yml file so all sql files inside that folder are used to init the DB?

(3) My Drupal project uses Drush 9, is there anything else I have to do in that regard? From my understanding, I would continue using Drush for managing my Drupal directory independent of Docker using my local Drush 9 installation, and only for providing the infrastructure (DB, server, ...) I use the docker framework. I did not see Drush 9 in the docker4drupal list, so I am wondering.

**Comment by chrarnold** [comment]
Thanks for the reply... I got quite some troubles but got it to work now.
1. In the end, it worked for me with setting NGINX_SERVER_ROOT: /var/www/html/demo2. In my (custom) webserver root directory, I put all the docker4drupal files, then in the subdirectory demo2 is my existing Drupal project. I felt this was not so clearly described what the expected folder structure is supposed to be, so maybe this is helpful for others. 

2. The site at least loads, but I am experiencing the following problems and I am wondering what it could be: First I want to say that the site is just a demo site downloaded anew and works totally fine locally with lampp (Apache), so the directory per se is ok and it contains a functional Drupal site. However, when using docker4Drupal, I have the following issue:
a) Before logging in, the design / CSS is not loaded or something. As soon as I login, the site looks as expected. In addition, some (only some) menus in the administration menu show the same issue with the design: "Content" works, "Administration" not, etc. I did not find any logs in the php container that could show what the problem is. Any ideas? The directory has 777 permissions, and the /tmp directory within Drupal is set to /tmp, which is writable. Drupal does not mention any warnings except security issues.

3. Ultimately, we are a team and want to work together on the site, and we hope that docker4drupal can help us to minimize technical problems due to differences in libraries, program versions etc. Do you have example code or any guidance how to best update repositories (such as composer install, drush config import etc) using docker4drupal? From my understanding, one needs to run this within the container, correct? Any help is really appreciated!

Thanks!

**Comment by csandanov** [comment]
>  Before logging in, the design / CSS is not loaded or something. As soon as I login, the site looks as expected.

Could you look up your console and network tabs in your browser console to see any errors or pending requests to static files.

> Do you have example code or any guidance how to best update repositories (such as composer install, drush config import etc) using docker4drupal?

You manage your codebase as usual, just mount it to a container as described in a quick start guide. We recommend managing all dependencies with composer, see https://github.com/drupal-composer/drupal-project

**Comment by chrarnold** [comment]
The following error causes this:
Refused to apply style from 'http://drupal.docker.localhost:8000/?0' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

I don't understand the following:
1) Some pages work fine, some don't, as I described. It cannot be a permission issue.
2) With lampp and Apache, the full site loads fine. No error messages whatsoever.
3) The "?0" looks weird also. Could it be something in the php.ini that works for Apache but not NGINX?

Thanks for the quick help, I really appreciate it!

**Comment by csandanov** [comment]
* Does this happen with Vanilla Drupal + standard themes or with your custom theme?
* Did you try https://github.com/froala/angular-froala/issues/170#issuecomment-386117678?
* Provide your compose file, `.env` so I can see images tags
