### ISSUE TITLE
Xdebug with Docker Edge mac66 in Macosx

### ISSUE THREAD

**Issue by perarg** [wodby/docker4drupal#302]
Can anyone confirm that can use xdebug with Docker Edge mac66 in Macosx with PhpStorm ?
I have done everything in https://wodby.com/stacks/drupal/docs/local/xdebug/ but there is no "connection" between website-phpstorm. Before giving up, i want to know if anyone has successful debugging with the above configuration ?

**UPDATE**: I think it is working using `PHP_XDEBUG_REMOTE_HOST: 10.254.254.254` for _macOS, Docker < 18.03_ and not the `PHP_XDEBUG_REMOTE_HOST: host.docker.internal` which is for _Docker 18.03+ & Linux/Mac/Win_. I am making some trials and i update the issue.

**Comment by barat** [comment]
For me it works with this config:
```zend_extension=xdebug.so
xdebug.remote_enable=1
xdebug.remote_autostart=0
xdebug.remote_connect_back=0
xdebug.profiler_enable=0
xdebug.remote_port=9000
xdebug.idekey = "IDEKEYHERE"
xdebug.remote_handler=dbgp
xdebug.remote_host = 10.254.254.254
xdebug.max_nesting_level = 500```

I just start a loopback by `sudo ifconfig lo0 alias 10.254.254.254` before container starts. Wasn't trying with host.docker.internal yet.

**Comment by csandanov** [comment]
`host.docker.internal` supported since 18.03+
