### ISSUE TITLE
5.1.0 release: Image tags are not updated in the .env file

### ISSUE THREAD

**Issue by duozersk** [wodby/docker4drupal#304]
For instance, https://hub.docker.com/r/wodby/drupal-nginx/tags/ lists 4.2.0 versions, but the .env file from 5.1.0 release still uses 4.1.0 and no 1.15 versions.

**Comment by csandanov** [comment]
Wow, thank you! Last minute merge before release overrode almost all changes to tags. Re-published 5.1.0 with updated archive https://github.com/wodby/docker4drupal/releases/tag/5.1.0
