### ISSUE TITLE
Consider methods to build local container to match UID/GID

### ISSUE THREAD

**Issue by jonpugh** [wodby/docker4drupal#31]
I was unable to get anything but a `File not found` when launching your docker-compose.yml.

I was able to make it easy for developers to rebuild a local container so that the web server user matches the UID of their acting local user.

This makes volumes much easier to deal with, and allows users to edit files locally without any permissions issues, or files showing up as owned by root.

Check out our dockerfile for Aegir "local": https://github.com/aegir-project/dockerfiles/blob/master/Dockerfile-local  and our prepare.sh script that creates the custom local container: https://github.com/aegir-project/development/blob/master/prepare.sh#L82

```
docker build --build-arg AEGIR_UID=$USER_UID -t aegir/hostmaster:local -f dockerfiles/Dockerfile-local dockerfiles
```

With the ARG definition, you are able to accept arguments at `docker build` time.

I wrote [prepare.sh](https://github.com/aegir-project/development/blob/master/prepare.sh) script for our aegir development environment that prepares source code, but most importantly, detects the users UID and runs the right `docker build` command to create a container just for that user.

**Comment by PavelPrischepa** [comment]
It's really interesting, thank you. Probably, It's may be difficult for beginners because you need to rebuild at least 2 images PHP, Nginx, and keep these up to date.

**Comment by brilsergei** [comment]
I just started to use docker for dev and got a problem with permissions when generate boilerplate code with drupal-console. I've changed Dockerfile for drupal-php image to make it create user with predefined UID and GID (which should be the same as on the host system). Also new Dockerfile installs drupal-console to the new user's home directory, makes the user to be /var/www/html owner and adds the user to www-data group. So, nginx has access to drupal files and drupal-console can write into site folder and create files with appropriate permissions and owned by user with UID same as on host system. I tested it with docker4drupal, it works fine.
It's enough for me but it would be good 

1. to set HOST_UID and HOST_GID in docker-compose.yml. (Docker compose [allows to do it](https://docs.docker.com/compose/compose-file/#args), but I haven't tested it yet)

2. to provide a way optionally skip creating of the host-user and make it work exactly the same way is original Dockerfile works now. (Have no idea how to do it without a script like @jonpugh suggested)

Main question is: Is it correct solution? I've never worked with docker before and Idk am I on right way or not.

**Comment by macmladen** [comment]
I think this is the same problem as referenced in #64.

It is interesting to note that on Mac this problem does not exist: everything that is done under docker (like running `drush` in docker) is working as `$USER` UID and GID so there is **absolutely** no problem with permissions.

@PavelPrischepa I would suggest somewhat wild solution, to **change UID/GID** for the `www-data` which is initially `82:82` to environment provided `HOST_UID/HOST_GID`.

Entry script could use **environment** variable and change `www-data` UID/GID

```
sudo groupmod -g $HOST_GID www-data
sudo usermod -u $HOST_UID www-data
```

That way we would ensure that container should not be rebuild, that it could be updated and still operate with our UID/GID.

**Comment by PavelPrischepa** [comment]
@macmladen I think it's bad idea to change `www-data` in entrypoint or command. Because they can be changed in docker args or compose file and the result will be unpredictable. 

I like the solution in #33, because it's simple and clear. But maybe we need to find a way how to make it more elegantly.

**Comment by csandanov** [comment]
We now recommend to add yourself to a group with ID 82 on the host machine http://docs.docker4drupal.org/en/latest/permissions/

**Comment by csandanov** [comment]
I'm closing this issue. It seems having GID 82 on the host machine solves the main problem for php and nginx containers.
