### ISSUE TITLE
Allow multiple projects to communicate?

### ISSUE THREAD

**Issue by elkrammer** [wodby/docker4drupal#311]
Hi,

I'm using the multiple projects solution described [here](https://wodby.com/stacks/drupal/docs/local/multiple-projects/) and everything is working fine for accessing the sites.
However I'm having trouble allowing communication between site1 and site2.
From site1 I have a module that pulls a json file from site2 but it's failing because it cannot communicate to site1.

To debug the issue I ssh'ed into site1's php container and ran:
```
wodby@php.container:/var/www/html $ curl http://site2.docker.localhost/
curl: (6) Could not resolve host: site2.docker.localhost
```
What's the best way to resolve this?

Thanks!

**Comment by PavelPrischepa** [comment]
You may access site2 via docker interface (works on Linux):
```bash
curl -H 'Host: site2.docker.localhost' http://172.17.0.1
```

**Comment by walkero-gr** [comment]
@PavelPrischepa This way you point the Docker IP of the second stack? What about if this is dynamic? Isn't there a way traefik to help on that, and send the calls to the right stack, based on the domain?

**Comment by devbranch-nikita** [comment]
```
version: "3"

services:
  php:
    extra_hosts:
      - "mysecondproject.docker.localhost:10.100.1.61"
```

10.100.1.61 here is the IP of your computer.

![2019-11-06-131917](https://user-images.githubusercontent.com/37998087/68294244-5cca1d00-0098-11ea-88b4-faeffb7f3e45.png)
