### ISSUE TITLE
Running docker4drupal on a production server

### ISSUE THREAD

**Issue by chrarnold** [wodby/docker4drupal#314]
Hi,
We are not so experienced with Docker yet, and we wanted to know your opinions on the following:
Are there any security or other practical concerns or settings to be aware of when using docker4drupal in a production environment? We have our own little server and we want to eventually make our Drupal website available to the public via docker4drupal. At least for development we started using it, and we wonder whether we can also just use it for production or whether this is not the best idea. 
The Docker Docs, for example, list the following issues for Compose in production:

1. Removing any volume bindings for application code, so that code stays inside the container and can’t be changed from outside
2.  Binding to different ports on the host
3. Setting environment variables differently, such as when you need to decrease the verbosity of logging, or to enable email sending)
4. Specifying a restart policy like restart: always to avoid downtime
5. Adding extra services such as a log aggregator

Any suggestions and opinions to the points I've posted are very much appreciated, thanks!

**Comment by csandanov** [comment]
Well, you're right, there's a bunch of things you should take care of when running containers in production, and additionally – yes, you have to configure images as well, such as setting up lower error reporting level for PHP and other things. If deploying a [Drupal stack via Wodby](https://cloud.wodby.com/stackhub/ada51e9b-2204-45ee-8e49-a4151912a168/overview) does not work for you (**disclosure**: I'm one of the co-founders and very much biased), I recommend to take a look at Kubernetes or Swarmkit that'll help you understand all the things you should consider when running containers in production, as for images configuration you can take a look at the official configs, for example PHP has the default [development](https://github.com/php/php-src/blob/master/php.ini-development) and [production](https://github.com/php/php-src/blob/master/php.ini-production) versions of `php.ini`.

**Comment by csandanov** [comment]
Also see https://drupal.stackexchange.com/a/231630
