### ISSUE TITLE
ERROR: manifest for wodby/postgres:10.1-1.3.1 not found

### ISSUE THREAD

**Issue by Mykola-Veriga** [wodby/docker4drupal#323]
I use docker4drupal - 5.1.2 with PostgreSQL
I have error 

```
$ docker-compose up -d 
Pulling postgres (wodby/postgres:10.1-1.3.1)...
ERROR: manifest for wodby/postgres:10.1-1.3.1 not found
```

I replaced in .env the 
POSTGRES_TAG=10.1-1.3.1 
on 
POSTGRES_TAG=10-1.3.1

**Comment by csandanov** [comment]
Yes, it should be `10-1.3.1`, already fixed

duplication of #318
