### ISSUE TITLE
UID 1000/82 write permissions

### ISSUE THREAD

**Issue by juvinious** [wodby/docker4drupal#326]
***Codebase***
Mounted codebase (Drupal 7)

**Describe the bug**
Recently upgraded the docker-compose from an older version that was over 3 years old. Lots of cool changes. :)
Noticed that the default user now has a UID of 1000, which is great, so I modified my sites/default/files back to my UID 1000 from UID 82 (chown -R 1000:1000). 
It had no problem reading files from the directory, however it prevented drupal from writing to the directory. So I also did chmod -R 775 just in case I was missing something but to no avail.
I ended up changing group ownership back to 82 and it works.

**Output of `docker info`**
Containers: 8
 Running: 8
 Paused: 0
 Stopped: 0
Images: 14
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.18.0-7-generic
Operating System: Ubuntu Cosmic Cuttlefish (development branch)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.31GiB
Name: G177-BJD7HQ2
ID: OQIV:TE4Z:GYSA:CCZC:HPES:AU43:WDIW:7XN7:PHZH:YAQA:PWJV:J4LH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

**Contents of your `docker-compose.yml`**
```
# Default commented out Drupal 8 tag
```

**Contents of your `.env`**
```
# Default commented out Drupal 8 tag
```

**Logs output `docker-compose logs`**
```
# N/A
```

**Question**
I'm wondering if there is a workaround or is this just inherent to a mounted codebase? 
Many thanks!

**Comment by csandanov** [comment]
Not sure what's the question, if you want fpm to write to files directory, the fpm user (www-data 82) must have writing permissions, more details on permissions described at https://github.com/wodby/php#users-and-permissions

**Comment by juvinious** [comment]
I see I misunderstood the uid change. 
It makes perfect sense now thanks for clearing it up.
Closing this.
