### ISSUE TITLE
Nginx and Drupal send the same headers

### ISSUE THREAD

**Issue by AllaKurochka** [wodby/docker4drupal#336]
I found that Drupal 8 and Nginx send the same headers:
X-Frame-Options SAMEORIGIN;
X-Content-Type-Options nosniff;

So as a result they are doubled.

**Contents of `.env`**
```
...
PHP_TAG=7.2-dev-4.6.4
NGINX_TAG=1.15
...
```

**Comment by csandanov** [comment]
Thank you for reporting this issue, headers duplication will be removed with the upcoming nginx update.

**Comment by csandanov** [comment]
Fixed in [5.3.3](https://github.com/wodby/docker4drupal/releases/tag/5.3.3)
