### ISSUE TITLE
mac permission for sync 

### ISSUE THREAD

**Issue by nathan-zhu** [wodby/docker4drupal#337]
***Codebase***
Built-in vanilla Drupal or mounted codebase

Configuration directory: sync
An automated attempt to create the directory **../config/sync failed**, possibly due to a permissions problem. To proceed with the installation, either create the directory and modify its permissions manually or ensure that the installer has the permissions to create it automatically. For more information, see INSTALL.txt or the online handbook.

I'm start to use docker with drupal , please help how to fix it . thanks.

**Describe your issue**
A clear and concise description of your issue.

**Output of `docker info`**
```
Paste here
```

**Contents of your `docker-compose.yml`**
```
Paste here
```

**Contents of your `.env`**
```
Paste here
```

**Logs output `docker-compose logs`**
```
Paste here
```

**Comment by csandanov** [comment]
If you want to get help please follow the template and provide information we ask, then, someone might help.
