### ISSUE TITLE
Crontab for Drupal

### ISSUE THREAD

**Issue by Vacilando** [wodby/docker4drupal#344]
***Codebase***
Drupal 7 or Drupal 8

**Describe your issue**
1. How to add a crontab task to the PHP container so that it persists.
2. Is there a generic way to set a crontab task for any Drupal 7 or Drupal 8 local environment? Something in the way Wodby does it: * * * * * drush -r "${HTTP_ROOT}" -l "${WODBY_HOST_PRIMARY}" cron

**Comment by csandanov** [comment]
Here's an example from wodby/php tests https://github.com/wodby/php/blob/master/7/tests/docker-compose.yml#L35

**Comment by Vacilando** [comment]
The crond container starts but the question is what to put into the crontab file so that it works on any Drupal site.

I tried the following:
- /usr/local/bin/drush cron --root=/var/www/html/
- /home/wodby/.composer/vendor/drush/drush/drush cron --root=/var/www/html/
- cd /var/www/html/ && /usr/local/bin/drush cron
- cd /var/www/html/ && /home/wodby/.composer/vendor/drush/drush/drush cron

But I am invariably seeing the following messages in the container's log:

Same when I indicated folder "/var/www/html/web" (it's a D8 site).

> Command core-cron needs a higher bootstrap level to run - you will need to invoke drush from a more functional Drupal environment to run this command.

**Comment by csandanov** [comment]
have you tried the same as on Wodby (from stack > settings page):
```
29 * * * * drush -r "${HTTP_ROOT}" -l "${WODBY_URL_PRIMARY}" cron
```
where http root is usually something like `/var/www/html/web` and URL is your base url, crond run from `www-data` user on purpose.

**Comment by Vacilando** [comment]
I did; experience:
- option "-l" is useless since the container does not know local subdomain "mysite.docker.localhost"
- using just "drush -r "/var/www/html/web" cron" results errors in the cron container log such as "The drush command 'cron' could not be executed. [error] The drush command 'cron
' could not be found."

Like I said in my second post (27 November) above, command such as "/usr/local/bin/drush cron --root=/var/www/html/" successfully starts the cron process and the http root is also OK, but the Linux user seemingly isn't.

**Comment by csandanov** [comment]
> but the Linux user seemingly isn't.

The logic behind users described in https://github.com/wodby/php#users-and-permissions. In Wodby environment we decided to set `www-data` user to replicate the behavior when you would trigger cron manually from Drupal admin UI. Besides, it may cause some file permissions issues, e.g. FPM has created a directory in public files that won't be writable for `wodby` user by default.

**Comment by csandanov** [comment]
> Unfortunately, the crontab file becomes empty after container creation.

Well, there's something on your side then, because we run cron in tests that I referred and they seem to be passed just fine. Please submit a new issue with more details how to reproduce.

**Comment by timdiels1** [comment]
@csandanov Could you share what to put in docker compose? As in my opinion this is something every Drupal website needs to have also running locally... And with the info here I can not get it to work.

**Comment by csandanov** [comment]
I provided all the information in the comments above

**Comment by timdiels1** [comment]
@csandanov I don't get it, you point to pieces that we need to put together. Some of us don't have the same knowledge and thus it is sometimes not as easy as it looks.

Could you share a snippet that is to be copy pasted in the docker-compose.yml that allows us to run the crontab with a specified file? I'm sure more ppl are looking for this.

**Comment by timdiels1** [comment]
Ok some documentation for others trying to set up.
1. Add the id_rsa, crontab and authorized_keys files from https://github.com/wodby/php/tree/master/7/tests

2. Add the following snippets in docker-compose.yml
```
sshd:
  image: wodby/drupal-php:$PHP_TAG
  container_name: "${PROJECT_NAME}_sshd"
  command: sudo /usr/sbin/sshd -De
  volumes:
    - ./authorized_keys:/home/wodby/.ssh/authorized_keys
  environment:
   DEBUG: 1

...

php:
  ...
  depends_on:
    - sshd
  ...
  volumes:
    ...
    - ./id_rsa:/home/wodby/.ssh/id_rsa

...

crond:
  image: wodby/drupal-php:$PHP_TAG
  container_name: "${PROJECT_NAME}_crond"
  command: sudo -E LD_PRELOAD=/usr/lib/preloadable_libiconv.so crond -f -d 0
  volumes:
    - ./crontab:/etc/crontabs/www-data
  depends_on:
    - sshd
```

**Comment by timdiels1** [comment]
Tried `29 * * * * drush -r "/var/www/html/web" -l "http://test.docker.localhost:8000" cron`

But also getting same issue as described by @Vacilando 
```
Command core-cron needs a higher bootstrap level to run - you will       [error]
need to invoke drush from a more functional Drupal environment to run
this command.
The drush command 'cron' could not be executed.                          [error]
```

@csandanov Could you please advise what we can do to get this working?

**Comment by csandanov** [comment]
Added `crond` service, enabled by default and runs every hour. Command:

```
drush -r /var/www/html/web cron
```

Works for vanilla (Drupal 8) after installation:

```
crond: wakeup dt=10
crond: wakeup dt=50
crond: file www-data:
crond:  line drush -r /var/www/html/web cron
crond:  job: 0 drush -r /var/www/html/web cron
crond: child running /bin/ash
crond: USER www-data pid 128 cmd drush -r /var/www/html/web cron
 [notice] Starting execution of comment_cron().
 [notice] Starting execution of dblog_cron(), execution of comment_cron() took 3.39ms.
 [notice] Starting execution of field_cron(), execution of dblog_cron() took 0.66ms.
 [notice] Starting execution of file_cron(), execution of field_cron() took 1.05ms.
 [notice] Starting execution of history_cron(), execution of file_cron() took 12.18ms.
 [notice] Starting execution of node_cron(), execution of history_cron() took 0.5ms.
 [notice] Starting execution of search_cron(), execution of node_cron() took 5.84ms.
 [notice] Starting execution of system_cron(), execution of search_cron() took 6.02ms.
 [notice] Starting execution of update_cron(), execution of system_cron() took 8.79ms.
 [notice] Execution of update_cron() took 17.63ms.
 [notice] Cron run completed.
```

**Comment by csandanov** [comment]
I'm locking this issue because it's old and the discussion here is not really relevant to the topic. If you have issues with the new crond service please post new issue.
