### ISSUE TITLE
Adding FTP to update modules

### ISSUE THREAD

**Issue by suricactus** [Wodby/docker4drupal#35]
Hello. Great work with this configuration! Do you have any plans to add ftp server to update modules easily?

**Comment by PavelPrischepa** [comment]
@suricactus what did you mean?

**Comment by suricactus** [comment]
When there are updates of modules or themes, I'm redirected to page asking for FTP credentials. I know I can achieve the same thing with `drush pm-update`, but it would be nice to do it with UI too.
![image](https://cloud.githubusercontent.com/assets/2820439/18339034/ae64d38e-75a5-11e6-85d6-8d086f7d5559.png)

**Comment by ruifigueiredo** [comment]
Hello, I think the problem is with users permissions.. the drupal-php images need to have users like root to work with volumes..

**Comment by ruifigueiredo** [comment]
@suricactus You can use docker-compose exec php sh and $chmod 777 modules, then exit the container with CTRL+p+q and use docker-compose exec --user 82 php drush dl module.

**Comment by PavelPrischepa** [comment]
@suricactus Also, you should read the p3 of https://github.com/Wodby/docker4drupal#instructions
```
...
$ sudo chgrp -R 82 sites/default/files
$ sudo chmod -R 775 sites/default/files
...
```

It should helps.

**Comment by willcode4food** [comment]
Is there a solution for Windows?

**Comment by PavelPrischepa** [comment]
@willcode4food no, it's for Linux. You should use an appropriate Windows commands.

**Comment by willcode4food** [comment]
I was able to resolve this on Windows.  You have to unset readonly permissions and make sure they are propagated to all the subdirectories and files.  

1. Right-click on the root directory of the drupal installation and select **Properties**
2. Uncheck **Read-only** and click **Apply**
3. You should be prompted to **Confirm Attribute Changes** and make sure **Apply Changes to this folder, subfolders and files** is selected. Click **Ok**

Should be good to go after that.  Hope this helps other windows users.

**Comment by PavelPrischepa** [comment]
Thank you @willcode4food I'll add it to readme.
