### ISSUE TITLE
Running drush commands

### ISSUE THREAD

**Issue by nxut** [wodby/docker4drupal#356]
***Codebase***
New mounted codebase

**Describe your issue**
I would like to know how to execute drush commands after running docker-compose up -d.
I want to run drush si for site installation.
I tried docker-compose exec php bash to access /var/www/html/, lunched drush si but can't reach mariadb instance.
Any suggestions please?
Thank you.

**Comment by nxut** [comment]
My bad, was specifying bad port.

**Comment by Enzo-JURET** [comment]
Salut @nxut , je suis nouveau dans le monde des déploiement docker et j'aimerai savoir comment tu à fais pour exécuter tes commandes drush depuis le projet docker4drupal ?

**Comment by mrspiderbrain** [comment]
In my experience, drush needed to be added as an additional composer dependency
`composer require drush/drush`
