### ISSUE TITLE
ERROR: manifest for wodby/elasticsearch:6.2-3.0.4 not found

### ISSUE THREAD

**Issue by walkero-gr** [wodby/docker4drupal#362]
**Describe the bug**
Elasticsearch tag 6.2-3.0.4 doesn't exist. When I do a 
```
docker-compose up -d
```
I get the error 
```
ERROR: manifest for wodby/elasticsearch:6.2-3.0.4 not found
```
It should change to 6.3-3.0.4

**Contents of your `.env`**
```
ELASTICSEARCH_TAG=6.2-3.0.4
# ELASTICSEARCH_TAG=6.1-3.0.4
# ELASTICSEARCH_TAG=6.0-3.0.4
# ELASTICSEARCH_TAG=5.6-3.0.4
# ELASTICSEARCH_TAG=5.5-3.0.4
# ELASTICSEARCH_TAG=5.4-3.0.4

### --- KIBANA ---

KIBANA_TAG=6.2-3.0.4
# KIBANA_TAG=6.1-3.0.4
# KIBANA_TAG=6.0-3.0.4
# KIBANA_TAG=5.6-3.0.4
# KIBANA_TAG=5.5-3.0.4
# KIBANA_TAG=5.4-3.0.4
```

**Comment by PavelPrischepa** [comment]
Hi, I see `wodby/elasticsearch:6.2-3.0.4` [failed to build](https://travis-ci.org/wodby/elasticsearch/jobs/497221228) so you may use `wodby/elasticsearch:6.2-3.0.3` until it will be fixed.

**Comment by PavelPrischepa** [comment]
I've restarted the job and `wodby/elasticsearch:6.2-3.0.4` has built successfully - it seems there was a temproraly issue.

**Comment by csandanov** [comment]
Fixed, now only major tags supported, e.g. `wodby/elasticsearch:6-4.1.0`
