### ISSUE TITLE
Use Self-Documenting Makefiles

### ISSUE THREAD

**Issue by irmantasp** [wodby/docker4drupal#368]
**Is your feature request related to a problem? Please describe.**
Make files if are very customized slowly become hard to read and find which defined commands you need to use.

**Describe the solution you'd like**
If self-documenting makefiles would be implemented, as provided in example here: https://swcarpentry.github.io/make-novice/08-self-doc/index.html it would provide a way to easily document and maintain project development makefiles. 

**Describe alternatives you've considered**
Writing bash scripts results in very messy documentation again and implementing cli like `ahoy` adds another dependency for the environment.

**Additional context**
Example `docker.mk`:
```make
include .env

.PHONY: up down stop prune ps shell drush logs

default: up

DRUPAL_ROOT ?= /var/www/html/web

## help	:	Print commands help.
help : docker.mk
	@sed -n 's/^##//p' $<

## up	:	Start up containers.
up:
	@echo "Starting up containers for $(PROJECT_NAME)..."
	docker-compose pull
	docker-compose up -d --remove-orphans

## down	:	Stop containers.
down: stop

## stop	:	Stop containers.
stop:
	@echo "Stopping containers for $(PROJECT_NAME)..."
	@docker-compose stop

## prune	:	Remove containers and their volumes.
prune:
	@echo "Removing containers for $(PROJECT_NAME)..."
	@docker-compose down -v

## ps	:	List running containers.
ps:
	@docker ps --filter name='$(PROJECT_NAME)*'

## shell	:	Remote in to runninng `php` container.
shell:
	docker exec -ti -e COLUMNS=$(shell tput cols) -e LINES=$(shell tput lines) $(shell docker ps --filter name='$(PROJECT_NAME)_php' --format "{{ .ID }}") sh

## drush	:	Execute `drush` command without additional arguments.
drush:
	docker exec $(shell docker ps --filter name='^/$(PROJECT_NAME)_php' --format "{{ .ID }}") drush -r $(DRUPAL_ROOT) $(filter-out $@,$(MAKECMDGOALS))

## logs	:	View containers logs.
logs:
	@docker-compose logs -f $(filter-out $@,$(MAKECMDGOALS))

# https://stackoverflow.com/a/6273809/1826109
%:
	@:
```
Example output when executing `make help`:
![Screenshot from 2019-03-26 21-25-31](https://user-images.githubusercontent.com/11249028/55027348-bef47700-500d-11e9-9494-e78fd4a03ee0.png)

**Comment by csandanov** [comment]
Looks good, PR is welcome!

**Comment by irmantasp** [comment]
Will make one asap! Thanks!

**Comment by csandanov** [comment]
Merged
