### ISSUE TITLE
Add `start` command to docker.mk

### ISSUE THREAD

**Issue by irmantasp** [wodby/docker4drupal#370]
**Is your feature request related to a problem? Please describe.**
It is not always needed to update to never versions of containers, you are working without internet connection. Option to start from where you left off would be nice feature to have.

**Describe the solution you'd like**
Implement Makefile command like this:
```make
## start	:	Start containers without updating.
start:
	@echo "Starting containers for $(PROJECT_NAME) from where you left off..."
	@docker-compose start
```

**Describe alternatives you've considered**
At the moment, none, as I already add it to all of my setups. 

**Additional context**

**Comment by csandanov** [comment]
Merged
