### ISSUE TITLE
make prune <SERVICE> doesn't work (anymore?)

### ISSUE THREAD

**Issue by obriat** [wodby/docker4drupal#378]
The command `make prune <SERVICE>`  doesn't work. 
It seems that `docker-compose down` doesn't take SERVICE as parameter like `up`.

Hence you can update the up target
 ```
## up	:	Start up containers.
up:
	@echo "Starting up containers $(filter-out $@,$(MAKECMDGOALS)) for $(PROJECT_NAME)..."
  ##		You can optionally pass an argument with the service name to start single container
  ##		up mariadb	: Start `mariadb` container.
  ##		up mariadb solr	: Start `mariadb` and `solr`.
	docker-compose pull
	docker-compose up -d --remove-orphans $(filter-out $@,$(MAKECMDGOALS))
```

**Comment by csandanov** [comment]
I don't think we ever had it, is there a reason you need down instead of prune? if yes, then feel free to submit a PR similar to what we had for prune – see https://github.com/wodby/docker4drupal/pull/372

**Comment by obriat** [comment]
Sorry it was `make prune` : https://github.com/wodby/docker4drupal/blob/master/docker.mk#L38, I update the issue description.
