### ISSUE TITLE
Creating solr core is not straight forward.

### ISSUE THREAD

**Issue by kevinquillen** [wodby/docker4drupal#379]
Probably one for the docs, but for those looking, here is how to create a solr core for Drupal (8, in my case):

`docker exec -ti SOLR_CONTAINER_NAME make core=CORENAME -f /usr/local/bin/actions.mk`

I checked the docker4drupal docs and I could not find anywhere where it detailed how to do this.

**Comment by csandanov** [comment]
I know it may be hard to find but we have it documented at https://wodby.com/docs/stacks/solr/#local-environment
