### ISSUE TITLE
Drush Alias is not appearing

### ISSUE THREAD

**Issue by lhridley** [Wodby/docker4drupal#38]
The latest update to the drupal PHP 5.6 and 7.0 images removed the drush alias file.  Please add this back into the docker image.

**Comment by PavelPrischepa** [comment]
Hi @lhridley,

Sorry, I can't get the issue.

I've seen the `@dev` Drush alias in the PHP container here `/etc/drush/site-aliases/default.aliases.drushrc.php`. The command `docker-compose exec --user 82 php drush @dev status` works too.

Could you provide more details about the issue?

**Comment by charginghawk** [comment]
FYI, anybody running into this issue, I encountered it because my site docroot wasn't top level, and while I specified `NGINX_DOCROOT: web` I didn't also specify `PHP_DOCROOT: web` in my docker-compose.yml. The latter is what makes the drush alias work.
