### ISSUE TITLE
Place phony targets right before the appropriate rules

### ISSUE THREAD

**Issue by iryston** [wodby/docker4drupal#383]
**It is a good practice to place phony targets right before the appropriate rules.**
In this case you can edit rules in one place.

What do you think about this kind of code reformatting?

```make
## down : Stop containers.
.PHONY: down
down: stop

## start : Start containers without updating.
.PHONY: start
start:
	@echo "Starting containers for $(PROJECT_NAME) from where you left off..."
	@docker-compose start

## stop : Stop containers.
.PHONY: stop
stop:
	@echo "Stopping containers for $(PROJECT_NAME)..."
	@docker-compose stop
```

**Comment by csandanov** [comment]
it's ok, it kinda adds an extra noise but in this way fewer chances you'll forget to update `.PHONY`

**Comment by iryston** [comment]
Ok, I'll prepare pull request.
