### ISSUE TITLE
PHP 5.4 Support

### ISSUE THREAD

**Issue by albertski** [wodby/docker4drupal#385]
I am taking over a project that is currently using PHP 5.4. We will be working on upgrading but for the time being, I need to add a couple of new features. 

What would be the best way for me to get my docker to use php 5.4

**Comment by csandanov** [comment]
Try `wodby/drupal-php:5.3-4.7.5` but it's super old and hasn't been updated for a while

**Comment by albertski** [comment]
Thanks so much!

**Comment by albertski** [comment]
@csandanov Sorry I did try that one and it was php 5.3.  I also tried this one `PHP_TAG=5.3-dev-macos-4.4.2` and it was php 5.3.  Do you by any chance have one for php 5.4 or direct me how I can create one.

**Comment by csandanov** [comment]
We never had php 5.4 image because it hit EOL earlier than 5.3
