### ISSUE TITLE
SSH

### ISSUE THREAD

**Issue by Vacilando** [Wodby/docker4drupal#39]
Is there a way to connect to the local site via SSH? 
So that we can work using PuTTY when using Docker for Windows (rather than having to use PowerShell).

**Comment by Vacilando** [comment]
Is SSH already available? How to connect to it?

**Comment by PavelPrischepa** [comment]
Hi @Vacilando,

There is no **sshd** in containers.

**Comment by Vacilando** [comment]
Thanks for getting back to me on this, @PavelPrischepa.
Could sshd be added, so that we can access containers from Windows via PuTTY?

**Comment by PavelPrischepa** [comment]
@Vacilando, we can't add sshd to the php container because it'll violate the rule "container per process". So, we can make a new sshd container with access to docroot. Is it what you mean?

**Comment by Vacilando** [comment]
Sounds like a great approach, very elegant, @PavelPrischepa!

**Comment by Vacilando** [comment]
Any ETA on adding the SSH container? Would be a tremendous improvement!

**Comment by PavelPrischepa** [comment]
@Vacilando Special for you https://github.com/Wodby/docker4drupal/commit/9fd3080532c201b3e85b65e56f4f1a51c9f43496.

I've added SSHd container. Uncomment it, specify SSH public key then access it via `ssh -p 8022 root@localhost`.

**Comment by Vacilando** [comment]
@PavelPrischepa: excellent, it works perfectly!

NB: the port is 8006 (not 8022).

Thanks, closing this ticket.
