### ISSUE TITLE
Traefik 2 released, and container stop working.

### ISSUE THREAD

**Issue by Niklan** [wodby/docker4drupal#401]
https://hub.docker.com/_/traefik?tab=tags

The Traefik 2 is released. Since in docker-compose.yml we have

```yaml
  traefik:
    image: traefik
```

It gets the last available release. But seems 1.7 and 2.0 is not BC releases and this cause problem.

As a temporary solution I used a specific tag:

```yaml
  traefik:
    image: traefik:v1.7.16-alpine
```

docker-compose.yml must be updated to traefik 2 settings or have a tag version as other containers.

**Comment by ChristopheCaron** [comment]
Same issue, with the specific tag indicated by Niklan, it works perfectly as temporary solution.

**Comment by brianV** [comment]
PR in #402 should provide a temporary fix until Traefik 2.0 can be fully supported.

**Comment by devkinetic** [comment]
`version: '2'

services:
  traefik:
    image: traefik:v2.0
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
    networks:
      - "xxxx"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

networks:
  xxxx:
    external:
      name: xxxx_default
`

**Comment by csandanov** [comment]
Merged #402 to pin traefik to v1. Upgrade to v2 will be performed with the next release

**Comment by mralexho** [comment]
Anyone know why the alpine image is slightly larger (+5mb)?

**Comment by csandanov** [comment]
perhaps the previous latest image wasn't actually alpine-based but was [from scratch](https://github.com/containous/traefik-library-image/blob/3ddcd457753890311afbd4209996e07caf84c1be/scratch/Dockerfile), so I guess the right tag would be just `1.7` instead of `v1.7.16-alpine` but I don't it makes a difference

**Comment by xcusso** [comment]
The same isssue in local multiste traefik.yml. 
Solved:
`version: '2'

services:
  traefik:
    image: traefik:v1.7.16-alpine
    restart: unless-stopped
    command: -c /dev/null --web --docker --logLevel=DEBUG
    networks:
      - project1
      - project2`

**Comment by csandanov** [comment]
Docker4Drupal [5.4.11](https://github.com/wodby/docker4drupal/releases/tag/5.4.11) has been released with traefik v2 support, update your `docker-compose.yml` with new traefik service and traefik labels.

**Comment by xcusso** [comment]
Still problems with multiple project using traefik:v2.0 or traefik:v2.0.2 
Container traefik restart every few seconds. 
In logs we can see:
command traefik error: failed to decode configuration from flags: field not found, node: c

**Comment by csandanov** [comment]
You should update the command of `traefik` service.

**Comment by xcusso** [comment]
Sorry for my insistence, I will say that you must update traefick.yml to adjust to the parameters of docker-compose.yml (traefik section). If you download Docker4Drupal 5.4.11 to install in multiple project in local environment they still fails..

**Comment by sandykadam** [comment]
@csandanov so you mean to say now we can run multiple docker projects with this new traefik?
Like ..

/var/www/html/project1 - docker-compose up

-- different prompt
/var/www/html/project2 - docker-compose up

**Comment by xcusso** [comment]
No. Install a traefik container for all the projects (dockers) in the same server (ip). See: https://wodby.com/docs/stacks/drupal/local/ section: Running multiple Projects.

**Comment by csandanov** [comment]
`traefik.yml` content is now also updated for v2, missed that before
