### ISSUE TITLE
Improving the way to configure Drupal while using own codebase

### ISSUE THREAD

**Issue by Kwadz** [wodby/docker4drupal#403]
As mentioned in the [documentation](https://wodby.com/docs/stacks/drupal/local/#mount-my-codebase) we currently have to configure manually the database details in the `settings.php` file while these details are already present in the `.env` file

I think this way can be improved using CLI commands to automatise the process as I showed in [this answer](https://stackoverflow.com/a/57956441/1941316).

I would suggest adding an `install.sh` file containing this code with the environment variables as arguments. Then no need to replicate manually the content of the `.env` file.

What do you think? If agreed I'll do a pull request.

**Comment by csandanov** [comment]
I think we can just add the command in Makefile (`docker.mk`), it already includes `.env`

**Comment by Kwadz** [comment]
What do you mean by "command" please? Since it's singular I don't understand what you mean.
Could you be more precise with your words?

If you're talking about putting the code directly in Makefile using multiple `docker exec` commands, you have to keep in mind the code is multilines. Using a `.sh` file to keep readability is much cleaner IMO.

**Comment by csandanov** [comment]
I doubt people would want another file from docker4drupal in their root directory, especially for the very specific one-time use case. I'm not even sure how many copies our Makefile and even if they do how many of them actually running make commands? Also, some people store `settings.php` file under the version control and prefer to edit it themselves.

**Comment by Kwadz** [comment]
All right, let's forget it then.
