### ISSUE TITLE
Interactive mode is not yet supported on Windows

### ISSUE THREAD

**Issue by Vacilando** [wodby/docker4drupal#41]
README.md suggests:

> You can connect to any container by executing the following command:
> $ docker-compose exec php sh

However, I am getting the following error message:
_Interactive mode is not yet supported on Windows. Please pass the -d flag when using `docker-compose exec`._

**Comment by drubb** [comment]
This is a well-known issue of docker compose for windows, docker is working on it: https://github.com/docker/compose/issues/3194. In the meantime you can try the corresponding docker command:
`docker exec -it <containername> sh`
Look for the containername with `docker ps` (maybe it's 'php' in your case)!

**Comment by GodGinrai** [comment]
If you install docker-compose through pip, it works.  This was using cygwin; (babun would likely work, too) I can't guarantee this will install the good version of docker-compose if you are not using cygwin or babun.

**Comment by joswhite** [comment]
docker/compose#3194 is now fixed - shouldn't this be closed?
