### ISSUE TITLE
How to map localhost:port to domain name

### ISSUE THREAD

**Issue by Vacilando** [wodby/docker4drupal#42]
#21 and https://github.com/Wodby/docker4drupal/blob/master/README.md recommend using different port numbers for different sites.

That works, but if you work with 3 or more sites it starts to get confusing.

Is there a quick way to assign domain names instead of localhost:port via docker-compose.yml?
Perhaps by using a local IP address which then can be mapped via the hosts file.

**Comment by brilsergei** [comment]
`
...
PHP_SITENAME: mysite.com
...
NGINX_SERVER_NAME mysite.com
...
`
then add to your hosts
`127.0.0.1    mysite.com`
But you still have to use port forvarding and access site by mysite.com:8000 because 80 ports is already taken by another process (by docker, as I understand).
And use PHP_SITENAME because there is typo in source files for the corresponding image.

**Comment by PavelPrischepa** [comment]
> And use PHP_SITENAME because there is typo in source files for the corresponding image.

By the way, this issue has been fixed in #43.

**Comment by ndobromirov** [comment]
Can't we have one more nginx container that will act as a proxy in a separate project.

In the proxy configs, you will bind the domain:port mappings, using base ports ranges for name-spacing.
Proxy will work on port 80 and 443 (for SSL).
Like so:
Project 1 -> 7XXX ports, project 2 -> 8XXX and so on.

In the proxy you have:
mysyte1.local goes to localhost:7XXX
mysyte2.local goes to localhost:8XXX
.. And so on.

When starting new project:
1. Only once - add definition in your local proxy configuration and hosts file
  ( this will be a centralized thing to be actively used for all projects)
2. You prepare everything (with custom ports in your composer file)
3. Have fun :)

**Comment by Vacilando** [comment]
@ndobromirov's idea sounds good. It would also be a solution for #21.

**Comment by macmladen** [comment]
I am currently using [jwilder/nginx-proxy](https://github.com/jwilder/nginx-proxy) container to get name resolving but Pavel has already said something about using [containous/traefik](https://github.com/containous/traefik) in #50

**Comment by bleen** [comment]
@macmladen can you elaborate on how you are using nginx-proxy a bit (e.g. give some sample configs) ... I've been trying to get this working for a bit without success. This workaround seems promising but having some examples would be great!!

**Comment by csandanov** [comment]
You can now use docker4drupal with domains http://docs.docker4drupal.org/en/latest/domains/

**Comment by henryejemuta** [comment]
> @macmladen can you elaborate on how you are using nginx-proxy a bit (e.g. give some sample configs) ... I've been trying to get this working for a bit without success. This workaround seems promising but having some examples would be great!!

That's quite straightforward you can see example block below:

````
server {
    listen 80;
    server_name yourdomainname.com;
    root /pathtoyourapp;

    index index.html index.htm; #Include your dydnamic script index here e.g. index.php

    location / {
                proxy_pass http://127.0.0.1:8000;
        }

# Your dynamic script processor and other configs


}
````
