### ISSUE TITLE
Running Blackfire?

### ISSUE THREAD

**Issue by kevinquillen** [wodby/docker4drupal#423]
In an older closed issue, its started that Blackfire won't work with the php dev tag images. I just tried a non dev image, and the blackfire module is still not loaded.

Is there a way to use Blackfire docker image on Mac? What is the right php tag to use? I am following the Blackfire docs but it seems outdated.

**Comment by csandanov** [comment]
Blackfire won't work in debug enabled images which isn't the same as dev images. The extension is disabled by default, you should enable it by adding `$PHP_BLACKFIRE=1` to `php` service and uncommenting `blackfire` service in `docker-compose.yml`. If it still doesn't work, please provide more details requested in the issue template

Also: https://wodby.com/docs/stacks/drupal/containers/#blackfire
