### ISSUE TITLE
Cannot install webprofiler module, due to not met requirements of symfony/stopwatch

### ISSUE THREAD

**Issue by nasl** [wodby/docker4drupal#426]
***Codebase***
Built-in vanilla Drupal 8 latest + some contrib modules already downloaded with composed but not installed/enabled. Some core modules installed. Local docker desktop environment, win 10 pro. Everything default, no modifications to docker config files.

**Describe your issue**
Cannot install webprofiler module, due to not met requirements. Can download other modules with composer, every module was ok, started from A letter, ~40 modules.

**Output of `docker info`**
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - drupal/webprofiler 2.0.0-rc1 requires symfony/stopwatch 2.4.* -> no matching package found.
    - drupal/webprofiler 2.0.0-rc2 requires symfony/stopwatch 2.4.* -> no matching package found.
    - drupal/webprofiler 2.0.0-rc3 requires symfony/stopwatch 2.4.* -> no matching package found.
    - Installation request for drupal/webprofiler ^2.0@RC -> satisfiable by drupal/webprofiler[2.0.0-rc3, 2.0.0-rc2, 2.0.0-rc1].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it
```

**Contents of your `docker-compose.yml`**
```
Paste here
```

**Contents of your `.env`**
```
Paste here
```

**Logs output `docker-compose logs`**
```
Paste here
```

Of course, no positive result of `composer require symfony/stopwatch:^2.4`
 `composer require symfony/stopwatch` installs 5.0.5 version

Can install webprofiler with composer on other drupal8 installations, checked it on opendevshop server.

EDIT: somehow... webrofiler module seem to be installed and works.

**Comment by csandanov** [comment]
It's a composer dependencies issue, how is that related to d4d?

**Comment by nasl** [comment]
...I have no idea :( just mentioned here as in other installs I do not see such message.

**Comment by csandanov** [comment]
Closing as not relevant, you should post this question on stackoverflow
