### ISSUE TITLE
Upload file in PMA limited to 2 048KiB

### ISSUE THREAD

**Issue by nasl** [wodby/docker4drupal#427]
***Codebase***
Default PMA container

**Describe your issue**
Upload through PMA is limited 2 048KiB, but I assume PHP_UPLOAD_MAX_FILESIZE: 1G and 
      PHP_MAX_INPUT_VARS: 1G in docker-compose should set it to 1G

**Comment by csandanov** [comment]
there's was the fix recently https://github.com/wodby/docker4drupal/pull/425
