### ISSUE TITLE
xhprof must have container_name

### ISSUE THREAD

**Issue by Niklan** [wodby/docker4drupal#428]
I believe that `xhprof` [container](https://github.com/wodby/docker4drupal/blob/master/docker-compose.yml#L241-L247) must have name.

Currently, it has this config:

```yaml
#  xhprof:
#    image: wodby/xhprof:$XHPROF_TAG
#    restart: always
#    volumes:
#      - files:/mnt/files
#    labels:
#      - "traefik.http.routers.${PROJECT_NAME}_xhprof.rule=Host(`xhprof.${PROJECT_BASE_URL}`)"
```

But there is no `container_name` as it done for all others. This cause problems:

- Container name is mandatory. Since we do not set it, the docker set it manually based on current directory name.
- Since container name is not set directly in docker-compose.yml, this container won't stop by `docker-composer stop` and will continue working.
- Since this container is not handled by docker-compose after it started, this container will auto-start with the host.

Assuming all this, if you have 10 projects, you will have 10 xhprof containers which will auto start with the host every time. This also slow down the `docker-compose up -d` since docker trying to figure out what to do with xhprof container and sometimes can hag up for a several seconds.

My proposal and solution is easy, we must add `container_name` to xhprof container for consistency and solving all those problems.

```yaml
#  xhprof:
#    image: wodby/xhprof:$XHPROF_TAG
#    container_name: "${PROJECT_NAME}_xhprof"
#    restart: always
#    volumes:
#      - files:/mnt/files
#    labels:
#      - "traefik.http.routers.${PROJECT_NAME}_xhprof.rule=Host(`xhprof.${PROJECT_BASE_URL}`)"
```

**Comment by csandanov** [comment]
Sounds good, we also do not have it in kibana and elasticsearch services
