### ISSUE TITLE
Typo in environment variable names

### ISSUE THREAD

**Issue by brilsergei** [Wodby/docker4drupal#43]
Docker compose has
`PHP_SITE_NAME: dev`
`PHP_HOST_NAME: localhost:8000`
But in default.aliases.drushrc.php for wodby/drupal-php:5.6
`$aliases[isset($_SERVER['PHP_SITENAME']) ? $_SERVER['PHP_SITENAME'] : 'dev'] = array(`
`  'root' => '/var/www/html/' . (isset($_SERVER['PHP_DOCROOT']) ? $_SERVER['PHP_DOCROOT'] : ''),`
`  'uri' => isset($_SERVER['PHP_HOSTNAME']) ? $_SERVER['PHP_HOSTNAME'] : 'localhost:8000',`
`);`

**Comment by PavelPrischepa** [comment]
Hi @brilsergei, 

Thank you very much, I've fixed the bug.
