### ISSUE TITLE
Use Mutagen instead of docker-sync

### ISSUE THREAD

**Issue by Kwadz** [wodby/docker4drupal#442]
It's a known issue that Docker for Mac is slow when using shared volumes containing a big amount of files, see the historical https://github.com/docker/for-mac/issues/77.

So, some workarounds came like [`:cached` ](https://docs.docker.com/docker-for-mac/osxfs-caching/#cached) and [docker-sync](http://docker-sync.io/). However it's not totally satisfactory because it's still slow compared to native and docker-sync requires a lot of resources when syncing. 

That being said, there is a good alternative, almost perfect, which is [Mutagen](https://mutagen.io/). Some benchmark is available [here](https://medium.com/netresearch/improving-performance-for-docker-on-mac-computers-when-using-named-volumes-55580efcbf68#bf1b). It's almost **as fast as native** shared volumes with Linux!

So, I suggest replacing docker-sync with Mutagen. I'm gonna send a pull request with Mutagen configured for docker4drupal.

**Comment by Kwadz** [comment]
If it's OK to use it, I'll update the documentation accordingly.

**Comment by adriadrop** [comment]
I can confirm mutagen works great on Mac OSx, also it can be run with d4d with just UI, but this is nice addition to fine tune it

Wondering about your config and ignore part, where you ignore web/core vendor/ etc, why would you ignore those paths by default and how would you synch them ?

**Comment by Kwadz** [comment]
Thanks @adriadrop for your feedback. You're right, may be we should not ignore those files by default, like we currently do with docker-sync. So, I commented them.

To answer your question, on my side I comment for example _core/_ or _contrib/_ when I want to work on it. Otherwise for _vendor/_ I always keep it not sync, and just execute a local `composer install` one time to get the files locally for my IDE.

I'd like to add a `COPY` instruction in the Mutagen's _Dockerfile_ to get all the files already available at the first start, and create a _.dockerignore_ accordingly.
That said, I think we should use an _app/_ directory instead of synchronizing all the project, see #441.
So I'd like we agree on that before.

**Comment by weitzman** [comment]
FYI Mutagen is now integrated into the nightly build of Docker Desktop for Mac. Its coming soon(ish) to everyone.

**Comment by michalkleiner** [comment]
Had a look at the nightly Docker Desktop for Mac build and it's quite simple, not offering any additional configuration options like excludes, custom permissions etc. So a good start, but unless it starts supporting mutagen project configs per folder it's still quite far off.

**Comment by csandanov** [comment]
Thank you, it looks very interesting. Obviously it would be preferable to use the built-in solution. Perhaps we should wait since it's already in the edge?

**Comment by Kwadz** [comment]
The built-in solution does not allow fine tuning. Using Mutagen manually is much more advanced for power users.

**Comment by csandanov** [comment]
It seems it will be added https://github.com/docker/for-mac/issues/4621#issuecomment-637025688

**Comment by Kwadz** [comment]
Good news!
Anyway, I'd suggest letting docker4drupal users enjoy the speed with the Mutagen manual configuration awaiting the built-in solution is ready and provided in the stable version of Docker for Mac. When this will be done, we'll be able to remove it here. What do you think?

**Comment by adriadrop** [comment]
https://docs.docker.com/docker-for-mac/edge-release-notes/#docker-desktop-community-2320

now it can called with just :delegate flag so basically 

`- ./:/var/www/html:delegate`

**Comment by Kwadz** [comment]
FYI, Docker removed the built-in Mutagen in Edge: _The Mutagen file sync feature that we have been experimenting with in recent Edge releases has been removed_.
https://docs.docker.com/docker-for-mac/edge-release-notes/

Since using Mutagen manually is much better than using docker-sync manually, I suggest that the community benefit from this.

**Comment by csandanov** [comment]
ok, we need how-to-use documentation
