### ISSUE TITLE
Was the solrconfig set 8.x-3.9 removed from 5.4.19?

### ISSUE THREAD

**Issue by mralexho** [wodby/docker4drupal#451]
***Codebase***
Mounted codebase

**Describe your issue**
During an update, I noticed a merge conflict with the SOLR_CONFIG_SET env variable. Has "search_api_solr_8.x-3.9" been removed from 5.4.19?

**Contents of your `.env`**
```
### --- SOLR ---

SOLR_CONFIG_SET="search_api_solr_4.0"
#SOLR_CONFIG_SET="search_api_solr_8.x-3.2"
#SOLR_CONFIG_SET="search_api_solr_8.x-2.7"
#SOLR_CONFIG_SET="search_api_solr_8.x-1.2"
#SOLR_CONFIG_SET="search_api_solr_7.x-1.14"
```

I see it listed as being supported on https://github.com/wodby/solr. Just want to confirm.

Thank you!

**Comment by csandanov** [comment]
No, it in fact wasn't, just replaced the default to 4.0. Now returned, all config sets listed at https://github.com/wodby/solr.

**Comment by mralexho** [comment]
Thank you!
