### ISSUE TITLE
Alpine Version:  I am getting a minimum Alpine 3.9 error message; and seeing Alpine 3.8.5 in logs

### ISSUE THREAD

**Issue by RightsandWrongsgit** [wodby/docker4drupal#458]
***OS type***
macOS

***Codebase***
Built-in vanilla Drupal, fresh GitHub clone

**Describe the bug**
I was seeing no port available messages.  Went into the logs and is appears more basic than that, as NIGIX is exiting prematurely.  Seems to show Alpine 3.8 associated with the container.  And I am getting a banner across the Visual Studio interface when I try to attach to the container that a minimum of Alpine 3.9 is required [Alpine Linux 3.9 or later required.]

**Contents of your `docker-compose.yml`**
```
Fresh Vanilla install from GitHub

**Contents of your `.env`**
```
Fresh Vanilla install from GitHub

**Logs output `docker-compose logs`**
VERSION_ID=3.8.5
PRETTY_NAME="Alpine Linux v3.8"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"
[801 ms] 
[801 ms] Start: Run in container: cat /etc/passwd
[805 ms] Start: Run in container: test -d /home/wodby/.vscode-server
[808 ms] 
[808 ms] 
[808 ms] Start: Run in container: set -o noclobber ; mkdir -p '/home/wodby/.vscode-server/data/Machine' && { > '/home/wodby/.vscode-server/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
[811 ms] 
[811 ms] 
[811 ms] Exit code 1

**Comment by csandanov** [comment]
We're stuck with 3.8 for now because pagespeed doesn't yet support openssl 1.1 https://github.com/apache/incubator-pagespeed-mod/issues/1856

**Comment by csandanov** [comment]
Nginx's base image was updated to alpine 3.13
