### ISSUE TITLE
Add back Drupal Console support

### ISSUE THREAD

**Issue by mralexho** [wodby/docker4drupal#461]
**Is your feature request related to a problem? Please describe.**
Removal of Drupal Console in https://github.com/wodby/docker4drupal/releases/tag/5.4.23

**Describe the solution you'd like.**
It looks like Composer 2 support was just released https://github.com/hechoendrupal/drupal-console-extend-plugin/releases/tag/0.9.5. Can you please add it back to Drupal 8? 

Thank you.

**Comment by csandanov** [comment]
It's back!
