### ISSUE TITLE
Error install.php 

### ISSUE THREAD

**Issue by GaetanoDeRoberto** [wodby/docker4drupal#492]
I always get this error 

Error: Call to a member function setFormClass() on null in system_entity_type_build() (line 1217 of /var/www/html/web/core/modules/system/system.module).

![image](https://user-images.githubusercontent.com/3607105/129039244-5ecceee0-6240-4a55-bc2c-60034c73f9ff.png)

**Comment by basit-paracha** [comment]
I also having same issue, i am using Drupal9 with composer and docker4drupal, but when i want to setup , it gives me same error, its a weired situation.

**Comment by csandanov** [comment]
cannot reproduce from the latest version (master branch) on macos with vanilla drupal (`make` command), i recommend trying to clean up your docker volumes and try again:
```
docker system prune --volumes
```

**Comment by GaetanoDeRoberto** [comment]
Thanks,
I am on Windows 10 pro and tried to do as you suggested but nothing, it doesn't work.
I tried on Ubuntu and everything works fine
Perhaps the problem e is Windows WSL2

Anyway you should write that it doesn't work on Windows

**Comment by GaetanoDeRoberto** [comment]
ok i solved
If you are using a version of Drupal downloaded via composer you should not delete the docker-compose.override.yml file
Of course you also need to remember to set the directories for the persistent db

**Comment by webprogrammierer** [comment]
I have the same problem with same error message on Windows 10, Docker Desktop, WSL2:
`Error: Call to a member function setFormClass() on null in system_entity_type_build()`

As a not working solution I can add docker-compose.override.yml.

After rebuilding the project with docker-compose up everything seems to be okay. The error is gone and Drupal can be installed and used without problems.

BUT:
The main thing that docker-compose.override.yml changes is this:
```
php: 
    volumes:
    - codebase:/var/www/html
```

```
instead of:
    volumes:
    - ./:/var/www/html:cached
```

The consequence is the missing of the file sharing:  the drupal project files are not synced anymore between linux in the docker container and Windows.

So this solution is not acceptable.
Windows 10 Users want to use Windows to write code, change drupal template files and css files but still want to use docker. 

**Urgently I would need a solution where volumes can be shared between linux and windows without have the above error message.**

Anybody here who can help?
Thank you very much.
