### ISSUE TITLE
GuzzleHttp: Connection refused for internal calls

### ISSUE THREAD

**Issue by raul-drupal-dev** [wodby/docker4drupal#499]
***OS type***
macOS

***Drupal version***
9

***Codebase***
mounted codebase

**Describe the bug**

Guzzle internal calls give an error when you run the next lines:

```php
$client = \Drupal::httpClient();
$url = "http://drupal.docker.localhost/my/awesome/api";
$request = $client->get($url, [
      'headers' => ['Cookie' => \Drupal::request()->headers->get("cookie")],
]);  
````
***Error 1:***
```
GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: drupal.docker.localhost (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in GuzzleHttp\Handler\CurlFactory::createRejection() (line 200 of /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php).
```
***Error1 fix:***
Add the ip and domain of traefik to /etc/hosts on php container but then comes the error2

***Error2:***
```
GuzzleHttp\Exception\ConnectException: cURL error 7: Failed to connect to drupal.docker.localhost port 8000 after 0 ms: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in GuzzleHttp\Handler\CurlFactory::createRejection() (line 200 of /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php).
```

***SOLUTION:***
Reading the documentation from traefik we found this solution that helps in many other ways, it make it works for external and internal calls.

Please review it and merge it if you think this is fine.

```php
diff --git a/.env b/.env
index d058d3c..fce6a7f 100644
--- a/.env
+++ b/.env
@@ -6,6 +6,7 @@
 
 PROJECT_NAME=my_drupal9_project
 PROJECT_BASE_URL=drupal.docker.localhost
+PROJECT_PORT=8000
 
 DB_NAME=drupal
 DB_USER=drupal
diff --git a/docker-compose.yml b/docker-compose.yml
index 455fbe4..bf6d227 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -17,6 +17,8 @@ services:
   php:
     image: wodby/drupal-php:$PHP_TAG
     container_name: "${PROJECT_NAME}_php"
+    links:
+      - "traefik:${PROJECT_BASE_URL}"
     environment:
       PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
 #      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S opensmtpd:25
@@ -271,9 +273,9 @@ services:
   traefik:
     image: traefik:v2.0
     container_name: "${PROJECT_NAME}_traefik"
-    command: --api.insecure=true --providers.docker
+    command: --api.insecure=true --providers.docker --entrypoints.web.address=:${PROJECT_PORT}
     ports:
-    - '8000:80'
+    - '${PROJECT_PORT}:${PROJECT_PORT}'
 #    - '8080:8080' # Dashboard
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
```

**Comment by csandanov** [comment]
`.localhost` domain won't be resolved from the container to your host machine, you should add a hostname for localhost in `/etc/hosts`

**Comment by raul-drupal-dev** [comment]
But this couldnt be a solution because when you run down and up again, you lose that configuration...

Even this, It comes the second error, "connection refused" because the traefik container is not listening on the right port.

This is why you need to link the domains between containers and tell traefik listen same port as you are using.

 hope this make it bit more clear.

**Comment by csandanov** [comment]
I'm saying you should add a localhost domain on your host machine not in a container, or use a docker built-in alias, e.g. `host.docker.internal`. Or connect directly to the other container, e.g. `nginx`

**Comment by raul-drupal-dev** [comment]
hi @csandanov 
sorry for delay response, I was busy.
I test what you said: 

1- add the domain to my hosts (not in a container) and we get same error "connection refused"
2- Adding the alias to traefik, same error "connection refused"

```yml
traefik:
  image: traefik:v2.0
    container_name: "${PROJECT_NAME}_traefik"
   command: --api.insecure=true --providers.docker
  ports:
   - '8000:80'
  # - '8080:8080' # Dashboard
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
  networks:
   default:
     aliases:
       - ${PROJECT_BASE_URL}
```

```php
GuzzleHttp\Exception\ConnectException: cURL error 7: Failed to connect to drupal.docker.localhost port 8000 after 0 ms: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in GuzzleHttp\Handler\CurlFactory::createRejection() (line 200 of /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php).
```

There is a mistake on the issue comment about the call, maybe this could be the cause of the confusion:
- the base-url (http://drupal.docker.localhost:8000) is taken dynamically from the drupal so automatically get the domain and port you are using in your website.

```php
$client = \Drupal::httpClient();
$url = "http://drupal.docker.localhost:8000/my/awesome/api";   //<--- line that changes I forgot to put the port.
$request = $client->get($url, [
      'headers' => ['Cookie' => \Drupal::request()->headers->get("cookie")],
]);  
````

I do not know what I'm doing wrong.

I really appreciate your help.

**Comment by csandanov** [comment]
I don't get it, you're still using `.localhost` domain in your example. This domain won't work, either use `nginx` or custom domain you've added on the host. Anyway, it's not a bug, for support requests use stackoverflow
