### ISSUE TITLE
memcache doesn't work, memcache drupal 8 module fail to install.

### ISSUE THREAD

**Issue by riccardoravaro** [wodby/docker4drupal#52]
(Currently using Extensions not available version Either the memcache or memcached extensions must be installed in order to use memcache integration.)

**Comment by PavelPrischepa** [comment]
@riccardoravaro The memcached extensions has been added:
- https://pkgs.alpinelinux.org/package/edge/testing/x86_64/php7-memcached
- https://pkgs.alpinelinux.org/package/edge/testing/x86_64/php5-memcached

Build https://travis-ci.org/Wodby/drupal-php/jobs/171295293

**Comment by JunYoshida-LH** [comment]
i cannot find the link.

https://pkgs.alpinelinux.org/package/edge/testing/x86_64/php7-memcached
https://pkgs.alpinelinux.org/package/edge/testing/x86_64/php5-memcached

**Comment by PavelPrischepa** [comment]
@JunYoshida-LH 
php5 unsupported, for php7 it was renamed to `php7-pecl-memcached`
https://pkgs.alpinelinux.org/packages?name=php7-pecl-memcached&branch=edge
