### ISSUE TITLE
Update docker-compose file. Crond is not working.

### ISSUE THREAD

**Issue by nvelychenko** [wodby/docker4drupal#523]
In the latest version of the PHP image, you've updated [condition](https://github.com/wodby/php/blob/master/7/docker-entrypoint.sh#L111) during which crond is enabled. Also documentation was [updated](https://github.com/wodby/php/blob/master/README.md#crond).

What needs to be done is to replace this command: [`sudo -E LD_PRELOAD=/usr/lib/preloadable_libiconv.so crond -f -d 0`](https://github.com/wodby/docker4drupal/blob/master/docker-compose.yml#L59) with new one `sudo -E crond -f -d 0`

**Comment by iVegas** [comment]
This can be closed  due to #524
