### ISSUE TITLE
The documentation still recommends to use drupal-composer/drupal-project instead of the drupal/recommended-project

### ISSUE THREAD

**Issue by wombatbuddy** [wodby/docker4drupal#530]
The documentation on the following page: https://wodby.com/docs/1.0/stacks/drupal/local/
recommends to use the "drupal-composer/drupal-project" the composer template.
But now days is recommended to use the "drupal/recommended-project" instead, see https://www.drupal.org/docs/develop/using-composer/manage-dependencies

Proposed solution:
to alter the documentation that it provides the link to the [drupal/recommended-project](https://github.com/drupal/recommended-project).

**Comment by csandanov** [comment]
Thank you, now fixed
