### ISSUE TITLE
Error on Docker Desktop 4.16

### ISSUE THREAD

**Issue by kvantstudio** [wodby/docker4drupal#536]
Not work php and nginx with after update Docker Desktop 4.15 to 4.16. Error with permissions sudo command not access with user root.

**Comment by csandanov** [comment]
Seems like a docker desktop bug that should be fixed https://github.com/docker/for-mac/issues/6675

**Comment by mrothauer** [comment]
same here: `error: failed switching to "root": operation not permitted`

**Comment by csandanov** [comment]
Fixed in 4.16.1

**Comment by kvantstudio** [comment]
Mailhog not start in 4.16.1, not errors in logs. Crond start with error /docker-entrypoint.sh: line 13: /etc/crontabs/www-data: Permission denied

PHP and NGINX now work fine on 4.16.1!

**Comment by kvantstudio** [comment]
Yes fixed!
