### ISSUE TITLE
Unresponsive service when requesting resources

### ISSUE THREAD

**Issue by mccrodp** [wodby/docker4drupal#54]
This repo looked great, but can't get anywhere yet with it. After running up with only the maria, php and nginx services, I get the following when requesting the CHANGELOG, install.php and a custom added index.html.

```
b359ceafdecc_docker4drupal_nginx_1 | 172.22.0.1 - - [25/Oct/2016:14:06:53 +0000] "GET /install.php HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"
b359ceafdecc_docker4drupal_nginx_1 | 172.22.0.1 - - [25/Oct/2016:14:07:11 +0000] "GET /install.php HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"
b359ceafdecc_docker4drupal_nginx_1 | 172.22.0.1 - - [25/Oct/2016:14:07:11 +0000] "GET /CHANGELOG.txt HTTP/1.1" 404 564 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"
b359ceafdecc_docker4drupal_nginx_1 | 172.22.0.1 - - [25/Oct/2016:14:07:14 +0000] "GET /CHANGELOG.txt HTTP/1.1" 404 564 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"
b359ceafdecc_docker4drupal_nginx_1 | 172.22.0.1 - - [25/Oct/2016:14:07:51 +0000] "GET / HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"
b359ceafdecc_docker4drupal_nginx_1 | 172.22.0.1 - - [25/Oct/2016:14:07:51 +0000] "GET /index.html HTTP/1.1" 200 5 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"
```

When I run `docker-compose exec nginx sh` I can see the files are there but can only access if I generate a custom `index.html`, the other 2 resources in example above are not found.

**EDIT:** While writing this I found that the php resource was eventually loaded, massive delay though. Then the error is that the database is unreachable.

```
PDOException: SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock' (2 "No such file or directory") in lock_may_be_available() (line 167 of /var/www/html/includes/lock.inc).
```

**Comment by PavelPrischepa** [comment]
@mccrodp `CHANGELOG.txt` is not available according to a [rule](https://github.com/Wodby/drupal-nginx/blob/master/drupal8.conf#L100 in Nginx config). The rule based on popular [Nginx for Drupal config](https://github.com/perusio/drupal-with-nginx/blob/747fc306b86ff772829265ab475de7b9825aff7e/apps/drupal/drupal.conf#L214).

About `/install.php`. It should works for D7 only, try /core/install.php for D8.

> Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock'

It looks like an issue settings.php. Be sure you are using `mariadb` as a database host. Something like that (D8 config):
```
$databases['default']['default'] = array (
  'database' => 'drupal',
  'username' => 'drupal',
  'password' => 'drupal',
  'prefix' => '',
  'host' => 'mariadb',
  'port' => '3306',
  'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql',
  'driver' => 'mysql',
);
```

**Comment by mccrodp** [comment]
Thanks for the reply @PavelPrischepa. I was able to reproduce this error with Wordpress Quickstart, modified it for Drupal and once I mount the volume with same settings.php it give the above error. There's some lower level Docker error here, (not with this repo) on Docker for Mac. Or, I need to define the volume separately and give it access to the DB container. Anyways, I move to using Kalabox for now as it was quicker. Hopefully will post an issue in Docker soon about it.
