### ISSUE TITLE
Drupal codebase not downloaded

### ISSUE THREAD

**Issue by yonas** [Wodby/docker4drupal#55]
Does docker4drupal download the Drupal codebase?

I might have missed a step, but this is what I ran:

```
wget https://raw.githubusercontent.com/Wodby/drupal-compose/master/docker-compose.yml
docker-compose up -d
```

Going to `http://localhost:8000` returns a 404 error with an empty white page saying "File not found."

I wasn't able to find the Drupal codebase in `/var/www/html` when looking in the nginx container.

**Comment by PavelPrischepa** [comment]
Hi @yonas, docker4drupal doesn't provide Drupal codebase. You should download it manually.

**Comment by csandanov** [comment]
@yonas, docker4drupal is designed to be used with your git cloned directory containing your Drupal project.

**Comment by yonas** [comment]
@PavelPrischepa @csandanov Thanks!
