### ISSUE TITLE
How to add a module to a Built-in vanilla Drupal installation with the use of composer?

### ISSUE THREAD

**Issue by justmeonthegit** [wodby/docker4drupal#558]
***Codebase***
Built-in vanilla Drupal  

**Describe your issue**
I want to add modules to the drupal built in plan vanilla drupal version with the use of composer. how to do that?

**Comment by csandanov** [comment]
you can shell to the drupal container via `make shell` and then use `composer require` as usual

**Comment by justmeonthegit** [comment]
Great, I understand. Thxs
