### ISSUE TITLE
Use confd

### ISSUE THREAD

**Issue by fortis** [wodby/docker4drupal#56]
It looks great for environment variables  http://www.mricho.com/confd-and-docker-separating-config-and-code-for-containers/

**Comment by csandanov** [comment]
Yes, we are aware of confd and use it at Wodby but I'm not sure it makes sense for local development. We should keep docker4drupal as simple as possible, people who need additional tools can always fork it.

**Comment by PavelPrischepa** [comment]
It makes sense if you are using confd as a template engine. Run confd once (not daemon) during the container start.

**Comment by csandanov** [comment]
New images now use simplified version of gotpl from confd for config templates https://github.com/wodby/gotpl (e.g. https://github.com/wodby/nginx/blob/master/1.10/templates/nginx.conf.tpl)
