### ISSUE TITLE
Mariadb version 10.0.16 that supports json type

### ISSUE THREAD

**Issue by mgomma** [wodby/docker4drupal#57]
How to change mariadb to version 10.0.16 that supports json tabke type as I need to install JSON module.

**Comment by PavelPrischepa** [comment]
There is MariaDB 10.1.14 in the latest image. Does it fits you?

**Comment by mgomma** [comment]
MySQL 5.7.7+ (JSON)
MariaDB 10.10.x+ (JSON)

required for module [https://www.drupal.org/project/jsonb](jsonb)

**Comment by csandanov** [comment]
The current MariaDB version is 10.1.19, there's no 10.10 line (https://downloads.mariadb.org/mariadb/+releases/), maybe the maintainer meant 10.1, not 10.10
