### ISSUE TITLE
Error with drush sql-cli to import database

### ISSUE THREAD

**Issue by ChristopheCARONMGDIS** [wodby/docker4drupal#572]
***OS type***
Linux (ubuntu)

***Drupal version***
10

***Codebase***
Built-in vanilla Drupal or mounted codebase

**Describe the bug**

If you import with drush sql-cli a sql file you've got an error:
2026 SSL is required
![image](https://github.com/user-attachments/assets/c21cd425-03a0-4ef5-8502-ad46738f9045)

This bug comes today so I think this a recent update of a container
Even with an old tag, like MARIADB_TAG=10.11-3.26.0
I've got the issue

I can skip the error with parameters --extra=skip-ssl for information.

**Comment by csandanov** [comment]
ref https://github.com/wodby/drupal-php/issues/104

**Comment by ChristopheCARONMGDIS** [comment]
Thansk for your quick answer so we will patient for new wodby php release  ;)
