### ISSUE TITLE
Serving Drupal from a subdirectory?

### ISSUE THREAD

**Issue by mlbrgl** [Wodby/docker4drupal#58]
Hi,

I have the following folder structure: 

```
/var
    /www
        /html
            docker-compose.yml
            /drupal-composer
                /web (Drupal docroot installed through drupal-composer)
                    index.php
            index.html

```
In the docker-compose.yml, I defined: 
```
PHP_DOCROOT: drupal-composer/web
NGINX_DOCROOT: drupal-composer/web
```

Visiting localhost:8000 serves index.html and not index.php. I made sure to reload the containers via `docker-compose restart`.

Any idea what I might be missing?

Thanks!

**Comment by artemboyko43** [comment]
Hi,

I think you should correct volumes in php, It should be 
`    
volumes:
      - ./drupal-composer:/var/www/html
`

And also nginx just set to web dir.
`NGINX_DOCROOT: web`

It is working in my repo: https://github.com/artemboyko43/otk-drupal
But I use directory project instead of drupal-composer

**Comment by mlbrgl** [comment]
Thanks @artemboyko43! Shifting to the next level of subdirectory down seems to do the trick indeed.
