### ISSUE TITLE
How to Create Multiple databases

### ISSUE THREAD

**Issue by dcre** [wodby/docker4drupal#59]
Hello. i am using docker4drupal containers for local development. I need to create one more database apart from the default 'drupal'. However phpmyadmin does not have permissions and i do not know the root password to create the database from console. How can i tackle this?

**Comment by martinfrances107** [comment]
have you tried getting a shell on the mysql container 

something like 

docker exec -it drupal_mariadb_1 sh

if you have root user access on  that container then you can google for one of the many ways of changing password?

With something like 

mysqladmin -u USER -p password NEWPASSWORD 

I hope this helps

**Comment by dcre** [comment]
Yes i am using the shell on the mysql container as you described.

The problem is that when i try to actually connect to mysql from within the container, i cannot connect as i dont know the root password. I get
Access denied for user 'root'@'localhost' (using password: NO)

In the docker-compose file i see a MYSQL_RANDOM_ROOT_PASSWORD: 1
I guess that the root password is randomly created.

So, question is, how can i actually connect to mysql and maybe create a new table from the console?

**Comment by martinfrances107** [comment]
Do you have access to the log output?

[ One way is to look at the output from docker-compose up. ]

One of the early mariadb_1 logs entries tells you what the password is.

**Comment by umpirsky** [comment]
@martinfrances107 I only see `mariadb_1  | 2016-11-21 17:54:24 140417542949928 [Warning] 'proxies_priv' entry '@% root@e34ba3e0e621' ignored in --skip-name-resolve mode.`, but still getting error when:

```
docker-compose exec mariadb sh -c 'exec mysqldump -uroot -p"e34ba3e0e621" drupal'
mysqldump: Got error: 1045: "Access denied for user 'root'@'localhost' (using password: YES)" when trying to connect
```

**Comment by PavelPrischepa** [comment]
@dcre 

> So, question is, how can i actually connect to mysql and maybe create a new table from the console?

It should works like that:

- Enter a container `docker-compose exec <Maria DB container name> sh`
- Exec mysql cli `mysql -u<user> -p<password>`
- Do what yo need in mysql/mariadb.

**Comment by dcre** [comment]
@PavelPrischepa

The actual problem is not how to connect to mysql and perform an operation.
The problem is the root credentials for connecting to mysql

As noted by umpirsky, a root password does show when starting the containers, but this password is not accepted for root login to mysql.

Without root login to mysql i dont see how i can actually create a second database.

**Comment by PavelPrischepa** [comment]
@dcre I'm failed to reproduce the issue

Root password generated:
```
mariadb_1  | GENERATED ROOT PASSWORD: deeShoab3No3Oom2pha3dah3seib9ahk
```
Logged in successfully:
```
> docker-compose exec mariadb mysql -uroot -pdeeShoab3No3Oom2pha3dah3seib9ahk
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 8
Server version: 10.1.19-MariaDB MariaDB Server

Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]>
```

**Comment by csandanov** [comment]
I'm closing this issue, @dcre if you still have this issue provide more details.

**Comment by dcre** [comment]
Just a last comment on this, for other people to save time.

mysql random password is only available and visible during initiation of the containers
docker-compose up

only in case you haven't enabled the volumes: parameter of mariadb in docker-compose.yml.
If you have set the volumes, in order to start the container with an already existing db, or other reason, you dont get to see the root password while initiating.

Not sure why this happens. Any ideas?

**Comment by martinfrances107** [comment]
@dcre

An already existing db on the host machine?

You should be able to ping your host machine from inside the container.

If you can ping the IP address of the db server then it is a matter of setting up the $databases variable in the settings.php file.

settings.php is self documenting - look for the text 

> you may optionally specify multiple "target" databases

I hope this helps.

**Comment by bserem** [comment]
@martinfrances107 this doesn't cover the fact that the root password is forever lost if you don't look for it in the first initialization of the environment, as dcre points out.

I still believe this is an issue.

**Comment by PavelPrischepa** [comment]
@bserem you can use env var `MYSQL_ROOT_PASSWORD` and specify any root pasword you want. Or you can keep root password empty via `MYSQL_ALLOW_EMPTY_PASSWORD`.

**Comment by bserem** [comment]
@PavelPrischepa this information is really good! I'll try it on the next project.

Thanks

ps: until now I'm just loading more containeres, which is actually pretty easy to do

**Comment by zsnagy73** [comment]
You can find the root password in the logs, just run:
`docker-compose logs mariadb | grep PASSWORD`

**Comment by ashishdeynap** [comment]
I'm facing an issue in creating a new database. Attached a screenshot of my screen. Any suggestion would be helpful. Thanks
![image](https://user-images.githubusercontent.com/17843409/28629913-674e44e6-7246-11e7-94f2-1f016011cfba.png)

**Comment by brandonratz** [comment]
@ashishdeynap and others. I was confused at first by the `MYSQL_USER` and `MYSQL_ROOT_PASSWORD`. In order to obtain root permissions you must log in as `root` user using the env variable `MYSQL_ROOT_PASSWORD` as password. By default from cli this might look something like this:

`docker exec -it docker4drupal_mariadb_1 mysql -u root -p`

I hope this helps someone. I was effectively attempting to run MySQL operations from the database user instead of the root user.

**Comment by adriadrop** [comment]
After you enter DB service, you need to login as root user. After that create DB you want. This is not all, unless you are adding root credentials to your setttings.php file, you will need to grant privilegies to your default user, probably named "drupal" so you need to run this mysql command

`GRANT ALL PRIVILEGES ON new_db.* TO 'drupal'@'%'; `

more on that here https://chartio.com/resources/tutorials/how-to-grant-all-privileges-on-a-database-in-mysql/

**Comment by howardshand** [comment]
Late to this but a better way to access the DB container without root creds is 
```
docker exec -u 0 -it my_drupal9_project_mariadb bash
```
