### ISSUE TITLE
Run docker-compose exec within a folder

### ISSUE THREAD

**Issue by jzavrl** [wodby/docker4drupal#60]
I'm using https://github.com/drupal-composer/drupal-project to build my Drupal structure and I feel this will become more and more of a standard than the one folder structure that you have now if you download Drupal from drupal.org.

The difference is that you get the vendor folder in the root and then the Drupal stuff is inside /web.

I've adjusted the docker-compose.yml PHP_DOCROOT and NGINX_DOCROOT to web, but when I do  `docker-compose exec --user 82 php drush` it doesn't work because it executes at root level.

I know I can connect on the container, cd into web and then run drush, which works, but I'm more interested how I can run all this from my host machine? Obviously the same problem exists with Console.

**Comment by csandanov** [comment]
AFAIK, you can specify path to your Docroot via -r option in drush command

**Comment by ashhishhh** [comment]
More Precisely `docker-compose exec --user 82 php drush -r /var/www/html/web cr
5 mins
`

**Comment by MacSim75** [comment]
I opened an issue so we can have that -w--workdir option as if we were using `docker exec`.
https://github.com/docker/compose/issues/5650
