### ISSUE TITLE
Change mariabdb default port

### ISSUE THREAD

**Issue by arrubiu** [wodby/docker4drupal#63]
I need to change default mariadb port.
As described on docs, I've tried to add a command option like this:

`command: --port=3307`

Nothing changes: if I run "docker ps", port displayed for "mariadb" container in 3306.

Is there a way to change port?

**Comment by martinfrances107** [comment]
If you mapped the existing port from the container to different one on the host -  would that solve your problem ?

https://github.com/Wodby/docker4drupal/blob/master/docker-compose.yml

If you look at the pma service  - the port inside 80 which is mapped to 8001 on the outside.

    ports:
     - "8001:80"

I hope this helps

**Comment by arrubiu** [comment]
The problem is that I've to make a migration between two drupal sites.
I would like to use docker4drupal, on for every site, and this works, I've changed nginx and pma ports.
The problem is that from my site2 I've to connect to the database of site1 (I should use migrate).

**Comment by PavelPrischepa** [comment]
@arrubiu just publish the site1 db port via

```
ports:
 - "83306:3306"
```

then connect to the site1 db from the site2 via localhost:83306 (db config).
