### ISSUE TITLE
[INFO] Helper script for drupal4docker

### ISSUE THREAD

**Issue by bserem** [wodby/docker4drupal#66]
I made this bash script: https://github.com/bserem/DockerDrupalDev
that, when used with a **properly configured docker-compose.yml** file, will start/stop docker, configure Drupal if not configured already, and alias drush to the dockerized drush.

It was made with docker4drupal in mind, since this is what I use at the moment.
The idea is that by a single command, everything will be up and running, easily.

Hope you guys like it.

**Comment by bserem** [comment]
I pushed a branch for D8+composer and seperated the D7 to its own branch.

D8 is not thoroughly tested yet, I just started with it today, but I got Drush working just fine without getting inside the docker container.
Permissions on files created by Drush are wrong, but this doesn't really delay development.

**Comment by csandanov** [comment]
We recommend running commands inside of container as --user 82 (www-data)
