### ISSUE TITLE
Allow running drush in the sshd container

### ISSUE THREAD

**Issue by Vacilando** [wodby/docker4drupal#67]
The sshd container (introduced in  #39) works well -- allows for working in Linux environment even on Windows. Working wish git there is flawless.

One thing that is missing is the ability to execute drush commands. How can that be achieved?

Or is there an alternative? How to change from sshd container to the php container? (docker exec -it does not work there)

**Comment by bserem** [comment]
SSHD container doesn't have PHP (nor drush), that is why you can't run drush in it.
I suppose it would be easier to add SSH to the PHP container, rather than doing anything else.

I spent some time trying to configure docker so as to share binaries between the two containers, but without luck.
I ended up doing this: `alias drush="docker-compose exec --user 82 php drush"`
which led to this https://github.com/bserem/DockerDrupalDev/blob/master/DockerDrupalDev.sh

But the command `docker-compose exec --user 82 php drush` only works for D7 for. It doesn't work for D8+composer, where Drupal resides under a `/web/` folder.

**Comment by Vacilando** [comment]
Indeed, we can execute drush in the php container. The aim of the sshd container (see #39) was to provide a possibility for Windows users to be able to work with the local environment in Linux (instead of having to use the less intuitive PowerShell).

**Comment by bserem** [comment]
However, without the ability to have drush+ssh it is almost impossible to use proper drush aliases.
One **must** run drush in the container, which is such a waste given that with Docker I can have everything in my desktop (editor, debugger, code files etc, only the services are dockerized).
With drush aliases I can run drush commands right from my editor (Vim). Without them I need to have an extra window open **inside** the container just to run drush.

I'd prefer to have SSH alongside PHP and Drush.

**Comment by Vacilando** [comment]
I totally agree with you, @bserem -- it would be wonderful if SSH access could be added to PHP. A separate SSH container would then not be needed.

@PavelPrischepa: in https://github.com/Wodby/docker4drupal/issues/39#issuecomment-249356913 you said 'we can't add sshd to the php container because it'll violate the rule "container per process"'. Do you think you could kindly reconsider in light of this thread?

**Comment by bserem** [comment]
Well, container per process isn't a bad idea, if SSHD container can somehow communicate with the PHP container.
I do not know if this is possible with Docker, and I do not know how to do it!

**Comment by PavelPrischepa** [comment]
@bserem two containers can communicate via volumes, shared unix socket or network.

@Vacilando PHP+SSHD in a container is a specific case. It's possible, but not in a common solution.
So, I suggest you to make a custom container based on `wodby/drupal-php` with SSHD.

Building a custom image is easy with [build directive](https://docs.docker.com/compose/compose-file/#/build) in a compose file.

Popular supervisers (to run more than 1 process in docker):

- https://docs.docker.com/engine/admin/using_supervisord/
- https://github.com/just-containers/s6-overlay

Ask, if you will have questons about configurations `sshd` in Alpine.

**Comment by csandanov** [comment]
As I understand interactive mode is now implemented under windows https://github.com/docker/compose/issues/3194
