### ISSUE TITLE
Allow local overrides of the docker-compose file

### ISSUE THREAD

**Issue by ioskevich** [wodby/docker4drupal#72]
Is there any way to override default settings in the docker-compose.yml (and docker-sync.yml) using local config files? Main goal is to to be able to update docker-compose.yml/docker-sync.yml once they are updated in this repo, but keep local, project-specific customizations (host names, ports, containers used, etc).
Might be something already supported by docker-compose, will appreciate help finding docs if so.

Thanks!

**Comment by csandanov** [comment]
You can create additional compose file and run them together as 
```bash
docker-compose -f docker-compose.yml -f docker-compose-custom.yml up
```
The settings will be merged and AFAIK the next file overrides settings from the previous. As for docker-sync file, I doubt we will update it often and it's expected to be customized.

**Comment by ioskevich** [comment]
Thanks a lot, will try it.
