### ISSUE TITLE
drupal commerce v2

### ISSUE THREAD

**Issue by dcre** [wodby/docker4drupal#74]
Hi

Trying to install drupal commerce v2 via the following command
composer create-project drupalcommerce/project-base mystore --stability dev

i get the following error
 Problem 1
    - Installation request for drupal/commerce 2.x-dev -> satisfiable by drupal/commerce[2.x-dev].
    - drupal/commerce 2.x-dev requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.

Is there a way to overcome this issue? Has anybody tried commerce on docker4drupal?

BR
Giannis

**Comment by PavelPrischepa** [comment]
Hm, it's strange, because I see bcmath in a container:
```
> docker run --rm wodby/drupal-php php -m | grep bcmath
bcmath
```

**Comment by csandanov** [comment]
I'm closing this issue, @dcre please provide more information because it seems the php extension is in place.
