### ISSUE TITLE
"Primary script unknown" on Docker launch

### ISSUE THREAD

**Issue by paperscissors** [wodby/docker4drupal#75]
So I followed the usage instructions in the documentation, and the containers all seem to launch correctly when I `docker-compose up -d` from my Drupal 8 code base.

When I try to visit localhost:8000, however, I get a "File not found" error. Checking the nginx logs I see a `FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream` error.

I've verified I am running the docker-compose up command from my codebase (the root of the Drupal installation) and everything is there--- but it seems like NGINX either can't find the Drupal index.php in root, that NGINX isn't setup for index.php defaults, or the PHP or NGINX container is pointing to the wrong document root. I've tried both / and /index.php to be sure.

Log output is as follows:

```
php_1      | 172.18.0.6 -  30/Dec/2016:23:36:44 +0000 "GET /index.php" 404
nginx_1    | 2016/12/30 23:36:44 [error] 12#12: *4 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.5:9000", host: "localhost:8000"
nginx_1    | 172.18.0.1 - - [30/Dec/2016:23:36:44 +0000] "GET / HTTP/1.1" 404 47 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"
nginx_1    | 172.18.0.1 - - [30/Dec/2016:23:36:44 +0000] "GET /favicon.ico HTTP/1.1" 200 43 "http://localhost:8000/" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"
```

and docker-compose.yml volumes is set to the default:
```
    volumes:
      - ./:/var/www/html
```
everything else in docker-compose.yml is default as well. My host is Fedora 25 workstation, Docker version is 1.12.5, build 6009905/1.12.5

**Comment by csandanov** [comment]
It sounds like you didn't mount your codebase to nginx container, make sure you have the following lines in your nginx service definition.
```yml
volumes_from:
      - php
```

**Comment by f1rf1n** [comment]
For future reference. I encountered this problem because my NGINX_SERVER_ROOT in the php service was set to var/www/html/web instead of var/www/html for a D7 site.

**Comment by neuquen** [comment]
I got the same error and found that the codebase didn't mount properly to my nginx container (see output below).  I have `volumes_from: - php` and I also changed the NGINX_SERVER_ROOT to `var/www/html`.  When I restart the containers it doesn't fix the issue.

How can I force the code to mount itself to the nginx and php containers? I find that sometimes it works and sometimes it doesn't.

Output:

```
PS C:\> docker-compose exec php ls -lah /var/www/html
total 4
drwxr-xr-x    2 www-data www-data      40 Feb 24 17:20 .
drwxr-xr-x    1 www-data www-data    4.0K Dec  5 07:32 ..
PS C:\> docker-compose exec nginx ls -lah /var/www/html
total 4
drwxr-xr-x    2 www-data www-data      40 Feb 24 17:20 .
drwxr-xr-x    3 root     root        4.0K Nov 30 06:22 ..
```
