### ISSUE TITLE
php7.0-intl extension by default inside PHP 7 image

### ISSUE THREAD

**Issue by daliborstojakovic** [wodby/docker4drupal#77]
It would be good to have php7.0-intl by default inside PHP7 image so we don't have to install it additionally via dockerfile

**Comment by PavelPrischepa** [comment]
Hi @daliborstojakovic, I've added intl ext in the latest wodby/drupal-php.

**Comment by csandanov** [comment]
The 2.0.0 images now come with intl extension enabled by default, for more details see https://github.com/wodby/php
