### ISSUE TITLE
Issue logging into site running under docker4drupal [question]

### ISSUE THREAD

**Issue by tcropley** [wodby/docker4drupal#78]
Super impressed with Docker and Docker4Drupal in particular.

Having an issue logging into a site thats running on a Macbook Pro with docker-sync. I've read through the readme and the docs, as well as some generous googling.

Not sure where to start debugging this issue. Not sure this is right place to ask the question, compounded by the fact that I'm not very familiar with nginx configurations. 

I'm able to get site up and running on localhost:8000, all containers working (it seems), db MUST be connected as site pops up, but as soon as I try to log into the site, i get redirected to the home page with the following errors : 

```
php_1      | 172.20.0.6 -  03/Jan/2017:03:49:15 +0000 "GET /index.php" 200
nginx_1    | 172.20.0.1 - - [03/Jan/2017:03:49:15 +0000] "GET /user HTTP/1.1" 200 4166 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36"
php_1      | 172.20.0.6 -  03/Jan/2017:03:49:49 +0000 "POST /index.php" 302
nginx_1    | 172.20.0.1 - - [03/Jan/2017:03:49:49 +0000] "POST /user HTTP/1.1" 302 5 "http://localhost:8000/user" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36"
php_1      | 172.20.0.6 -  03/Jan/2017:03:49:49 +0000 "GET /index.php" 403
nginx_1    | 172.20.0.1 - - [03/Jan/2017:03:49:49 +0000] "GET /?q=user/1 HTTP/1.1" 403 3652 "http://localhost:8000/user" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36"
php_1      | 172.20.0.6 -  03/Jan/2017:03:49:52 +0000 "GET /index.php" 200
nginx_1    | 172.20.0.1 - - [03/Jan/2017:03:49:52 +0000] "GET /user HTTP/1.1" 200 4168 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36"

```
Is this an embarrassing stupid on my part?

Any help would be very, very welcome.

T

**Comment by martinfrances107** [comment]
localhost:8001 is the port for phpMyAdmin ....

if you are looking to confirm the status of the database.

otherwise maybe shell into the php container and have a poke about.

I hope this helps.

**Comment by tcropley** [comment]
Hi Martin,
My problem is actually trying to log into the website. On login (watchdog shows successful login "405  03/Jan 09:16  user      notice    Session opened for admin." ) but I'm redirected to the home page .. and I'm not logged in.

I've tried two different projects and I'm seeing the same behaviour. I disabled the globalredirect module thinking that might be a problem .. and I've set the base_url in the settings.php to localhost:8000

I confess that I haven't tried to log into phpmyadmin -- it's not really important ATM. I _AM_ able to get into the shell's for both the php and the mysql containers  and they appear to both be functioning properly.

Really confused about even where to start digging -- is it an nginx thing? a drupal thing? a docker4drupal container thing? a stupid setting somewhere?

Many thanks.

**Comment by martinfrances107** [comment]
Ok next iteration / suggestion

It may not be obvious to someone new to this particular container setup but look at the link between the containers - if the service definition has a "ports" entry then the container map to ports on the host - in short they are public 

varnish - 8004
nginx - 8000

If you visit 8004 and 8000 maybe you can tease out any difference - and maybe that will uncover the problem.

Are you using D8 or D7 ?

**Comment by tcropley** [comment]
Hi Martin, 

Using D7 and a very simple docker-compose config based on default docker4drupal config:
- mariadb
- php  (drupal-php:5.6-1.0.0) with d4d-unison-sync
- nginx (volumes - php, ports - 8000:80)
- pma (defaults)
- mailhog (defaults)
- uncommented d4d-unison-sync under volumes at the bottom of the page.

**Comment by martinfrances107** [comment]
I am familiar with D8 only 

When you say

"and I've set the base_url in the settings.php to localhost:8000"

Hmm I can't really comment about the d7 setup but manipulating settings.php sounds inconsistent with the docker strategy for D8.

Would you investigate the canonical D7 way of achieving that?

**Comment by tcropley** [comment]
Martin - thank you for your help.  I a couple of the comments you made caused me to dig back in the settings file (settings.php) .. still not 100% what was mis-behaving, but its running much better now.

**Comment by martinfrances107** [comment]
Great, I am glad I to hear things are better now...

**Comment by csandanov** [comment]
So it seems the issue was resolved, feel free to reopen in case you have it again
