### ISSUE TITLE
Drupal can't properly write D8 config files using docker-machine

### ISSUE THREAD

**Issue by iwhitcomb** [wodby/docker4drupal#79]
I'm attempting to use docker-machine to run docker4drupal using the following setup...

```
docker-machine create --driver=virtualbox docker4drupal
eval $(docker-machine env docker4drupal)
docker-compose --host=$DOCKER_HOST up -d
```

I've created my settings.php file and sites/default/files folder(chmod 777).

Everything seems to go perfectly creating a Virtualbox machine called docker4drupal and building the containers. I can view the machine at http://192.168.0.XXX:8000 which gives me the D8 install screen.

When I click through the install I consistently get the following error on the "Verify requirements" step of the install.

> Configuration directory: sync	
> An automated attempt to create the directory sites/default/files/config_csdT0K-H1Kw-NxES8rqgM_p3L3h3Nf03XZVXw5t8SOZ6-PS4Y4mazasHKVcV2O9A_G2k6SI_Wg/sync failed, possibly due to a permissions problem. To proceed with the installation, either create the directory and modify its permissions manually or ensure that the installer has the permissions to create it automatically. For more information, see INSTALL.txt or the online handbook.

I've tried every iteration of chmod and chgrp that I can think of locally, directly on the docker machine, AND the containers to no avail. Any ideas?

**Comment by iwhitcomb** [comment]
Also, if I follow the directions and create the folder and set permissions manually Drupal gives me all sorts of ugly "Warning: mkdir(): Permission denied..." errors all over the site and CSS/JS does not load in the theme.

**Comment by csandanov** [comment]
Is there a specific reason you use docker machine instead of docker 1.12?

**Comment by iwhitcomb** [comment]
Specifically, no, other than for the sake of keeping everything self contained and running in a Linux environment. I'm also on OSX and would like the option of building the machine remotely(on AWS or Softlayer) instead of a vbox if necessary.

I've figured out that I'm able to work as long as I create the config folder(s) manually and disable CSS/JS aggregation. It just seems strange that with full chmod 777 access to the files folder it still struggles.

**Comment by csandanov** [comment]
Just use [docker for mac](https://docs.docker.com/docker-for-mac/) instead of docker machine, you will still have all docker cli tools.
