### ISSUE TITLE
Cannot see my drupal site

### ISSUE THREAD

**Issue by haroldSanchezb** [wodby/docker4drupal#87]
I executed the yaml file, and docker-compose create the containers and the containers start running, but when I try to enter to localhost:8000 site, localhost is not mounted

![image](https://cloud.githubusercontent.com/assets/355510/22513656/a3b1f0c2-e87b-11e6-86eb-8c17f166630a.png)
![image](https://cloud.githubusercontent.com/assets/355510/22513701/c76c726c-e87b-11e6-8847-329c548e022d.png)

PD: I use Ubuntu

**Comment by haroldSanchezb** [comment]
Currently I have a trouble with mount a host volume :(

**Comment by PavelPrischepa** [comment]
What kind of trouble do you have?

**Comment by haroldSanchezb** [comment]
Hi, the first comment I resolved installed again VirtualBox was a trouble with network adapter, the second I thing is very common, I want my drupal project inside of php container, in volumes I put the directory of the drupal project like ./main:/var/www/html but nothing happens, I copy manually the project and exec composer, works now but when I try to connect with the database, drupal not find the db, I put localhost, the docket public ip, the name of the container, but not work.

**Comment by PavelPrischepa** [comment]
You don't need Virtualbox, Docker is all you need. Also check [Getting started](http://docs.docker4drupal.org/en/latest) manual.

**Comment by haroldSanchezb** [comment]
Repost : I want my drupal project inside of php container, in volumes in compose file, I put the directory of the drupal project like ./main:/var/www/html but nothing happens, I copy manually the project and exec composer, works now but when I try to connect with the database, drupal not find the db, I put localhost, the docket public ip, the name of the container, but not work.

**Comment by PavelPrischepa** [comment]
Use **mariadb** (service name in compose file) as a db host instead of **localhost**.

**Comment by PavelPrischepa** [comment]
@haroldSanchezb was it helpful?

**Comment by haroldSanchezb** [comment]
hey thanks a lot, works now :D

**Comment by nrutkowski** [comment]
I am a noob to docker containers and I'm just wondering, why is the host name mariadb? If you open Traefik the host it gives for mariadb is `projectname_mariadb_1.` this is just confusing.
