### ISSUE TITLE
Permission error when using Drush

### ISSUE THREAD

**Issue by idiazroncero** [wodby/docker4drupal#88]
Hi there;

I'm using a fresh, unmodified version of docker4drupal (on Mac OS) and, following the official docs, i'm using this command in order to execute drush as www-data

`docker-compose exec --user 82 php drush`

However, it throws a permissions error

```
[02-Feb-2017 12:35:34 UTC] PHP Warning:  pcntl_exec(): Error has occurred: (errno 13) Permission denied in phar:///usr/local/bin/drush/includes/startup.inc on line 415

Warning: pcntl_exec(): Error has occurred: (errno 13) Permission denied in phar:///usr/local/bin/drush/includes/startup.inc on line 415
Error has occurred executing the Drush script found at /var/www/html/drush
(errno 13) Permission denied
```

Any ideas? Everything seems fine to me - as far as I can tell.

**Comment by PavelPrischepa** [comment]
What version of PHP container do you have?

**Comment by idiazroncero** [comment]
I was trying to spin the docker on an old Drupal7 install, so I choose the 5.6 version.

**Comment by csandanov** [comment]
With d4d 2.0.0 we installed drush globally via composer for www-data user, so there shouldn't be any issues with permission

**Comment by csandanov** [comment]
If you still have this problem with d4d 2.0 feel free to re-open the issue

**Comment by dr-mdbadawi** [comment]
i have the same issue on php 7.1 container

**Comment by csandanov** [comment]
Never use latest, always specify stability tags that we provide in the default docker-compose.yml
