### ISSUE TITLE
Can't use "Install from a URL" 

### ISSUE THREAD

**Issue by GiorgosK** [wodby/docker4drupal#91]
docker-compose finished succesfully and was able to install drupal but trying to add a module with "install from URL" leads to 
`Failed to fetch file due to error "cURL error 6: Couldn't resolve host 'ftp.drupal.org' (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)"
Unable to retrieve Drupal project from https://ftp.drupal.org/files/projects/module_filter-8.x-3.0.tar.gz.`

**Comment by PavelPrischepa** [comment]
Could you ping ftp.drupal.org from the php container?
