### ISSUE TITLE
Avoid usage of volumes_from (deprecated)

### ISSUE THREAD

**Issue by ndobromirov** [wodby/docker4drupal#92]
The docker-compose file directive is depricated and removed as of docker 3
https://docs.docker.com/compose/compose-file/#/volumesfrom

Use global named volumes instead.
https://docs.docker.com/compose/compose-file/#volume-configuration-reference

**Comment by PavelPrischepa** [comment]
@ndobromirov thank you, we'll add global volumes.

**Comment by csandanov** [comment]
Got rid of it in 2.0.0 version
