### ISSUE TITLE
ERROR: for php  No such image: 

### ISSUE THREAD

**Issue by GiorgosK** [wodby/docker4drupal#93]
copying docker-compose.yml 
and running `docker-compose up -d` leads to the following error

> ERROR: for php  No such image: sha256:65b6f6f6f3cc15d5006c247dcdde9b74b1402a03d4eabbdf3b4475c8474fa80a
ERROR: Encountered errors while bringing up the projec

Here is the details from my system 
> Docker version 1.13.0, build 49bf474
docker-compose version 1.10.1, build b252738
docker-py version: 2.0.2
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016

tried to change the php section 
>    image: wodby/drupal-php:7.0-1.0.0

to 
>     image: wodby/drupal-php:7.0
taken from https://github.com/wodby/drupal-php works
but still get the same error 

>ERROR: for php  No such image: sha256:65b6f6f6f3cc15d5006c247dcdde9b74b1402a03d4eabbdf3b4475c8474fa80a
ERROR: Encountered errors while bringing up the project.

**Comment by csandanov** [comment]
Do you have `wodby/drupal-php:7.0-1.0.0` image on your local machine? You can check it with `docker images`. What happens when you execute `docker pull wodby/drupal-php:7.0-1.0.0`?

**Comment by GiorgosK** [comment]
Yes I have it 
>wodby/drupal-php           7.0-1.0.0           e317c5e9d913        8 weeks ago         235 MB

>$ docker pull wodby/drupal-php:7.0-1.0.0
7.0-1.0.0: Pulling from wodby/drupal-php
Digest: sha256:bada98d1ee6177143814540a40719bb06fa3157d65c8d6d64b33b9408f236568
Status: Image is up to date for wodby/drupal-php:7.0-1.0.0

**Comment by csandanov** [comment]
So it seems you have `wodby/drupal-php:7.0-1.0.0` image after all. Make sure you're using the same image for your php service inside of your docker-compose file.
